import "server-only";
import { randomUUID } from "node:crypto";
import { getFirestore } from "firebase-admin/firestore";
import { defaultAdminApp } from "../auth/firebaseAdminAuthAdapter";
import { authorizeWorkerServiceRequest } from "./workerServiceAuthCore";
import type { WorkerServiceKind } from "../../contracts/workerServiceAuth";
const db=()=>getFirestore(defaultAdminApp());
export function authorizeProductionWorker(request:Request,kind:WorkerServiceKind){const expectedId=kind==="files_worker"?process.env.WORKER_FILES_SERVICE_ID:process.env.WORKER_AI_SERVICE_ID,expectedVersion=kind==="files_worker"?process.env.WORKER_FILES_CREDENTIAL_VERSION:process.env.WORKER_AI_CREDENTIAL_VERSION,secret=kind==="files_worker"?process.env.WORKER_FILES_CREDENTIAL:process.env.WORKER_AI_CREDENTIAL;return authorizeWorkerServiceRequest(request,kind,{environment:process.env.NODE_ENV||"production",now:()=>new Date(),secretFor:(id,version)=>id===expectedId&&version===expectedVersion?secret:undefined,getGrant:async id=>(await db().doc(`serviceGrants/${id}`).get()).data(),reserveNonce:async i=>db().runTransaction(async tx=>{const ref=db().doc(`serviceRequestNonces/${i.principalId}:${i.nonce}`),snap=await tx.get(ref);if(snap.exists)return false;tx.create(ref,{schemaVersion:"service-request-nonce.v1",principalId:i.principalId,requestId:i.requestId,expiresAt:i.expiresAt,createdAt:new Date().toISOString()});return true}),ids:()=>({requestId:`service_req_${randomUUID().replace(/-/g,"")}`,correlationId:`service_corr_${randomUUID().replace(/-/g,"")}`})})}
export async function lookupWorkerExecutionReceipt(fingerprint:string){const s=await db().doc(`serviceExecutionCommands/${fingerprint}`).get();const d=s.data();return s.exists&&d?.status==="completed"&&d.receipt?Object.freeze(d.receipt):undefined}
export async function reserveWorkerExecution(input:any){return db().runTransaction(async tx=>{const ref=db().doc(`serviceExecutionCommands/${input.executionFingerprint}`),s=await tx.get(ref);if(s.exists)return s.data()?.status==="completed"?{status:"completed" as const,receipt:s.data()?.receipt}:{status:"running" as const};tx.create(ref,{schemaVersion:"worker-service-command.v1",fingerprint:input.executionFingerprint,principalId:input.principal.servicePrincipalId,grantVersion:input.grant.grantVersion,worker:input.principal.serviceKind,status:"running",createdAt:new Date().toISOString()});return{status:"started" as const}})}
export async function completeWorkerExecution(input:any,receipt:any){await db().runTransaction(async tx=>{const ref=db().doc(`serviceExecutionCommands/${input.executionFingerprint}`),s=await tx.get(ref);if(!s.exists||s.data()?.status!=="running"||s.data()?.principalId!==input.principal.servicePrincipalId)throw Error("stale execution command");tx.update(ref,{status:"completed",receipt,completedAt:new Date().toISOString()})})}
export async function abandonWorkerExecution(input:any){await db().runTransaction(async tx=>{const ref=db().doc(`serviceExecutionCommands/${input.executionFingerprint}`),s=await tx.get(ref);if(s.exists&&s.data()?.status==="running"&&s.data()?.principalId===input.principal.servicePrincipalId)tx.delete(ref)})}
