const stableId=(value:string)=>{let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return(h>>>0).toString(16).padStart(8,"0")};
const createHash=(_:string)=>({update:(value:string)=>({digest:(_:string)=>stableId(value)})});
export const ENTERPRISE_WORKFLOW_VERSION="enterprise-loan-workflow.v1" as const;
export const WORKFLOW_TRANSITION_VERSION="enterprise-transition-registry.v1" as const;
export const WORKFLOW_SLA_POLICY=Object.freeze({version:"workflow-sla.v1",stageTargetHours:Object.freeze({new_submission:24,document_collection:72,processing:24,ready_for_underwriter:8,underwriting:24,suspended:168,approved:24,ready_for_closing:72,closed:0,withdrawn:0,cancelled:0})});
export const LIFECYCLE_STAGES=["new_submission","document_collection","processing","ready_for_underwriter","underwriting","suspended","approved","ready_for_closing","closed","withdrawn","cancelled"] as const;
export const OPERATIONAL_STATUSES=["awaiting_documents","documents_processing","processing_failed","evidence_ready","review_required","conditions_outstanding","ready_for_review","assigned","in_review","awaiting_borrower","awaiting_third_party","ready_to_advance","complete"] as const;
export const PRIORITIES=["urgent","high","normal","low"] as const;
export type LifecycleStage=typeof LIFECYCLE_STAGES[number];export type OperationalStatus=typeof OPERATIONAL_STATUSES[number];export type Priority=typeof PRIORITIES[number];
export type DecisionState="not_evaluated"|"blocked"|"incomplete"|"refer"|"suspended"|"conditionally_approved"|"approved"|"denied";
export type WorkflowAssignment=Readonly<{kind:"unassigned"}|{kind:"user";userId:string;displayName:string|null;role:string|null;assignedAt:string|null;assignedBy:string|null;source:"manual"|"system"}>;
export type WorkflowSla=Readonly<{policyVersion:string;targetHours:number;elapsedHours:number;state:"not_applicable"|"on_track"|"approaching"|"breached"|"paused";dueAt:string|null;pausedReason:string|null}>;
export type EnterpriseWorkflowState=Readonly<{schemaVersion:typeof ENTERPRISE_WORKFLOW_VERSION;workflowVersion:string;applicationId:string;tenantId:string|null;lifecycleStage:LifecycleStage;operationalStatus:OperationalStatus;readinessState:string;decisionState:DecisionState;assignment:WorkflowAssignment;priority:Priority;attention:"critical_blocker"|"sla_breached"|"processing_failed"|"high_review_finding"|"conditions_overdue"|"ready_for_action"|"normal";blockingReasons:readonly string[];outstandingConditionIds:readonly string[];reviewRequiredFindingIds:readonly string[];documentProcessingStatus:"not_started"|"processing"|"failed"|"complete";evidenceProcessingStatus:"not_started"|"invalid"|"valid";mortgageReviewStatus:"not_started"|"blocked"|"review_required"|"clear";sla:WorkflowSla;enteredStageAt:string|null;lastActivityAt:string|null;allowedTransitions:readonly string[];requiredActions:readonly string[];historyReference:string;validation:Readonly<{valid:true;source:"enterprise"|"legacy_adapter"}>}>;
export type WorkflowSource=Readonly<{id:string;tenantId?:string;workflowVersion?:string;authorizationVersion?:string;status?:string;priority?:string;underwriterId?:string;underwriterName?:string;createdAt?:any;updatedAt?:any;dueDate?:any;storedDocs?:readonly unknown[];documentCount?:number;documentProcessingStatus?:string;scan?:any;workflowFacts?:any;uwConditions?:readonly any[];conditions?:readonly any[];enterpriseWorkflow?:Partial<EnterpriseWorkflowState>}>;
const iso=(v:any)=>{if(typeof v==="string"&&Number.isFinite(Date.parse(v)))return new Date(v).toISOString();if(typeof v==="number"&&Number.isFinite(v))return new Date(v).toISOString();if(v?.toDate)return v.toDate().toISOString();return null};
const decision=(v:any):DecisionState=>{const s=String(v||"").toLowerCase();if(s==="approved")return"approved";if(s==="denied"||s==="declined")return"denied";if(s==="blocked")return"blocked";if(s.includes("condition"))return"conditionally_approved";if(s==="refer")return"refer";if(s==="suspended")return"suspended";if(s==="incomplete")return"incomplete";return"not_evaluated"};
const legacyStage=(s:string):LifecycleStage=>{const v=s.toLowerCase();if(v.includes("closed"))return"closed";if(v.includes("withdraw"))return"withdrawn";if(v.includes("cancel"))return"cancelled";if(v.includes("approved"))return"approved";if(v.includes("condition"))return"underwriting";if(v.includes("uw")||v.includes("review"))return"underwriting";return"new_submission"};
export function deriveEnterpriseWorkflow(source:WorkflowSource,now=new Date()):EnterpriseWorkflowState{const scan=source.scan||{},review=scan.mortgageReview||scan.analysis?.mortgageReview,enterprise=scan.enterpriseEvidence||scan.analysis?.enterpriseEvidence,conditions=(source.uwConditions||source.conditions||[]).filter((c:any)=>c?.status!=="done"&&c?.status!=="cleared"),blockingConditions=conditions.filter((c:any)=>c?.blocking||c?.severity==="high"),docs=source.documentCount??source.storedDocs?.length??0,processing=source.documentProcessingStatus||"",reviewStatus=review?.summary?.status||"not_started",decisionState=decision(scan.ai?.verdict||scan.decision?.state||scan.verdict),manual=(source.enterpriseWorkflow?.lifecycleStage||legacyStage(source.status||"")) as LifecycleStage;let stage=manual,status:OperationalStatus="ready_to_advance";const blockers:string[]=[];if(!docs){stage="document_collection";status="awaiting_documents";blockers.push("documents_required")}else if(processing==="processing"){stage="processing";status="documents_processing"}else if(processing==="failed"){stage="processing";status="processing_failed";blockers.push("document_processing_failed")}else if(enterprise?.state==="blocked"||enterprise?.package?.validation?.valid===false){stage="processing";status="processing_failed";blockers.push("evidence_invalid")}else if(reviewStatus==="blocked"||review?.summary?.blocking>0){stage=manual==="underwriting"?"underwriting":"processing";status="review_required";blockers.push("mortgage_review_blocked")}else if(blockingConditions.length){stage="underwriting";status="conditions_outstanding";blockers.push("blocking_conditions_outstanding")}else if(conditions.length){stage="underwriting";status="conditions_outstanding"}else if(reviewStatus==="review_required"){stage="processing";status="review_required"}else if(reviewStatus==="clear"&&!["approved","ready_for_closing","closed"].includes(manual)){stage="ready_for_underwriter";status=source.underwriterId?"assigned":"ready_for_review"}else if(manual==="underwriting")status="in_review";else if(manual==="approved")status="ready_to_advance";else if(manual==="ready_for_closing")status="ready_to_advance";else if(["closed","withdrawn","cancelled"].includes(manual))status="complete";
 const priority=PRIORITIES.includes(source.priority as any)?source.priority as Priority:"normal",entered=iso(source.enterpriseWorkflow?.enteredStageAt)||iso(source.updatedAt)||iso(source.createdAt),last=iso(source.updatedAt)||iso(source.createdAt),target=(WORKFLOW_SLA_POLICY.stageTargetHours as any)[stage]??24,elapsed=entered?Math.max(0,(now.getTime()-Date.parse(entered))/36e5):0,due=iso(source.dueDate)||(entered&&target?new Date(Date.parse(entered)+target*36e5).toISOString():null),terminal=["closed","withdrawn","cancelled"].includes(stage),slaState=terminal||!target?"not_applicable":stage==="suspended"?"paused":elapsed>=target?"breached":elapsed>=target*.8?"approaching":"on_track",attention=blockers.length?"critical_blocker":slaState==="breached"?"sla_breached":status==="processing_failed"?"processing_failed":review?.summary?.high>0?"high_review_finding":stage==="ready_for_underwriter"?"ready_for_action":"normal",assignment:WorkflowAssignment=source.underwriterId?Object.freeze({kind:"user",userId:source.underwriterId,displayName:source.underwriterName||null,role:"underwriter",assignedAt:iso(source.enterpriseWorkflow?.assignment&&(source.enterpriseWorkflow.assignment as any).assignedAt),assignedBy:null,source:"manual"}):Object.freeze({kind:"unassigned"});
 const context={stage,status,decisionState,blockers};const allowed=TRANSITIONS.filter(t=>(t.sources as readonly LifecycleStage[]).includes(stage)&&t.guard(context)).map(t=>t.id);const required=blockers.length?["Resolve system blockers before advancement"]:stage==="document_collection"?["Collect required documents"]:stage==="ready_for_underwriter"?[source.underwriterId?"Begin underwriting review":"Assign an underwriter"]:conditions.length?["Clear outstanding canonical conditions"]:["Perform the next allowed workflow transition"];
 return Object.freeze({schemaVersion:ENTERPRISE_WORKFLOW_VERSION,workflowVersion:source.workflowVersion||source.authorizationVersion||`legacy-${createHash("sha256").update(source.id).digest("hex").slice(0,16)}`,applicationId:source.id,tenantId:source.tenantId||null,lifecycleStage:stage,operationalStatus:status,readinessState:scan.readiness?.readinessLabel||scan.analysis?.readiness?.readinessLabel||"unknown",decisionState,assignment,priority,attention,blockingReasons:Object.freeze(blockers),outstandingConditionIds:Object.freeze(conditions.map((c:any)=>String(c.id||"")).filter(Boolean)),reviewRequiredFindingIds:Object.freeze((review?.findings||[]).filter((f:any)=>f.reviewRequired).map((f:any)=>String(f.findingId))),documentProcessingStatus:!docs?"not_started":processing==="failed"?"failed":processing==="processing"?"processing":"complete",evidenceProcessingStatus:enterprise?.state==="blocked"?"invalid":enterprise?.package?.validation?.valid?"valid":"not_started",mortgageReviewStatus:reviewStatus,slа:undefined as never,...({sla:Object.freeze({policyVersion:WORKFLOW_SLA_POLICY.version,targetHours:target,elapsedHours:Number(elapsed.toFixed(2)),state:slaState,dueAt:due,pausedReason:stage==="suspended"?"workflow_suspended":null})}),enteredStageAt:entered,lastActivityAt:last,allowedTransitions:Object.freeze(allowed),requiredActions:Object.freeze(required),historyReference:`tenants/${source.tenantId||"legacy"}/applications/${source.id}/workflowEvents`,validation:Object.freeze({valid:true,source:source.enterpriseWorkflow?"enterprise":"legacy_adapter"})});}
type GuardContext={stage:LifecycleStage;status:OperationalStatus;decisionState:DecisionState;blockers:string[]};export const TRANSITIONS=Object.freeze([
 {id:"accept_submission",sources:["new_submission"],destination:"document_collection",permission:"queue.manage",reasonRequired:false,assignmentRequired:false,guard:(_:GuardContext)=>true},
 {id:"begin_processing",sources:["document_collection"],destination:"processing",permission:"queue.manage",reasonRequired:false,assignmentRequired:false,guard:(c:GuardContext)=>c.status!=="awaiting_documents"},
 {id:"send_to_underwriting",sources:["processing","ready_for_underwriter"],destination:"underwriting",permission:"queue.manage",reasonRequired:false,assignmentRequired:true,guard:(c:GuardContext)=>!c.blockers.length&&c.status!=="review_required"},
 {id:"suspend",sources:["processing","ready_for_underwriter","underwriting"],destination:"suspended",permission:"queue.manage",reasonRequired:true,assignmentRequired:false,guard:(_:GuardContext)=>true},
 {id:"return_to_processing",sources:["underwriting","suspended"],destination:"processing",permission:"queue.manage",reasonRequired:true,assignmentRequired:false,guard:(_:GuardContext)=>true},
 {id:"approve",sources:["underwriting"],destination:"approved",permission:"decision.approve",reasonRequired:false,assignmentRequired:true,guard:(c:GuardContext)=>!c.blockers.length&&c.decisionState==="approved"},
 {id:"send_to_closing",sources:["approved"],destination:"ready_for_closing",permission:"queue.manage",reasonRequired:false,assignmentRequired:false,guard:(c:GuardContext)=>c.decisionState==="approved"},
 {id:"close",sources:["ready_for_closing"],destination:"closed",permission:"queue.manage",reasonRequired:false,assignmentRequired:false,guard:(c:GuardContext)=>c.decisionState==="approved"},
 {id:"withdraw",sources:["new_submission","document_collection","processing","ready_for_underwriter","underwriting","suspended","approved"],destination:"withdrawn",permission:"queue.manage",reasonRequired:true,assignmentRequired:false,guard:(_:GuardContext)=>true},
 {id:"cancel",sources:["new_submission","document_collection","processing","ready_for_underwriter","underwriting","suspended"],destination:"cancelled",permission:"queue.manage",reasonRequired:true,assignmentRequired:false,guard:(_:GuardContext)=>true},
] as const);
export type QueueItem=Readonly<{applicationId:string;borrowerDisplayName:string;loanNumber:string|null;loanAmount:number|null;stage:LifecycleStage;status:OperationalStatus;decision:DecisionState;owner:string;priority:Priority;attention:EnterpriseWorkflowState["attention"];blockingCount:number;conditionCount:number;reviewRequiredCount:number;documentProcessingStatus:string;lastActivity:string|null;dueDate:string|null;slaState:WorkflowSla["state"];nextAction:string;workflowVersion:string}>;
export const queueItem=(app:WorkflowSource&{borrowerName?:string;loanNumber?:string;loanAmount?:number}):QueueItem=>{const w=deriveEnterpriseWorkflow(app);return Object.freeze({applicationId:app.id,borrowerDisplayName:app.borrowerName||"Borrower pending",loanNumber:app.loanNumber||null,loanAmount:typeof app.loanAmount==="number"?app.loanAmount:null,stage:w.lifecycleStage,status:w.operationalStatus,decision:w.decisionState,owner:w.assignment.kind==="user"?(w.assignment.displayName||w.assignment.userId):"Unassigned",priority:w.priority,attention:w.attention,blockingCount:w.blockingReasons.length,conditionCount:w.outstandingConditionIds.length,reviewRequiredCount:w.reviewRequiredFindingIds.length,documentProcessingStatus:w.documentProcessingStatus,lastActivity:w.lastActivityAt,dueDate:w.sla.dueAt,slaState:w.sla.state,nextAction:w.requiredActions[0]||"Review application",workflowVersion:w.workflowVersion})};
const priorityRank:Record<Priority,number>={urgent:0,high:1,normal:2,low:3},attentionRank:Record<QueueItem["attention"],number>={critical_blocker:0,sla_breached:1,processing_failed:2,high_review_finding:3,conditions_overdue:4,ready_for_action:5,normal:6};export const sortQueue=(items:readonly QueueItem[])=>[...items].sort((a,b)=>attentionRank[a.attention]-attentionRank[b.attention]||priorityRank[a.priority]-priorityRank[b.priority]||String(a.dueDate||"9999").localeCompare(String(b.dueDate||"9999"))||a.applicationId.localeCompare(b.applicationId));
export const workflowMetrics=(items:readonly QueueItem[])=>Object.freeze({totalActive:items.filter(x=>!["closed","withdrawn","cancelled"].includes(x.stage)).length,unassigned:items.filter(x=>x.owner==="Unassigned").length,readyForUnderwriter:items.filter(x=>x.stage==="ready_for_underwriter").length,blocked:items.filter(x=>x.blockingCount>0).length,reviewRequired:items.filter(x=>x.reviewRequiredCount>0||x.status==="review_required").length,conditionsOutstanding:items.filter(x=>x.conditionCount>0).length,slaApproaching:items.filter(x=>x.slaState==="approaching").length,slaBreached:items.filter(x=>x.slaState==="breached").length,approved:items.filter(x=>x.stage==="approved").length,readyForClosing:items.filter(x=>x.stage==="ready_for_closing").length});
