"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useCallback,useEffect,useMemo,useState} from "react";

const title=(v:string)=>String(v||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const tone=(v:string)=>v==="critical"||v==="high"||v==="adverse"||v==="blocked"?"bg-red-100 text-red-800":v==="material"||v==="medium"||v==="med"||v==="review_required"?"bg-amber-100 text-amber-800":v==="favorable"||v==="clear"||v==="approved"?"bg-green-100 text-green-800":"bg-slate-100 text-slate-700";
const Chip=({children,value=""}:{children:any;value?:string})=><span className={`rounded-full px-2 py-1 text-xs font-medium ${tone(value)}`}>{children}</span>;
export default function UnderwriterReviewWorkspace(){
 const id=String((useParams() as any)?.id||""),[workspace,setWorkspace]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState(0),[documentId,setDocumentId]=useState<string|null>(null),[page,setPage]=useState<number|null>(null),[busy,setBusy]=useState(false),[noteDraft,setNoteDraft]=useState("");
 const load=useCallback(async()=>{setError("");const response=await fetch(`/api/applications/${id}/workspace`,{cache:"no-store"}),body=await response.json().catch(()=>null);if(!response.ok||!body?.ok)throw Error(response.status===401?"Your session expired. Sign in and retry.":body?.error?.message||"The review workspace is unavailable.");setWorkspace(body.workspace);setLoading(false)},[id]);
 useEffect(()=>{void load().catch(e=>{setError(e.message);setLoading(false)})},[load]);
 const agenda=workspace?.agenda||[],active=agenda[selected]||null,documents=workspace?.documents||[],activeDocument=documents.find((x:any)=>x.documentId===documentId)||null;
 const openEvidence=(ref:any)=>{if(!ref?.documentId)return;setDocumentId(ref.documentId);setPage(Number.isInteger(ref.pageNumber)?ref.pageNumber:null)};
 useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement;if(["INPUT","TEXTAREA","SELECT"].includes(target?.tagName)||target?.isContentEditable)return;if(event.key==="j"){event.preventDefault();setSelected(x=>Math.min(agenda.length-1,x+1))}else if(event.key==="k"){event.preventDefault();setSelected(x=>Math.max(0,x-1))}else if(event.key==="Escape"){setDocumentId(null);setPage(null)}else if(event.key==="e"&&active?.documentReferences?.[0])openEvidence(active.documentReferences[0])};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[agenda.length,active]);
 const workflowAction=async(transitionId:string)=>{const finalAction=["withdraw","cancel","close"].includes(transitionId);if(finalAction&&!window.confirm(`Confirm ${title(transitionId)}?`))return;const reason=["suspend","return_to_processing","withdraw","cancel"].includes(transitionId)?window.prompt("Reason required")||"":undefined;if(reason!==undefined&&!reason)return;setBusy(true);try{const response=await fetch(`/api/applications/${id}/workflow`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandType:"transition_workflow",transitionId,...(reason?{reason}:{}),expectedVersion:workspace.workflow.workflowVersion,expectedMembershipVersion:workspace.authority.membershipVersion,expectedAuthorizationVersion:workspace.authority.authorizationVersion,idempotencyKey:crypto.randomUUID()})});const body=await response.json().catch(()=>null);if(!response.ok)throw Error(body?.error?.message||body?.code||"Workflow action failed.");await load()}catch(e:any){setError(`${e.message} The workspace was refreshed; the command was not retried.`);await load().catch(()=>{})}finally{setBusy(false)}};
 const decision=async(action:"approve"|"deny")=>{if(!window.confirm(`Confirm final decision: ${title(action)}?`))return;const justificationCode=action==="approve"?"analysis_and_conditions_satisfied":window.prompt("Denial justification code","policy_requirements_not_met");if(!justificationCode)return;setBusy(true);try{const contextResponse=await fetch(`/api/applications/${id}/decision`,{cache:"no-store"}),context=await contextResponse.json();if(!contextResponse.ok||!context.ok)throw Error(context?.error?.message||"Decision context is unavailable.");const response=await fetch(`/api/applications/${id}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,justificationCode,expectedWorkflowVersion:context.expectedWorkflowVersion,expectedDecisionVersion:context.expectedDecisionVersion,expectedAnalysisId:context.expectedAnalysisId,expectedAnalysisVersion:context.expectedAnalysisVersion,expectedAnalysisOutputFingerprint:context.expectedAnalysisOutputFingerprint,expectedEvidenceAggregationFingerprint:context.expectedEvidenceAggregationFingerprint,expectedMembershipVersion:context.expectedMembershipVersion,expectedAuthorizationVersion:context.expectedAuthorizationVersion,expectedApprovalAuthorityVersion:context.approvalAuthorityVersions[action],idempotencyKey:crypto.randomUUID()})}),body=await response.json().catch(()=>null);if(!response.ok)throw Error(body?.error?.message||body?.code||"Decision failed.");await load()}catch(e:any){setError(`${e.message} The workspace was refreshed; the decision was not retried.`);await load().catch(()=>{})}finally{setBusy(false)}};
 const addNote=async()=>{const note=noteDraft.trim();if(!note)return;setBusy(true);try{const response=await fetch(`/api/applications/${id}/workflow`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandType:"add_workflow_note",note,expectedVersion:workspace.workflow.workflowVersion,idempotencyKey:crypto.randomUUID()})}),body=await response.json().catch(()=>null);if(!response.ok)throw Error(body?.error?.message||body?.code||"Note could not be saved.");setNoteDraft("");await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const setConditionStatus=async(conditionId:string,targetStatus:"open"|"done")=>{if(targetStatus==="done"&&!window.confirm("Confirm this condition is resolved using the available evidence?"))return;setBusy(true);try{const response=await fetch(`/api/applications/${id}/workflow`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandType:"set_condition_status",conditionId,targetStatus,expectedVersion:workspace.workflow.workflowVersion,expectedMembershipVersion:workspace.authority.membershipVersion,expectedAuthorizationVersion:workspace.authority.authorizationVersion,idempotencyKey:crypto.randomUUID()})}),body=await response.json().catch(()=>null);if(!response.ok)throw Error(body?.error?.message||body?.code||"Condition action failed.");await load()}catch(e:any){setError(`${e.message} The workspace was refreshed; the command was not retried.`);await load().catch(()=>{})}finally{setBusy(false)}};
 const selectedFinding=useMemo(()=>active?.findingId?workspace?.findings?.find((x:any)=>x.findingId===active.findingId):null,[active,workspace]),selectedCondition=useMemo(()=>active?.conditionId?workspace?.conditions?.find((x:any)=>x.id===active.conditionId):null,[active,workspace]);
 if(loading)return <div className="v-card p-8 text-sm" role="status">Loading authorized underwriter workspace…</div>;
 if(error&&!workspace)return <div className="v-card p-8"><h1 className="font-semibold">Workspace unavailable</h1><p className="text-sm v-muted mt-2">{error}</p><button className="v-btn mt-4" onClick={()=>{setLoading(true);void load().catch(e=>{setError(e.message);setLoading(false)})}}>Retry</button></div>;
 return <div className="space-y-4">
  <header className="v-card p-4 sticky top-0 z-20 bg-white"><div className="flex justify-between gap-3 flex-wrap"><div><Link href="/queue" className="text-xs text-blue-700">← Return to queue</Link><h1 className="text-xl font-semibold mt-1">{workspace.application.borrowerName}</h1><p className="text-xs v-muted">{workspace.application.loanNumber||workspace.application.id} · Analysis v{workspace.application.analysisVersionSequence||"baseline"}</p></div><div className="flex gap-2 flex-wrap items-center"><Chip value={workspace.workflow.attention}>{title(workspace.workflow.attention)}</Chip><Chip value={workspace.workflow.operationalStatus}>{title(workspace.workflow.operationalStatus)}</Chip><Chip value={workspace.workflow.decisionState}>{title(workspace.workflow.decisionState)}</Chip><Chip value={workspace.workflow.sla.state}>SLA {title(workspace.workflow.sla.state)}</Chip>{workspace.changeIntelligence?<Chip value={workspace.changeIntelligence.overallMateriality}>{title(workspace.changeIntelligence.overallMateriality)} change</Chip>:<Chip>Baseline</Chip>}</div></div>{error?<div className="mt-3 rounded-lg bg-red-50 p-2 text-xs text-red-800" role="alert">{error}</div>:null}</header>
  <div className="grid xl:grid-cols-[300px_minmax(420px,1fr)_380px] gap-3 min-h-[70vh]">
   <aside className="v-card p-3 overflow-auto"><div className="flex justify-between"><h2 className="font-semibold text-sm">Review agenda</h2><span className="text-xs v-muted">{agenda.length} items</span></div><p className="text-xs v-muted mt-1">J/K navigates · E opens evidence · Esc closes</p><div className="space-y-2 mt-3">{agenda.length?agenda.map((item:any,index:number)=><button key={item.id} onClick={()=>setSelected(index)} className={`w-full text-left rounded-xl border p-3 focus:outline-none focus:ring-2 focus:ring-blue-500 ${index===selected?"border-blue-400 bg-blue-50":"bg-white"}`}><div className="flex justify-between gap-2"><span className="text-xs font-semibold">{title(item.type)}</span><Chip value={item.severity}>{title(item.severity)}</Chip></div><div className="text-sm font-medium mt-2">{item.title}</div><div className="text-xs v-muted mt-1 line-clamp-2">{item.explanation}</div>{item.linked?<div className="text-xs text-blue-700 mt-1">Finding and condition linked</div>:null}</button>):<div className="text-sm v-muted p-3">No unresolved review items.</div>}</div></aside>
   <main className="v-card overflow-hidden flex flex-col"><div className="p-3 border-b flex justify-between"><div><h2 className="font-semibold text-sm">Authorized document review</h2><p className="text-xs v-muted">{activeDocument?activeDocument.documentType:"Select a document or evidence reference"}</p></div>{activeDocument?<a className="v-btn text-xs" target="_blank" rel="noreferrer" href={`/api/applications/${id}/documents/${activeDocument.documentId}`}>Open separately</a>:null}</div>{activeDocument&&(activeDocument.mimeType==="application/pdf"||activeDocument.mimeType?.startsWith("image/"))?<div className="flex-1 min-h-[620px] bg-slate-100"><iframe title="Authorized document preview" className="w-full h-full min-h-[620px]" src={`/api/applications/${id}/documents/${activeDocument.documentId}${page?`#page=${page}&zoom=page-width`:""}`}/></div>:<div className="flex-1 grid place-items-center p-8 text-center"><div><div className="font-medium">{activeDocument?"Preview unavailable for this file type.":"No document selected"}</div><p className="text-sm v-muted mt-2">{page?`Page-level evidence points to page ${page}; exact highlighting is not available.`:"Choose a document below or open linked evidence."}</p></div></div>}<div className="border-t p-3 flex gap-2 overflow-x-auto">{documents.map((doc:any)=><button key={doc.documentId} className={`rounded-lg border p-2 text-left min-w-40 ${doc.documentId===documentId?"border-blue-400 bg-blue-50":""}`} onClick={()=>{setDocumentId(doc.documentId);setPage(null)}}><div className="text-xs font-medium">{doc.documentType}</div><div className="text-xs v-muted">{title(doc.processingState)} · {doc.evidenceCount} evidence</div>{doc.changed?<span className="text-xs text-amber-700">Changed</span>:null}</button>)}</div></main>
   <aside className="space-y-3 overflow-auto"><section className="v-card p-4"><h2 className="font-semibold text-sm">{active?.title||"Review summary"}</h2><p className="text-sm v-muted mt-2">{active?.explanation||workspace.summary.nextAction}</p>{active?.documentReferences?.length?<div className="mt-3 space-y-1">{active.documentReferences.map((ref:any)=><button key={`${ref.documentId}:${ref.pageNumber}`} className="text-xs text-blue-700 block" onClick={()=>openEvidence(ref)}>Open document {ref.pageNumber?`page ${ref.pageNumber}`:"(page unavailable)"}</button>)}</div>:active?<p className="text-xs v-muted mt-3">No page-level provenance is available for this item.</p>:null}{active?<div className="mt-3 rounded-lg bg-slate-50 p-2 text-xs"><b>Recommended:</b> {active.recommendedAction}</div>:null}{selectedFinding?<details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold">Finding detail</summary><div className="mt-2 space-y-1"><p>{selectedFinding.explanation}</p><p><b>Observed:</b> {selectedFinding.observedValues?.map(String).join(" vs ")||"Not provided"}</p><p><b>Expected:</b> {selectedFinding.expectedRelationship||"Not provided"}</p><p><b>Fields:</b> {selectedFinding.affectedFields?.join(", ")||"None"}</p></div></details>:null}{selectedCondition?<div className="mt-3 text-xs"><b>Condition:</b> {title(selectedCondition.status)} · Owner {title(selectedCondition.owner||"unassigned")}</div>:null}</section>
    <section className="v-card p-4"><h2 className="font-semibold text-sm">Canonical underwriting fields</h2><div className="space-y-2 mt-3">{workspace.canonicalFields.map((field:any)=><details key={field.field} className="rounded-lg border p-2"><summary className="cursor-pointer text-sm"><div className="inline-flex justify-between w-[calc(100%-1rem)] gap-2"><span>{title(field.label)}</span><span className="font-semibold">{String(field.canonicalValue??"Unavailable")}</span></div></summary><div className="mt-2 text-xs space-y-1"><p>{title(field.verificationState)} · {field.sourceCount} sources · {field.conflictCount} conflicts</p><p>{field.resolutionReason||"No resolution explanation available."}</p>{field.sources.map((source:any)=><button key={source.evidenceId} className="block text-left text-blue-700" onClick={()=>openEvidence(source)}>{title(source.role)}: document {source.pageNumber?`page ${source.pageNumber}`:"page unavailable"}</button>)}</div></details>)}</div></section>
    <section className="v-card p-4"><h2 className="font-semibold text-sm">Decision and routing</h2><div className="mt-2 text-xs">{workspace.summary.unresolvedBlockers} blockers · {workspace.summary.reviewRequired} review items</div><div className="flex gap-2 flex-wrap mt-3">{workspace.workflow.allowedTransitions.map((action:string)=><button disabled={busy} key={action} className="v-btn text-xs" onClick={()=>void workflowAction(action)}>{title(action)}</button>)}<button disabled={busy||workspace.summary.unresolvedBlockers>0} className="v-btn-primary text-xs" onClick={()=>void decision("approve")}>Approve</button><button disabled={busy} className="v-btn-danger text-xs" onClick={()=>void decision("deny")}>Deny</button></div></section>
    {selectedCondition?<section className="v-card p-4"><h2 className="font-semibold text-sm">Condition action</h2><p className="text-xs v-muted mt-2">{selectedCondition.title} · {title(selectedCondition.status)} · Owner {title(selectedCondition.owner||"unassigned")}</p><button disabled={busy} className="v-btn mt-3 text-xs" onClick={()=>void setConditionStatus(selectedCondition.id,selectedCondition.status==="done"?"open":"done")}>{selectedCondition.status==="done"?"Reopen condition":"Resolve condition"}</button></section>:null}
    <section className="v-card p-4"><h2 className="font-semibold text-sm">Review note</h2><textarea aria-label="Append-only review note" className="mt-2 w-full rounded-lg border p-2 text-sm" rows={3} maxLength={1000} value={noteDraft} onChange={e=>setNoteDraft(e.target.value)} placeholder="Add a safe review note. Do not include account numbers, SSNs, or document text."/><button className="v-btn mt-2 text-xs" disabled={busy||!noteDraft.trim()} onClick={()=>void addNote()}>Add audit note</button></section>
    {workspace.changeIntelligence?<section className="v-card p-4"><h2 className="font-semibold text-sm">Latest changes</h2><div className="mt-2 flex gap-2"><Chip value={workspace.changeIntelligence.overallMateriality}>{title(workspace.changeIntelligence.overallMateriality)}</Chip><Chip value={workspace.changeIntelligence.overallFavorability}>{title(workspace.changeIntelligence.overallFavorability)}</Chip></div><p className="text-xs mt-3">{workspace.changeIntelligence.recommendedAction}</p></section>:null}
   </aside>
  </div>
 </div>
}
