import { requireAuthenticatedUserRequest } from "../../../../lib/server/auth/userApiAuth";
import { authorizeApplicationAction } from "../../../../lib/server/authorization/applicationAuthorizationOrchestrator";
import { persistAuthorizationAuditEvent } from "../../../../lib/server/authorization/authorizationAuditPersistence";
import { APPLICATION_ACTION_POLICIES } from "../../../../lib/server/authorization/applicationActionPolicies";
import { detailApplicationProjection } from "../../../../lib/server/applications/applicationReadProjection";
import { APPLICATION_READ_ROUTE_POLICY } from "../../../../lib/server/applications/applicationReadRouteCore";

export const dynamic = "force-dynamic";
export async function GET(request: Request, context: { params: { id: string } }) { const auth=await requireAuthenticatedUserRequest(request,APPLICATION_READ_ROUTE_POLICY);if(!auth.ok)return new Response(JSON.stringify({ok:false,error:auth.error}),{status:auth.error.status,headers:{"content-type":"application/json","cache-control":"private, no-store"}});const requestedTenantId=request.headers.get("x-velocity-tenant-id")||undefined,authorization=await authorizeApplicationAction({authentication:auth.context,...(requestedTenantId?{requestedTenantId}:{}),applicationId:context.params.id,permission:"application.read",policy:APPLICATION_ACTION_POLICIES.read,evaluatedAt:new Date().toISOString()});if(!authorization.auditPlan||!authorization.auditPlan.tenantId||!(await persistAuthorizationAuditEvent(authorization.auditPlan,{scope:"tenant",tenantId:authorization.auditPlan.tenantId,persistedAt:new Date().toISOString()})).ok)return new Response(JSON.stringify({ok:false,error:{code:"AUDIT_REQUIRED",message:"Application is unavailable."}}),{status:500,headers:{"content-type":"application/json","cache-control":"private, no-store"}});if(!authorization.ok)return new Response(JSON.stringify({ok:false,error:authorization.publicError}),{status:authorization.publicError.status,headers:{"content-type":"application/json","cache-control":"private, no-store"}});const result=await detailApplicationProjection({auth:auth.context,applicationId:context.params.id,requestedTenantId});return new Response(JSON.stringify(result.ok?result:{ok:false,error:{code:result.code,message:"Application is unavailable."}}),{status:result.status,headers:{"content-type":"application/json","cache-control":"private, no-store"}}); }
