"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
const label=(v:string)=>String(v||"").replace(/_/g," ").replace(/\./g," · ").replace(/\b\w/g,c=>c.toUpperCase());
const tabs=["Organization","Teams","Users","Roles","Permissions","Feature Flags","Governance Policies","Audit Overview","Settings"] as const;
export default function EnterpriseGovernancePage(){
 const[data,setData]=useState<any>(null),[tab,setTab]=useState<typeof tabs[number]>("Organization"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[teamId,setTeamId]=useState(""),[teamName,setTeamName]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/governance/enterprise",{cache:"no-store"}),body=await response.json().catch(()=>null);if(!response.ok||!body?.ok)throw Error(body?.error?.message||"Governance is unavailable.");setData(body.governance);setError("")},[]);
 useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
 const command=async(body:any)=>{setBusy(true);try{const response=await fetch("/api/governance/enterprise",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})}),result=await response.json().catch(()=>null);if(!response.ok||!result?.ok)throw Error(result?.error?.message||result?.error?.code||"Governance command failed.");await load()}catch(e:any){setError(e.message);await load().catch(()=>{})}finally{setBusy(false)}};
 if(error&&!data)return <div className="v-card p-8"><h1 className="font-semibold">Enterprise Governance unavailable</h1><p className="text-sm v-muted mt-2">{error}</p><button className="v-btn mt-4" onClick={()=>void load().catch(e=>setError(e.message))}>Retry</button></div>;
 if(!data)return <div className="v-card p-8 text-sm" role="status">Loading enterprise governance…</div>;
 return <div className="space-y-4"><header className="rounded-2xl bg-slate-950 text-white p-6"><Link href="/admin" className="text-xs text-slate-300">← Admin console</Link><div className="flex justify-between gap-4 flex-wrap mt-2"><div><h1 className="text-2xl font-semibold">Enterprise Administration & Governance</h1><p className="text-sm text-slate-300 mt-2">{data.organization.name} · {label(data.currentActor.role)} · Fail-closed policy evaluation</p></div><div className="text-xs rounded-full bg-white/10 px-3 py-2">Governance v1</div></div></header>{error?<div className="rounded-xl bg-red-50 text-red-800 p-3 text-sm" role="alert">{error}</div>:null}<nav className="v-card p-2 flex gap-1 overflow-x-auto" aria-label="Governance sections">{tabs.map(item=><button key={item} className={`px-3 py-2 rounded-lg text-sm whitespace-nowrap focus:ring-2 focus:ring-blue-500 ${tab===item?"bg-blue-600 text-white":"hover:bg-slate-100"}`} onClick={()=>setTab(item)}>{item}</button>)}</nav>
 {tab==="Organization"?<section className="v-card p-5"><h2 className="font-semibold">Organization</h2><div className="grid md:grid-cols-4 gap-3 mt-4">{[["Tenant",data.organization.tenantId],["Status",label(data.organization.status)],["Members",data.members.length],["Teams",data.teams.filter((x:any)=>x.status==="active").length]].map(([k,v])=><div className="v-card-soft p-3" key={String(k)}><div className="text-xs v-muted">{k}</div><div className="font-semibold mt-1">{v}</div></div>)}</div><p className="text-xs v-muted mt-4">Identity is provided by Firebase Authentication. Tenant membership, role, permissions, teams, approval authority, and feature enablement remain separate governed concepts.</p></section>:null}
 {tab==="Teams"?<section className="v-card p-5"><div className="flex justify-between"><h2 className="font-semibold">Teams</h2><span className="text-xs v-muted">{data.teams.length} configured</span></div>{data.currentActor.canManage?<div className="grid md:grid-cols-[1fr_2fr_auto] gap-2 mt-4"><input className="border rounded-lg p-2 text-sm" placeholder="team-id" value={teamId} onChange={e=>setTeamId(e.target.value)}/><input className="border rounded-lg p-2 text-sm" placeholder="Team name" value={teamName} onChange={e=>setTeamName(e.target.value)}/><button className="v-btn-primary" disabled={busy||!teamId||!teamName} onClick={()=>void command({commandType:"create_team",teamId,name:teamName,managerIds:[],memberIds:[],underwriterIds:[],processorIds:[]}).then(()=>{setTeamId("");setTeamName("")})}>Create team</button></div>:null}<div className="space-y-2 mt-4">{data.teams.map((team:any)=><div className="border rounded-xl p-3 flex justify-between gap-3" key={team.teamId}><div><div className="font-medium text-sm">{team.name}</div><div className="text-xs v-muted">{team.teamId} · {team.memberIds.length} members · {team.underwriterIds.length} underwriters · v{team.version}</div></div><span className="text-xs">{label(team.status)}</span></div>)}{!data.teams.length?<div className="text-sm v-muted">No teams configured. Existing tenant-wide visibility remains unchanged.</div>:null}</div></section>:null}
 {tab==="Users"?<section className="v-card p-5"><h2 className="font-semibold">Users and memberships</h2><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left border-b">{["User","Status","Role","Teams","Last activity","Version"].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.members.map((member:any)=><tr className="border-b" key={member.userId}><td className="p-2 font-medium">{member.userId}</td><td className="p-2">{label(member.status)}</td><td className="p-2">{label(member.role)}</td><td className="p-2">{member.teamIds.join(", ")||"Tenant-wide"}</td><td className="p-2">{member.lastActivityAt?new Date(member.lastActivityAt).toLocaleString():"Unavailable"}</td><td className="p-2 text-xs">{member.version}</td></tr>)}</tbody></table></div></section>:null}
 {tab==="Roles"?<section className="grid md:grid-cols-2 gap-3">{data.roles.filter((r:any)=>!["unknown","service_account"].includes(r.id)).map((role:any)=><div className="v-card p-4" key={role.id}><div className="flex justify-between"><h2 className="font-semibold">{role.label}</h2><span className="text-xs">{role.permissions.length} permissions</span></div><p className="text-xs v-muted mt-2">{role.capabilities.map(label).join(" · ")}</p><div className="mt-3 text-xs"><b>Approval authority:</b> {label(role.approvalAuthority)}</div></div>)}</section>:null}
 {tab==="Permissions"?<section className="v-card p-5"><h2 className="font-semibold">Central permission registry</h2><div className="grid md:grid-cols-3 gap-2 mt-4">{data.permissions.map((permission:any)=><div className="border rounded-lg p-3" key={permission.permission}><div className="text-sm font-medium">{permission.label}</div><div className="text-xs v-muted mt-1">{permission.permission} · {label(permission.category)}</div></div>)}</div></section>:null}
 {tab==="Feature Flags"?<section className="v-card p-5"><h2 className="font-semibold">Tenant feature flags</h2><p className="text-xs v-muted mt-1">Absent flags preserve existing behavior through compatibility-safe defaults.</p><div className="space-y-2 mt-4">{Object.entries(data.featureFlags.values).map(([feature,enabled])=><label key={feature} className="border rounded-xl p-3 flex justify-between"><span className="text-sm">{label(feature)}</span><input type="checkbox" disabled={!data.currentActor.canManage||busy} checked={!!enabled} onChange={e=>void command({commandType:"set_feature",feature,enabled:e.target.checked,expectedVersion:data.featureFlags.version})}/></label>)}</div></section>:null}
 {tab==="Governance Policies"?<section className="v-card p-5"><h2 className="font-semibold">Immutable policy versions</h2><div className="space-y-2 mt-4">{data.policies.map((policy:any)=><div className="border rounded-xl p-3 flex justify-between" key={policy.policyId}><div><div className="text-sm font-medium">{label(policy.type)}</div><div className="text-xs v-muted">{policy.policyId}</div></div><span className="text-xs">v{policy.version} · {label(policy.status)}</span></div>)}{!data.policies.length?<p className="text-sm v-muted">No tenant overrides. Built-in fail-closed governance defaults apply.</p>:null}</div></section>:null}
 {tab==="Audit Overview"?<section className="v-card p-5"><h2 className="font-semibold">Recent governance audit</h2><div className="space-y-2 mt-4">{data.audit.map((event:any)=><div className="border rounded-xl p-3" key={event.eventId}><div className="flex justify-between"><span className="text-sm font-medium">{label(event.action)}</span><span className="text-xs">{label(event.outcome)}</span></div><div className="text-xs v-muted mt-1">{event.entityType} {event.entityId} · {event.actor} · {event.createdAt?new Date(event.createdAt).toLocaleString():"Time unavailable"}</div></div>)}</div></section>:null}
 {tab==="Settings"?<section className="v-card p-5"><h2 className="font-semibold">Governance settings</h2><div className="grid md:grid-cols-2 gap-3 mt-4">{Object.entries(data.safeDefaults).map(([key,value])=><div className="v-card-soft p-3" key={key}><div className="text-xs v-muted">{label(key)}</div><div className="text-sm font-medium mt-1">{label(String(value))}</div></div>)}</div><p className="text-xs v-muted mt-4">Workflow SLA, review, and Change Intelligence defaults continue to use their existing versioned production policies until a compatible tenant override is published.</p></section>:null}
 </div>
}
