import { createHash } from "node:crypto";
import { APPLICATION_EVIDENCE_AGGREGATION_POLICY, aggregateApplicationEvidence, type ApplicationEvidenceSetV1 } from "../evidence/applicationEvidence";
import { extractDocumentEvidence, type DocumentEvidenceSetV1 } from "../evidence/documentEvidence";
import { APPLICATION_ACTION_POLICIES } from "../authorization/applicationActionPolicies";
import { APPLICATION_DOCUMENT_ACTION_POLICIES } from "../authorization/applicationDocumentActionPolicies";
import { DOCUMENT_RETRIEVAL_POLICY, type AuthorizedDocumentBytesV1 } from "../documents/authorizedDocumentBytes";
import { DOCUMENT_PROCESSING_POLICY, type AuthorizedDocumentProcessingResultV1 } from "../documents/authorizedDocumentProcessing";
import type { ServerAuthContextV1 } from "../../contracts/serverAuth";
import type { ApplicationAuthorizationResult } from "../authorization/applicationAuthorizationOrchestratorCore";
import type { ApplicationDocumentAuthorizationResult } from "../authorization/applicationDocumentAuthorizationOrchestratorCore";
import type { AuthorizationAuditPersistenceResult } from "../authorization/authorizationAuditPersistenceCore";
import type { UserApiAuthResult } from "../auth/userApiAuthCore";

export const APPLICATION_ANALYZE_POLICY = Object.freeze({schemaVersion:"application-analyze-policy.v1" as const,status:"provisional_product_review_required" as const,policyVersion:"application-analyze-policy.v1",producerVersion:"application-analyze-route.v1",maximumRequestBytes:4096,maximumDocuments:20,maximumTotalBytes:100*1024*1024,maximumTotalPages:200,maximumTotalText:4_000_000,minimumEvidenceDocuments:1,documentFailureMode:"block_analysis" as const,unsupportedDocumentMode:"block_analysis" as const,missingObjectMode:"block_analysis" as const,lowConfidenceOcrMode:"permit_with_warning" as const,timeoutMode:"fail_closed" as const});
export type ApplicationAnalyzePublicCode="AUTH_REQUIRED"|"AUTH_INVALID"|"TENANT_SELECTION_REQUIRED"|"RESOURCE_NOT_AVAILABLE"|"FORBIDDEN"|"AUDIT_REQUIRED"|"DOCUMENT_NOT_AVAILABLE"|"DOCUMENT_PROCESSING_FAILED"|"EVIDENCE_CONFLICT_REVIEW_REQUIRED"|"ANALYSIS_STALE"|"ANALYSIS_ALREADY_RUNNING"|"ANALYSIS_FAILED"|"INTERNAL_ERROR";
export type ApplicationAnalyzeRequest=Readonly<{requestedTenantId?:string;analysisVersion?:string;idempotencyKey:string}>;
export type AnalyzeInventoryItem=Readonly<{documentId:string}>;
export type AnalysisBeginResult=Readonly<{status:"started";commandId:string}|{status:"completed";response:ApplicationAnalyzeResponse}|{status:"conflict"}|{status:"running"}>;
export type ApplicationAnalyzeResponse=Readonly<{ok:true;status:"completed";applicationId:string;analysisVersion:string;policyVersion:string;evidenceAggregationFingerprint:string;documentCount:number;analysis:unknown;requestId:string;correlationId:string;writeResult:"created"|"already_exists_identical"}>;
export type ApplicationAnalyzeDependencies=Readonly<{
 authenticate(request:Request):Promise<UserApiAuthResult>;
 authorizeApplication(input:any):Promise<ApplicationAuthorizationResult>;
 persistAuthorizationAudit(event:unknown,context:any):Promise<AuthorizationAuditPersistenceResult>;
 listDocuments(input:Readonly<{applicationId:string;tenantId:string}>):Promise<readonly AnalyzeInventoryItem[]>;
 authorizeDocument(input:any):Promise<ApplicationDocumentAuthorizationResult>;
 retrieveBytes(input:any):Promise<Readonly<{ok:true;value:AuthorizedDocumentBytesV1}|{ok:false;code:string}>>;
 processBytes(input:AuthorizedDocumentBytesV1):Promise<Readonly<{ok:true;value:AuthorizedDocumentProcessingResultV1}|{ok:false;code:string}>>;
 analyzeEvidence(evidence:ApplicationEvidenceSetV1,analysisVersion:string):Promise<unknown>;
 begin(input:Readonly<{tenantId:string;applicationId:string;idempotencyKey:string;commandFingerprint:string;requestId:string;correlationId:string;startedAt:string}>):Promise<AnalysisBeginResult>;
 complete(input:Readonly<{tenantId:string;applicationId:string;idempotencyKey:string;commandId:string;commandFingerprint:string;response:ApplicationAnalyzeResponse;applicationAuthorizationVersion:string;documentLineage:ApplicationEvidenceSetV1["documentLineage"];completedAt:string}>):Promise<ApplicationAnalyzeResponse>;
 now():Date; onStep?(step:string):void;
}>;
const id=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const failure=(code:ApplicationAnalyzePublicCode,status:number,requestId?:string,correlationId?:string)=>Object.freeze({ok:false,error:Object.freeze({code,message:messages[code]}),...(requestId?{requestId}:{}),...(correlationId?{correlationId}:{}),status});
const messages:Record<ApplicationAnalyzePublicCode,string>={AUTH_REQUIRED:"Authentication is required.",AUTH_INVALID:"Authentication is invalid.",TENANT_SELECTION_REQUIRED:"A tenant selection is required.",RESOURCE_NOT_AVAILABLE:"The requested resource is not available.",FORBIDDEN:"The requested action is not available.",AUDIT_REQUIRED:"Required audit persistence failed.",DOCUMENT_NOT_AVAILABLE:"A required document is not available.",DOCUMENT_PROCESSING_FAILED:"A required document could not be processed.",EVIDENCE_CONFLICT_REVIEW_REQUIRED:"Conflicting evidence requires review.",ANALYSIS_STALE:"Analysis inputs changed.",ANALYSIS_ALREADY_RUNNING:"Analysis is already running.",ANALYSIS_FAILED:"Analysis could not be completed.",INTERNAL_ERROR:"The request could not be completed."};
function parseRequest(value:unknown):ApplicationAnalyzeRequest|undefined{if(!value||typeof value!=="object"||Array.isArray(value))return;const x=value as any,keys=Object.keys(x),allowed=new Set(["requestedTenantId","analysisVersion","idempotencyKey"]);if(keys.some(k=>!allowed.has(k))||!id.test(x.idempotencyKey||"")||(x.requestedTenantId!==undefined&&!id.test(x.requestedTenantId))||(x.analysisVersion!==undefined&&!id.test(x.analysisVersion)))return;return Object.freeze({...(x.requestedTenantId?{requestedTenantId:x.requestedTenantId}:{}),...(x.analysisVersion?{analysisVersion:x.analysisVersion}:{}),idempotencyKey:x.idempotencyKey})}
async function audit(d:ApplicationAnalyzeDependencies,event:any,tenantId:string,at:string){const result=await d.persistAuthorizationAudit(event,{scope:"tenant",tenantId,persistedAt:at});return result.ok}
export async function executeApplicationAnalyzeRoute(request:Request,applicationId:unknown,body:unknown,d:ApplicationAnalyzeDependencies):Promise<any>{
 const step=(s:string)=>d.onStep?.(s);step("validate_request");if(request.method!=="POST")return failure("INTERNAL_ERROR",405);const parsed=parseRequest(body);if(!parsed)return failure("INTERNAL_ERROR",400);
 step("authenticate");const authenticated=await d.authenticate(request);if(!authenticated.ok)return failure(authenticated.error.code==="AUTH_REQUIRED"?"AUTH_REQUIRED":"AUTH_INVALID",authenticated.error.status,authenticated.error.requestId,"correlationId" in authenticated?authenticated.correlationId:authenticated.context.correlationId);const auth=authenticated.context as ServerAuthContextV1;
 step("validate_application_id");if(typeof applicationId!=="string"||!id.test(applicationId))return failure("RESOURCE_NOT_AVAILABLE",404,auth.requestId,auth.correlationId);
 step("authorize_application");const app=await d.authorizeApplication({authentication:auth,...(parsed.requestedTenantId?{requestedTenantId:parsed.requestedTenantId}:{}),applicationId,permission:"application.analyze",policy:APPLICATION_ACTION_POLICIES.analyze,evaluatedAt:d.now().toISOString()});if(!app.ok){if(app.auditPlan&&app.auditPlan.tenantId)await audit(d,app.auditPlan,app.auditPlan.tenantId,d.now().toISOString());const code=app.publicError.code==="TENANT_SELECTION_REQUIRED"?"TENANT_SELECTION_REQUIRED":app.publicError.code==="RESOURCE_NOT_AVAILABLE"?"RESOURCE_NOT_AVAILABLE":app.publicError.code==="FORBIDDEN"?"FORBIDDEN":"INTERNAL_ERROR";return failure(code,app.publicError.status,auth.requestId,auth.correlationId)}
 step("persist_application_audit");if(!await audit(d,app.auditPlan,app.context.tenantId,d.now().toISOString()))return failure("AUDIT_REQUIRED",500,auth.requestId,auth.correlationId);
 step("resolve_document_inventory");let inventory;try{inventory=[...await d.listDocuments({applicationId,tenantId:app.context.tenantId})].sort((a,b)=>a.documentId.localeCompare(b.documentId))}catch{return failure("DOCUMENT_NOT_AVAILABLE",404,auth.requestId,auth.correlationId)}if(!inventory.length||inventory.length>APPLICATION_ANALYZE_POLICY.maximumDocuments||inventory.some(x=>!id.test(x.documentId)))return failure("DOCUMENT_NOT_AVAILABLE",404,auth.requestId,auth.correlationId);
 const evidence:DocumentEvidenceSetV1[]=[];let totalBytes=0,totalPages=0,totalText=0;
 for(const item of inventory){step(`resolve_document:${item.documentId}`);step(`authorize_document:${item.documentId}`);const doc=await d.authorizeDocument({authentication:auth,...(parsed.requestedTenantId?{requestedTenantId:parsed.requestedTenantId}:{}),applicationId,documentId:item.documentId,permission:"document.read",policy:APPLICATION_DOCUMENT_ACTION_POLICIES.read,evaluatedAt:d.now().toISOString()});if(!doc.ok){const plan=(doc as any).auditPlan;if(plan?.event?.tenantId)await audit(d,plan.event,plan.event.tenantId,d.now().toISOString());return failure("DOCUMENT_NOT_AVAILABLE",404,auth.requestId,auth.correlationId)}
  step(`persist_document_audit:${item.documentId}`);if(!await audit(d,doc.auditPlan.event,doc.context.tenantId,d.now().toISOString()))return failure("AUDIT_REQUIRED",500,auth.requestId,auth.correlationId);
  step(`retrieve_bytes:${item.documentId}`);const bytes=await d.retrieveBytes({authorization:doc,expectedApplicationId:applicationId,expectedDocumentId:item.documentId,expectedDocumentAuthorizationVersion:doc.documentFacts.documentAuthorizationVersion,policy:DOCUMENT_RETRIEVAL_POLICY,requestId:auth.requestId,correlationId:auth.correlationId});if(!bytes.ok)return failure("DOCUMENT_NOT_AVAILABLE",404,auth.requestId,auth.correlationId);totalBytes+=bytes.value.sizeBytes;if(totalBytes>APPLICATION_ANALYZE_POLICY.maximumTotalBytes)return failure("DOCUMENT_PROCESSING_FAILED",422,auth.requestId,auth.correlationId);
  step(`process_bytes:${item.documentId}`);const processed=await d.processBytes(bytes.value);if(!processed.ok)return failure("DOCUMENT_PROCESSING_FAILED",422,auth.requestId,auth.correlationId);totalPages+=processed.value.pageCount;totalText+=processed.value.normalizedText.length;if(totalPages>APPLICATION_ANALYZE_POLICY.maximumTotalPages||totalText>APPLICATION_ANALYZE_POLICY.maximumTotalText)return failure("DOCUMENT_PROCESSING_FAILED",422,auth.requestId,auth.correlationId);
  step(`extract_evidence:${item.documentId}`);evidence.push(extractDocumentEvidence(processed.value));
 }
 if(evidence.length<APPLICATION_ANALYZE_POLICY.minimumEvidenceDocuments)return failure("DOCUMENT_PROCESSING_FAILED",422,auth.requestId,auth.correlationId);
 step("aggregate_evidence");let aggregation:ApplicationEvidenceSetV1;try{aggregation=aggregateApplicationEvidence(evidence,APPLICATION_EVIDENCE_AGGREGATION_POLICY,{aggregatedAt:d.now().toISOString(),requestId:auth.requestId,correlationId:auth.correlationId})}catch{return failure("ANALYSIS_FAILED",500,auth.requestId,auth.correlationId)}if(aggregation.conflictGroups.length)return failure("EVIDENCE_CONFLICT_REVIEW_REQUIRED",409,auth.requestId,auth.correlationId);
 const analysisVersion=parsed.analysisVersion||"canonical-evidence-analysis.v1",commandFingerprint=hash({tenantId:app.context.tenantId,applicationId,applicationAuthorizationVersion:app.applicationFacts.resourceAuthorizationVersion,lineage:aggregation.documentLineage,aggregationFingerprint:aggregation.aggregationFingerprint,analysisVersion,policyVersion:APPLICATION_ANALYZE_POLICY.policyVersion});
 step("begin_idempotent_analysis");const begun=await d.begin({tenantId:app.context.tenantId,applicationId,idempotencyKey:parsed.idempotencyKey,commandFingerprint,requestId:auth.requestId,correlationId:auth.correlationId,startedAt:d.now().toISOString()});if(begun.status==="completed")return Object.freeze({...begun.response,writeResult:"already_exists_identical"});if(begun.status==="conflict")return failure("ANALYSIS_STALE",409,auth.requestId,auth.correlationId);if(begun.status==="running")return failure("ANALYSIS_ALREADY_RUNNING",409,auth.requestId,auth.correlationId);
 step("analyze_canonical_evidence");let analysis;try{analysis=await d.analyzeEvidence(aggregation,analysisVersion)}catch{return failure("ANALYSIS_FAILED",500,auth.requestId,auth.correlationId)}const response=Object.freeze({ok:true as const,status:"completed" as const,applicationId,analysisVersion,policyVersion:APPLICATION_ANALYZE_POLICY.policyVersion,evidenceAggregationFingerprint:aggregation.aggregationFingerprint,documentCount:aggregation.documentLineage.length,analysis,requestId:auth.requestId,correlationId:auth.correlationId,writeResult:"created" as const});
 step("persist_analysis_and_audit");try{return await d.complete({tenantId:app.context.tenantId,applicationId,idempotencyKey:parsed.idempotencyKey,commandId:begun.commandId,commandFingerprint,response,applicationAuthorizationVersion:app.applicationFacts.resourceAuthorizationVersion,documentLineage:aggregation.documentLineage,completedAt:d.now().toISOString()})}catch{return failure("ANALYSIS_STALE",409,auth.requestId,auth.correlationId)}
}
