import "server-only";
import {createHash} from "node:crypto";
import {getFirestore} from "firebase-admin/firestore";
import {defaultAdminApp} from "../auth/firebaseAdminAuthAdapter";
import {analyzeApplication} from "../../ai/analyzeApplication";
import {APPROVED_DOCUMENT_PROCESSING_DEPENDENCIES} from "../documents/authorizedDocumentProcessingAdapter";
import {DOCUMENT_PROCESSING_POLICY,processAuthorizedDocumentBytes} from "../documents/authorizedDocumentProcessing";
import type {ApplicationEvidenceSetV1} from "../evidence/applicationEvidence";
import type {ApplicationAnalyzeResponse} from "./applicationAnalyzeRouteCore";
import {buildEnterpriseReview,evidenceDocs} from "./enterpriseEvidenceReview";
import {buildUnderwritingReport} from "../../ai/buildUnderwritingReport";
import {conditionsFromMortgageReview,evaluateMortgageReview} from "../../mortgage/review/engine";
import {compareSnapshots,createAnalysisSnapshot,historyEntry,type AnalysisSnapshot} from "../../change-intelligence/engine";
const db=()=>getFirestore(defaultAdminApp());
export async function listCanonicalApplicationDocuments(input:Readonly<{applicationId:string;tenantId:string}>){const snap=await db().collection("applicationDocuments").where("applicationId","==",input.applicationId).get();return Object.freeze(snap.docs.map(doc=>Object.freeze({documentId:doc.id})).sort((a,b)=>a.documentId.localeCompare(b.documentId)))}
export const processCanonicalAuthorizedBytes=(input:any)=>processAuthorizedDocumentBytes(input,DOCUMENT_PROCESSING_POLICY,APPROVED_DOCUMENT_PROCESSING_DEPENDENCIES);
export async function analyzeCanonicalEvidence(evidence:ApplicationEvidenceSetV1,analysisVersion:string){const analysis=await analyzeApplication(evidenceDocs(evidence),{applicationId:evidence.applicationId,analysisVersion});const enterpriseEvidence=buildEnterpriseReview(evidence,analysis);const mortgageReview=evaluateMortgageReview(evidence.applicationId,enterpriseEvidence.package,analysis);const generated=conditionsFromMortgageReview(mortgageReview,enterpriseEvidence.package),conditionIds=new Set(analysis.canonicalConditions?.map(c=>c.id)||[]),canonicalConditions=Object.freeze([...(analysis.canonicalConditions||[]),...generated.filter(c=>!conditionIds.has(c.id))]);const reviewed=Object.freeze({...analysis,canonicalConditions,mortgageReview,enterpriseEvidence});const report=buildUnderwritingReport(reviewed as any,{borrower:analysis.normalized.borrower,loanNumber:analysis.normalized.loanNumber,loanAmount:analysis.normalized.loanAmount??undefined,propertyValue:analysis.normalized.propertyValue??undefined,income:analysis.normalized.income??undefined,debts:analysis.normalized.debts??undefined,assets:analysis.normalized.assets??undefined});return Object.freeze({...reviewed,ai:reviewed,report})}
export async function beginCanonicalAnalysis(input:any){const commandId=`analysis_${createHash("sha256").update(JSON.stringify([input.tenantId,input.applicationId,input.idempotencyKey])).digest("hex").slice(0,32)}`,ref=db().doc(`tenants/${input.tenantId}/applications/${input.applicationId}/analysisCommands/${input.idempotencyKey}`);return db().runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.exists){const data=snap.data()!;if(data.commandFingerprint!==input.commandFingerprint)return{status:"conflict" as const};if(data.status==="completed")return{status:"completed" as const,response:data.response as ApplicationAnalyzeResponse};return{status:"running" as const}}tx.create(ref,{schemaVersion:"application-analysis-command.v1",commandId,commandFingerprint:input.commandFingerprint,status:"running",requestId:input.requestId,correlationId:input.correlationId,startedAt:input.startedAt});return{status:"started" as const,commandId}})}
export async function completeCanonicalAnalysis(input:any){
 const root=`tenants/${input.tenantId}/applications/${input.applicationId}`,commandRef=db().doc(`${root}/analysisCommands/${input.idempotencyKey}`),stateRef=db().doc(`${root}/analysisState/current`),auditRef=db().doc(`${root}/analysisAuditEvents/${input.commandId}`),versionRef=db().doc(`${root}/analysisVersions/current`),appRef=db().doc(`applications/${input.applicationId}`);
 return db().runTransaction(async tx=>{
  const [commandSnap,versionSnap]=await Promise.all([tx.get(commandRef),tx.get(versionRef)]);
  if(!commandSnap.exists||commandSnap.data()?.status!=="running"||commandSnap.data()?.commandFingerprint!==input.commandFingerprint)throw Error("ANALYSIS_STALE");
  const active=versionSnap.data()||{},priorId=typeof active.snapshotId==="string"?active.snapshotId:null,priorRef=priorId?db().doc(`${root}/analysisSnapshots/${priorId}`):null,priorSnap=priorRef?await tx.get(priorRef):null,prior=priorSnap?.exists?priorSnap.data() as AnalysisSnapshot:null;
  if(priorId&&!prior)throw Error("ANALYSIS_VERSION_POINTER_INVALID");
  const analysis=input.response.analysis||{},priorDocumentIds=new Set((prior?.documents||[]).map(x=>x.documentId)),currentDocumentIds=new Set((input.documentLineage||[]).map((x:any)=>String(x.documentId))),triggerType=!prior?"initial_analysis":(input.documentLineage||[]).some((x:any)=>!priorDocumentIds.has(String(x.documentId)))?"document_added":prior.documents.some(x=>!currentDocumentIds.has(x.documentId))?"document_removed":prior.documents.some(x=>(input.documentLineage||[]).find((d:any)=>String(d.documentId)===x.documentId)?.processingFingerprint!==x.processingIdentity)?"document_reprocessed":"manual_reanalysis",snapshot=createAnalysisSnapshot({applicationId:input.applicationId,tenantId:input.tenantId,sequence:prior?prior.sequence+1:1,parentSnapshotId:prior?.snapshotId||null,analysis,documentLineage:input.documentLineage,createdAt:input.completedAt,triggerType});
  const equivalent=prior?.snapshotId===snapshot.snapshotId,change=!equivalent&&prior?compareSnapshots(prior,snapshot):undefined,entry=historyEntry(equivalent&&prior?prior:snapshot,change),nextHistory=equivalent?(active.history||[entry]):[entry,...(Array.isArray(active.history)?active.history:[])].slice(0,20),report=change?buildUnderwritingReport({...analysis,changeIntelligence:change} as any,{borrower:analysis.normalized?.borrower,loanNumber:analysis.normalized?.loanNumber,loanAmount:analysis.normalized?.loanAmount,propertyValue:analysis.normalized?.propertyValue,income:analysis.normalized?.income,debts:analysis.normalized?.debts,assets:analysis.normalized?.assets}):analysis.report,finalResponse=Object.freeze({...input.response,analysis:Object.freeze({...analysis,report,changeIntelligence:change||null,analysisSnapshotId:equivalent?prior?.snapshotId:snapshot.snapshotId})});
  tx.set(stateRef,{schemaVersion:"application-analysis-state.v1",commandId:input.commandId,applicationAuthorizationVersion:input.applicationAuthorizationVersion,documentLineage:input.documentLineage,evidenceAggregationFingerprint:input.response.evidenceAggregationFingerprint,analysisVersion:input.response.analysisVersion,policyVersion:input.response.policyVersion,completedAt:input.completedAt},{merge:false});
  tx.create(auditRef,{schemaVersion:"application-analysis-audit.v1",commandId:input.commandId,requestId:input.response.requestId,correlationId:input.response.correlationId,evidenceAggregationFingerprint:input.response.evidenceAggregationFingerprint,analysisVersion:input.response.analysisVersion,policyVersion:input.response.policyVersion,documentCount:input.response.documentCount,completedAt:input.completedAt,piiPresent:false,snapshotId:equivalent?prior?.snapshotId:snapshot.snapshotId,equivalentState:equivalent});
  if(!equivalent){
   tx.create(db().doc(`${root}/analysisSnapshots/${snapshot.snapshotId}`),snapshot);
   if(change)tx.create(db().doc(`${root}/changePackages/${change.packageId}`),change);
   tx.set(versionRef,{schemaVersion:"application-analysis-active-version.v1",snapshotId:snapshot.snapshotId,previousSnapshotId:prior?.snapshotId||null,sequence:snapshot.sequence,changePackageId:change?.packageId||null,history:nextHistory,updatedAt:input.completedAt},{merge:false});
  }
  const changeSummary=change?{packageId:change.packageId,snapshotId:change.currentSnapshotId,priorSnapshotId:change.priorSnapshotId,overallMateriality:change.overallMateriality,overallFavorability:change.overallFavorability,reReviewRequired:change.reReviewRequired,recommendedAction:change.recommendedAction,summary:change.summary,changes:change.changes.map(x=>({changeId:x.changeId,category:x.category,changeType:x.changeType,entityType:x.entityType,entityId:x.entityId,direction:x.direction,materiality:x.materiality,favorability:x.favorability,explanation:x.explanation,recommendedAction:x.recommendedAction,reviewRequired:x.reviewRequired,blocking:x.blocking})),createdAt:input.completedAt}:null;
  tx.update(appRef,{documentCount:input.response.documentCount,documentProcessingStatus:"complete",currentAnalysisSnapshotId:equivalent?prior?.snapshotId:snapshot.snapshotId,analysisVersionSequence:equivalent?prior?.sequence:snapshot.sequence,analysisVersionHistory:equivalent?active.history||[entry]:[entry,...(Array.isArray(active.history)?active.history:[])].slice(0,20),latestChangeSummary:changeSummary,workflowFacts:{mortgageReview:{summary:analysis.mortgageReview?.summary||null,findings:(analysis.mortgageReview?.findings||[]).map((f:any)=>({findingId:f.findingId,reviewRequired:f.reviewRequired,blocking:f.blocking,severity:f.severity}))},enterpriseEvidence:{state:analysis.enterpriseEvidence?.state||"not_started",package:{validation:analysis.enterpriseEvidence?.package?.validation||null}},readiness:analysis.readiness||null,decision:analysis.decision||null,analysisVersion:input.response.analysisVersion,evidencePackageId:analysis.enterpriseEvidence?.package?.packageId||null,changeIntelligence:changeSummary},updatedAt:new Date(input.completedAt)});
  tx.update(commandRef,{status:"completed",response:finalResponse,completedAt:input.completedAt});
  return finalResponse;
 })
}
