import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { FieldPath, Timestamp, getFirestore } from "firebase-admin/firestore";
import { defaultAdminApp } from "../auth/firebaseAdminAuthAdapter";
import { resolveTenantAuthorizationContext } from "../authorization/tenantAuthorizationResolver";
import { permissionsForRole } from "../authorization/permissionPolicy";
import type { ServerAuthContextV1 } from "../../contracts/serverAuth";

const PAGE_DEFAULT = 80, PAGE_MAX = 100, FALLBACK_SCAN_MAX = 1000;
const LIST_FIELDS = ["borrowerName","email","loanNumber","loanAmount","status","underwriterId","underwriterName","assignedUnderwriterId","borrowerProfileVerified","uwConditions","conditions","workflowVersion","authorizationVersion","priority","dueDate","enterpriseWorkflow","workflowFacts","documentCount","documentProcessingStatus","createdAt","updatedAt"] as const;
const DETAIL_FIELDS = ["borrowerName","email","loanNumber","loanAmount","status","underwriterId","underwriterName","assignedUnderwriterId","notes","scan","borrowerProfile","borrowerProfileVerified","uwConditions","conditions","workflowVersion","authorizationVersion","priority","dueDate","enterpriseWorkflow","workflowFacts","documentCount","documentProcessingStatus","createdAt","updatedAt"] as const;
type Cursor = Readonly<{ tenantId:string; updatedAtMs:number; id:string }>;
const safeId=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const secret=()=>process.env.APPLICATION_READ_CURSOR_SECRET||process.env.SESSION_COOKIE_SECRET||"";
const normalize=(value:any):any=>value instanceof Timestamp?value.toMillis():Array.isArray(value)?value.map(normalize):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,normalize(v)])):value;
const project=(id:string,data:any,fields:readonly string[]):Readonly<Record<string,any>>=>Object.freeze({id,...Object.fromEntries(fields.filter(k=>data[k]!==undefined).map(k=>[k,normalize(data[k])]))});
function encodeCursor(value:Cursor){const key=secret();if(key.length<32)throw Error("APPLICATION_READ_CURSOR_SECRET_REQUIRED");const payload=Buffer.from(JSON.stringify(value)).toString("base64url"),signature=createHmac("sha256",key).update(payload).digest("base64url");return `${payload}.${signature}`}
function decodeCursor(input:string|undefined,tenantId:string):Cursor|undefined{if(!input)return;const key=secret();if(key.length<32)throw Error("APPLICATION_READ_CURSOR_SECRET_REQUIRED");const [payload,sig,...extra]=input.split(".");if(!payload||!sig||extra.length)return;const expected=createHmac("sha256",key).update(payload).digest();let actual:Buffer;try{actual=Buffer.from(sig,"base64url")}catch{return}if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return;try{const x=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));if(x.tenantId!==tenantId||!Number.isSafeInteger(x.updatedAtMs)||!safeId.test(x.id))return;return x}catch{return}}
async function context(auth:ServerAuthContextV1,requestedTenantId?:string){const resolved=await resolveTenantAuthorizationContext({authentication:auth,...(requestedTenantId?{requestedTenantId}:{})});if(!resolved.ok)return {ok:false as const,status:resolved.error.status,code:resolved.error.code};if(!permissionsForRole(resolved.context.role).includes("application.read"))return {ok:false as const,status:403,code:"FORBIDDEN"};return {ok:true as const,value:resolved.context}}
async function audit(tenantId:string,auth:ServerAuthContextV1,action:string,outcome:string){await getFirestore(defaultAdminApp()).doc(`tenants/${tenantId}/applicationReadProjectionAudit/${auth.requestId}:${action}`).create({schemaVersion:"application-read-projection-audit.v1",action,outcome,principalReference:auth.principal.kind==="firebase_user"?auth.principal.uid:"invalid",requestId:auth.requestId,correlationId:auth.correlationId,piiPresent:false,createdAt:new Date().toISOString()}).catch((e:any)=>{if(e?.code!==6&&e?.code!=="already-exists")throw e})}
async function applicationPage(tenantId:string,pageSize:number,cursor:Cursor|undefined){let q:any=getFirestore(defaultAdminApp()).collection("applications").where("tenantId","==",tenantId).orderBy("updatedAt","desc").orderBy(FieldPath.documentId(),"desc");if(cursor)q=q.startAfter(Timestamp.fromMillis(cursor.updatedAtMs),cursor.id);try{return await q.limit(pageSize+1).get()}catch(error:any){if(error?.code!==9&&error?.code!=="failed-precondition")throw error;const fallback=await getFirestore(defaultAdminApp()).collection("applications").where("tenantId","==",tenantId).limit(FALLBACK_SCAN_MAX+1).get();if(fallback.size>FALLBACK_SCAN_MAX)throw Object.assign(new Error("APPLICATION_READ_INDEX_REQUIRED"),{code:"APPLICATION_READ_INDEX_REQUIRED"});const ordered=[...fallback.docs].sort((a:any,b:any)=>{const am=a.get("updatedAt")?.toMillis?.(),bm=b.get("updatedAt")?.toMillis?.();if(!Number.isSafeInteger(am)||!Number.isSafeInteger(bm))throw Object.assign(new Error("APPLICATION_UPDATED_AT_INVALID"),{code:"APPLICATION_UPDATED_AT_INVALID"});return bm-am||b.id.localeCompare(a.id)});const eligible=cursor?ordered.filter((d:any)=>{const ms=d.get("updatedAt").toMillis();return ms<cursor.updatedAtMs||(ms===cursor.updatedAtMs&&d.id<cursor.id)}):ordered;return Object.freeze({docs:eligible.slice(0,pageSize+1)})}}
export async function listApplicationProjection(input:{auth:ServerAuthContextV1;requestedTenantId?:string;pageSize?:string|null;cursor?:string|null}){const c=await context(input.auth,input.requestedTenantId);if(!c.ok)return c;const pageSize=input.pageSize===null||input.pageSize===undefined?PAGE_DEFAULT:Number(input.pageSize);if(!Number.isInteger(pageSize)||pageSize<1||pageSize>PAGE_MAX)return {ok:false as const,status:400,code:"INVALID_QUERY"};const cursor=decodeCursor(input.cursor||undefined,c.value.tenantId);if(input.cursor&&!cursor)return {ok:false as const,status:400,code:"INVALID_CURSOR"};const snapshot=await applicationPage(c.value.tenantId,pageSize,cursor);const docs=snapshot.docs.slice(0,pageSize),hasMore=snapshot.docs.length>pageSize,last=docs.at(-1);await audit(c.value.tenantId,input.auth,"application.list","allowed");return {ok:true as const,status:200,schemaVersion:"application-list-projection.v1",applications:docs.map((d:any)=>project(d.id,d.data(),LIST_FIELDS)),assignees:await listAssignees(c.value.tenantId),nextCursor:hasMore&&last?encodeCursor({tenantId:c.value.tenantId,updatedAtMs:last.get("updatedAt").toMillis(),id:last.id}):null,requestId:input.auth.requestId,correlationId:input.auth.correlationId}}
async function listAssignees(tenantId:string){const members=await getFirestore(defaultAdminApp()).collection(`tenants/${tenantId}/members`).where("membershipStatus","==","active").where("role","==","underwriter").limit(100).get();const ids=members.docs.map(d=>d.id);if(!ids.length)return[];const legacy=await getFirestore(defaultAdminApp()).getAll(...ids.map(id=>getFirestore(defaultAdminApp()).doc(`underwriters/${id}`)));return ids.map((id,i)=>{const d=legacy[i].data()||{};return Object.freeze({id,...(typeof d.name==="string"?{name:d.name}:{}),...(typeof d.email==="string"?{email:d.email}:{}),active:true})})}
export async function detailApplicationProjection(input:{auth:ServerAuthContextV1;applicationId:string;requestedTenantId?:string}){if(!safeId.test(input.applicationId))return {ok:false as const,status:404,code:"RESOURCE_NOT_AVAILABLE"};const c=await context(input.auth,input.requestedTenantId);if(!c.ok)return c;const snapshot=await getFirestore(defaultAdminApp()).collection("applications").where("tenantId","==",c.value.tenantId).where(FieldPath.documentId(),"==",input.applicationId).limit(1).get();if(snapshot.empty){await audit(c.value.tenantId,input.auth,"application.detail","denied");return {ok:false as const,status:404,code:"RESOURCE_NOT_AVAILABLE"}}await audit(c.value.tenantId,input.auth,"application.detail","allowed");return {ok:true as const,status:200,schemaVersion:"application-detail-projection.v1",application:project(snapshot.docs[0].id,snapshot.docs[0].data(),DETAIL_FIELDS),assignees:await listAssignees(c.value.tenantId),requestId:input.auth.requestId,correlationId:input.auth.correlationId}}
