import "server-only";
import {createHash} from "node:crypto";
import {getFirestore} from "firebase-admin/firestore";
import {defaultAdminApp} from "../auth/firebaseAdminAuthAdapter";
import {analyzeApplication} from "../../ai/analyzeApplication";
import {APPROVED_DOCUMENT_PROCESSING_DEPENDENCIES} from "../documents/authorizedDocumentProcessingAdapter";
import {DOCUMENT_PROCESSING_POLICY,processAuthorizedDocumentBytes} from "../documents/authorizedDocumentProcessing";
import type {ApplicationEvidenceSetV1} from "../evidence/applicationEvidence";
import type {ApplicationAnalyzeResponse} from "./applicationAnalyzeRouteCore";
import {buildEnterpriseReview,evidenceDocs} from "./enterpriseEvidenceReview";
import {buildUnderwritingReport} from "../../ai/buildUnderwritingReport";
const db=()=>getFirestore(defaultAdminApp());
export async function listCanonicalApplicationDocuments(input:Readonly<{applicationId:string;tenantId:string}>){const snap=await db().collection("applicationDocuments").where("applicationId","==",input.applicationId).get();return Object.freeze(snap.docs.map(doc=>Object.freeze({documentId:doc.id})).sort((a,b)=>a.documentId.localeCompare(b.documentId)))}
export const processCanonicalAuthorizedBytes=(input:any)=>processAuthorizedDocumentBytes(input,DOCUMENT_PROCESSING_POLICY,APPROVED_DOCUMENT_PROCESSING_DEPENDENCIES);
export async function analyzeCanonicalEvidence(evidence:ApplicationEvidenceSetV1,analysisVersion:string){const analysis=await analyzeApplication(evidenceDocs(evidence),{applicationId:evidence.applicationId,analysisVersion});const enterpriseEvidence=buildEnterpriseReview(evidence,analysis);const report=buildUnderwritingReport({...analysis,enterpriseEvidence} as any,{borrower:analysis.normalized.borrower,loanNumber:analysis.normalized.loanNumber,loanAmount:analysis.normalized.loanAmount??undefined,propertyValue:analysis.normalized.propertyValue??undefined,income:analysis.normalized.income??undefined,debts:analysis.normalized.debts??undefined,assets:analysis.normalized.assets??undefined});return Object.freeze({...analysis,ai:analysis,report,enterpriseEvidence})}
export async function beginCanonicalAnalysis(input:any){const commandId=`analysis_${createHash("sha256").update(JSON.stringify([input.tenantId,input.applicationId,input.idempotencyKey])).digest("hex").slice(0,32)}`,ref=db().doc(`tenants/${input.tenantId}/applications/${input.applicationId}/analysisCommands/${input.idempotencyKey}`);return db().runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.exists){const data=snap.data()!;if(data.commandFingerprint!==input.commandFingerprint)return{status:"conflict" as const};if(data.status==="completed")return{status:"completed" as const,response:data.response as ApplicationAnalyzeResponse};return{status:"running" as const}}tx.create(ref,{schemaVersion:"application-analysis-command.v1",commandId,commandFingerprint:input.commandFingerprint,status:"running",requestId:input.requestId,correlationId:input.correlationId,startedAt:input.startedAt});return{status:"started" as const,commandId}})}
export async function completeCanonicalAnalysis(input:any){const commandRef=db().doc(`tenants/${input.tenantId}/applications/${input.applicationId}/analysisCommands/${input.idempotencyKey}`),stateRef=db().doc(`tenants/${input.tenantId}/applications/${input.applicationId}/analysisState/current`),auditRef=db().doc(`tenants/${input.tenantId}/applications/${input.applicationId}/analysisAuditEvents/${input.commandId}`);return db().runTransaction(async tx=>{const snap=await tx.get(commandRef);if(!snap.exists||snap.data()?.status!=="running"||snap.data()?.commandFingerprint!==input.commandFingerprint)throw Error("ANALYSIS_STALE");tx.set(stateRef,{schemaVersion:"application-analysis-state.v1",commandId:input.commandId,applicationAuthorizationVersion:input.applicationAuthorizationVersion,documentLineage:input.documentLineage,evidenceAggregationFingerprint:input.response.evidenceAggregationFingerprint,analysisVersion:input.response.analysisVersion,policyVersion:input.response.policyVersion,completedAt:input.completedAt},{merge:false});tx.create(auditRef,{schemaVersion:"application-analysis-audit.v1",commandId:input.commandId,requestId:input.response.requestId,correlationId:input.response.correlationId,evidenceAggregationFingerprint:input.response.evidenceAggregationFingerprint,analysisVersion:input.response.analysisVersion,policyVersion:input.response.policyVersion,documentCount:input.response.documentCount,completedAt:input.completedAt,piiPresent:false});tx.update(commandRef,{status:"completed",response:input.response,completedAt:input.completedAt});return input.response})}
