import { createHash } from "node:crypto";
import { AUTHORIZED_DOCUMENT_BYTES_V1, DOCUMENT_RETRIEVAL_POLICY_VERSION, type AuthorizedDocumentBytesV1 } from "./authorizedDocumentBytes";

export const AUTHORIZED_DOCUMENT_PROCESSING_V1="authorized-document-processing.v1" as const;
export const DOCUMENT_PROCESSING_POLICY_VERSION="document-processing-policy.v1" as const;
export const DOCUMENT_NORMALIZATION_VERSION="document-text-normalization.v1" as const;
export const DOCUMENT_PROCESSING_POLICY=Object.freeze({policyVersion:DOCUMENT_PROCESSING_POLICY_VERSION,maximumBytes:20*1024*1024,maximumPdfPages:50,maximumImagePixels:40_000_000,maximumTextLength:2_000_000,maximumPerPageTextLength:100_000,processingTimeoutMs:180_000,perStageTimeoutMs:150_000,maximumWarnings:100,maximumDiagnostics:100,maximumPageResults:50} as const);
export type ProcessingErrorCode="AUTHORIZED_BYTES_INVALID"|"DOCUMENT_HASH_MISMATCH"|"DOCUMENT_SIZE_MISMATCH"|"DOCUMENT_TYPE_UNSUPPORTED"|"DOCUMENT_ENCRYPTED"|"DOCUMENT_MALFORMED"|"DOCUMENT_PAGE_LIMIT_EXCEEDED"|"DOCUMENT_PIXEL_LIMIT_EXCEEDED"|"DOCUMENT_TEXT_LIMIT_EXCEEDED"|"OCR_UNAVAILABLE"|"OCR_FAILED"|"EXTRACTION_FAILED"|"PROCESSING_TIMEOUT"|"TEMP_FILE_FAILED"|"CLEANUP_FAILED"|"DEPENDENCY_FAILURE"|"INTERNAL_ERROR";
export type StageName="validated"|"type_detected"|"native_text_attempted"|"rasterization_attempted"|"ocr_attempted"|"normalized"|"completed"|"failed";
export type StageRecord=Readonly<{stage:StageName;status:"completed"|"skipped"|"failed";reason?:string}>;
export type RawPage=Readonly<{pageNumber:number;text:string;method:"native_text"|"ocr";confidence?:number;warnings?:readonly string[]}>;
export type ProcessingDependencies=Readonly<{engineId:string;engineVersion:string;extractPdf(bytes:Uint8Array,limits:typeof DOCUMENT_PROCESSING_POLICY,signal:AbortSignal):Promise<Readonly<{pageCount:number;encrypted?:boolean;pages:readonly RawPage[];requiresOcr:boolean}>>;ocrPdf?(bytes:Uint8Array,limits:typeof DOCUMENT_PROCESSING_POLICY,signal:AbortSignal):Promise<readonly RawPage[]>;ocrImage(bytes:Uint8Array,contentType:string,limits:typeof DOCUMENT_PROCESSING_POLICY,signal:AbortSignal):Promise<Readonly<{width:number;height:number;pages:readonly RawPage[]}>>;now?:()=>Date}>;
export type AuthorizedDocumentProcessingResultV1=Readonly<{schemaVersion:typeof AUTHORIZED_DOCUMENT_PROCESSING_V1;tenantId:string;applicationId:string;documentId:string;documentAuthorizationVersion:string;sourceContentHash:string;sourceSizeBytes:number;sourceContentType:string;processingStatus:"completed";processingStage:"completed";engine:Readonly<{id:string;version:string}>;processingPolicyVersion:typeof DOCUMENT_PROCESSING_POLICY_VERSION;normalizationVersion:typeof DOCUMENT_NORMALIZATION_VERSION;startedAt:string;completedAt:string;requestId:string;correlationId:string;pageCount:number;normalizedText:string;pages:readonly Readonly<{schemaVersion:typeof AUTHORIZED_DOCUMENT_PROCESSING_V1;documentId:string;pageNumber:number;method:"native_text"|"ocr";text:string;confidence?:number;warnings:readonly string[];sourceContentHash:string;processingFingerprint:string;assumption:false}>[];warnings:readonly string[];diagnostics:readonly string[];provenance:Readonly<{source:"authorized_document_bytes";retrievalPolicyVersion:typeof DOCUMENT_RETRIEVAL_POLICY_VERSION;authorizationVersion:string}>;stages:readonly StageRecord[];processingFingerprint:string}>;
export type ProcessingResult=Readonly<{ok:true;value:AuthorizedDocumentProcessingResultV1}|{ok:false;code:ProcessingErrorCode;stages:readonly StageRecord[]}>;
const fail=(code:ProcessingErrorCode,stages:StageRecord[]):ProcessingResult=>Object.freeze({ok:false,code,stages:Object.freeze([...stages,Object.freeze({stage:"failed",status:"failed",reason:code})])});
const valid=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
export const normalizeDocumentText=(s:string)=>s.normalize("NFKC").replace(/\r\n?/g,"\n").replace(/[\t\f\v ]+/g," ").replace(/ *\n */g,"\n").replace(/\n{3,}/g,"\n\n").trim();
const timeout=<T>(p:Promise<T>,ms:number,c:AbortController)=>new Promise<T>((resolve,reject)=>{const t=setTimeout(()=>{c.abort();reject(new Error("timeout"))},ms);p.then(v=>{clearTimeout(t);resolve(v)},e=>{clearTimeout(t);reject(e)})});
export async function processAuthorizedDocumentBytes(input:unknown,policy:unknown,deps:ProcessingDependencies):Promise<ProcessingResult>{
 const stages:StageRecord[]=[];const a=input as AuthorizedDocumentBytesV1;
 if(!a||a.schemaVersion!==AUTHORIZED_DOCUMENT_BYTES_V1||policy!==DOCUMENT_PROCESSING_POLICY||a.retrievalPolicyVersion!==DOCUMENT_RETRIEVAL_POLICY_VERSION||!(a.bytes instanceof Uint8Array)||!valid.test(a.tenantId)||!valid.test(a.applicationId)||!valid.test(a.documentId)||!valid.test(a.documentAuthorizationVersion)||!valid.test(a.requestId)||!valid.test(a.correlationId)||!/^([a-f0-9]{64})$/.test(a.sha256)||!Number.isSafeInteger(a.sizeBytes)||a.sizeBytes<=0)return fail("AUTHORIZED_BYTES_INVALID",stages);
 if(a.bytes.byteLength!==a.sizeBytes)return fail("DOCUMENT_SIZE_MISMATCH",stages);
 const owned=new Uint8Array(a.bytes);if(createHash("sha256").update(owned).digest("hex")!==a.sha256)return fail("DOCUMENT_HASH_MISMATCH",stages);
 if(a.sizeBytes>DOCUMENT_PROCESSING_POLICY.maximumBytes)return fail("AUTHORIZED_BYTES_INVALID",stages);stages.push(Object.freeze({stage:"validated",status:"completed"}));
 if(!["application/pdf","image/png","image/jpeg"].includes(a.contentType))return fail("DOCUMENT_TYPE_UNSUPPORTED",stages);stages.push(Object.freeze({stage:"type_detected",status:"completed"}));
 const fingerprint=createHash("sha256").update(JSON.stringify([a.tenantId,a.applicationId,a.documentId,a.documentAuthorizationVersion,a.sha256,a.contentType,DOCUMENT_PROCESSING_POLICY_VERSION,deps.engineId,deps.engineVersion,DOCUMENT_NORMALIZATION_VERSION])).digest("hex");
 const startedAt=(deps.now?.()||new Date()).toISOString();const controller=new AbortController();let raw:readonly RawPage[]=[];let pageCount=1;
 let activeStage:StageName|undefined;
 try{await timeout((async()=>{if(a.contentType==="application/pdf"){activeStage="native_text_attempted";const x=await deps.extractPdf(owned,DOCUMENT_PROCESSING_POLICY,controller.signal);if(x.encrypted)throw Object.assign(new Error(),{code:"DOCUMENT_ENCRYPTED"});if(!Number.isSafeInteger(x.pageCount)||x.pageCount<1)throw Object.assign(new Error(),{code:"DOCUMENT_MALFORMED"});if(x.pageCount>DOCUMENT_PROCESSING_POLICY.maximumPdfPages)throw Object.assign(new Error(),{code:"DOCUMENT_PAGE_LIMIT_EXCEEDED"});pageCount=x.pageCount;stages.push(Object.freeze({stage:"native_text_attempted",status:"completed"}));activeStage=undefined;if(x.requiresOcr){if(!deps.ocrPdf)throw Object.assign(new Error(),{code:"OCR_UNAVAILABLE"});activeStage="rasterization_attempted";raw=await deps.ocrPdf(owned,DOCUMENT_PROCESSING_POLICY,controller.signal);stages.push(Object.freeze({stage:"rasterization_attempted",status:"completed"}),Object.freeze({stage:"ocr_attempted",status:"completed"}));activeStage=undefined}else{raw=x.pages;stages.push(Object.freeze({stage:"rasterization_attempted",status:"skipped",reason:"native_text_available"}),Object.freeze({stage:"ocr_attempted",status:"skipped",reason:"native_text_available"}))}}else{stages.push(Object.freeze({stage:"native_text_attempted",status:"skipped",reason:"image_input"}),Object.freeze({stage:"rasterization_attempted",status:"skipped",reason:"image_input"}));activeStage="ocr_attempted";const x=await deps.ocrImage(owned,a.contentType,DOCUMENT_PROCESSING_POLICY,controller.signal);if(x.width*x.height>DOCUMENT_PROCESSING_POLICY.maximumImagePixels)throw Object.assign(new Error(),{code:"DOCUMENT_PIXEL_LIMIT_EXCEEDED"});raw=x.pages;stages.push(Object.freeze({stage:"ocr_attempted",status:"completed"}));activeStage=undefined}})(),DOCUMENT_PROCESSING_POLICY.processingTimeoutMs,controller)}catch(e:any){const code=(e?.message==="timeout"?"PROCESSING_TIMEOUT":e?.code||"DEPENDENCY_FAILURE") as ProcessingErrorCode;if(activeStage)stages.push(Object.freeze({stage:activeStage,status:"failed",reason:code}));return fail(code,stages)}
 if(raw.length>DOCUMENT_PROCESSING_POLICY.maximumPageResults)return fail("DOCUMENT_PAGE_LIMIT_EXCEEDED",stages);const sorted=[...raw].sort((x,y)=>x.pageNumber-y.pageNumber);if(sorted.some((p,i)=>p.pageNumber!==i+1))return fail("EXTRACTION_FAILED",stages);
 const pages=[] as any[];let total=0;const warnings:string[]=[];for(const p of sorted){const text=normalizeDocumentText(p.text);if(text.length>DOCUMENT_PROCESSING_POLICY.maximumPerPageTextLength)return fail("DOCUMENT_TEXT_LIMIT_EXCEEDED",stages);total+=text.length;if(total>DOCUMENT_PROCESSING_POLICY.maximumTextLength)return fail("DOCUMENT_TEXT_LIMIT_EXCEEDED",stages);const w=[...(p.warnings||[])].slice(0,DOCUMENT_PROCESSING_POLICY.maximumWarnings);warnings.push(...w);pages.push(Object.freeze({schemaVersion:AUTHORIZED_DOCUMENT_PROCESSING_V1,documentId:a.documentId,pageNumber:p.pageNumber,method:p.method,text,...(p.confidence!==undefined?{confidence:p.confidence}:{}),warnings:Object.freeze(w),sourceContentHash:a.sha256,processingFingerprint:fingerprint,assumption:false}))}stages.push(Object.freeze({stage:"normalized",status:"completed"}),Object.freeze({stage:"completed",status:"completed"}));
 const value:any={schemaVersion:AUTHORIZED_DOCUMENT_PROCESSING_V1,tenantId:a.tenantId,applicationId:a.applicationId,documentId:a.documentId,documentAuthorizationVersion:a.documentAuthorizationVersion,sourceContentHash:a.sha256,sourceSizeBytes:a.sizeBytes,sourceContentType:a.contentType,processingStatus:"completed",processingStage:"completed",engine:Object.freeze({id:deps.engineId,version:deps.engineVersion}),processingPolicyVersion:DOCUMENT_PROCESSING_POLICY_VERSION,normalizationVersion:DOCUMENT_NORMALIZATION_VERSION,startedAt,completedAt:(deps.now?.()||new Date()).toISOString(),requestId:a.requestId,correlationId:a.correlationId,pageCount,normalizedText:pages.map(p=>p.text).join("\n\n"),pages:Object.freeze(pages),warnings:Object.freeze(warnings.slice(0,DOCUMENT_PROCESSING_POLICY.maximumWarnings)),diagnostics:Object.freeze([]),provenance:Object.freeze({source:"authorized_document_bytes",retrievalPolicyVersion:a.retrievalPolicyVersion,authorizationVersion:a.documentAuthorizationVersion}),stages:Object.freeze(stages),processingFingerprint:fingerprint};return Object.freeze({ok:true,value:Object.freeze(value)});
}
