import { validateIsoTimestamp, validateTenantId, type IsoTimestamp, type SchemaVersion, type TenantId } from "./primitives";
import { validateCorrelationId, validateRequestId, type CorrelationId, type RequestId, type ServerPrincipalKind } from "./serverAuth";
import { AUTHORIZATION_CONSTRAINTS, AUTHORIZATION_DENIAL_REASONS, AUTHORIZATION_PERMISSIONS, AUTHORIZATION_RESOURCE_TYPES, type AuthorizationDecisionV1, type AuthorizationDenialReason, type AuthorizationPermission, type AuthorizationResourceType, type ConstraintEvaluation } from "./authorization";

export const AUTHORIZATION_AUDIT_EVENT_V1 = "authorization-audit-event.v1" as SchemaVersion;
export const AUTHORIZATION_CACHE_KEY_V1 = "authorization-cache-key.v1" as SchemaVersion;
export const AUTHORIZATION_AUDIT_PRODUCER = "velocity-authorization-decision.v1";
export const AUTHORIZATION_AUDIT_CLASSIFICATIONS = ["access_allowed", "access_denied", "permission_denied", "tenant_denied", "resource_denied", "policy_failure", "security_event"] as const;
export type AuthorizationAuditClassification = typeof AUTHORIZATION_AUDIT_CLASSIFICATIONS[number];

export type AuthorizationAuditEventV1 = Readonly<{
  schemaVersion: typeof AUTHORIZATION_AUDIT_EVENT_V1; eventId: string; requestId: RequestId; correlationId: CorrelationId; evaluatedAt: IsoTimestamp;
  principalKind: ServerPrincipalKind; principalReference: string; tenantId?: TenantId; membershipVersion?: string; tenantVersion?: string;
  serviceGrantVersion?: string; policyVersion: string; permissionVersion: string; permission: AuthorizationPermission;
  resourceType: AuthorizationResourceType; resourceId?: string; resourceAuthorizationVersion?: string; decision: "allow" | "deny";
  denialReason?: AuthorizationDenialReason; constraintsEvaluated: readonly ConstraintEvaluation[]; producer: typeof AUTHORIZATION_AUDIT_PRODUCER;
  classification: AuthorizationAuditClassification;
}>;

export type AuthorizationCacheKeyV1 = Readonly<{
  schemaVersion: typeof AUTHORIZATION_CACHE_KEY_V1; key: string; tenantId: TenantId; principalReference: string; permission: AuthorizationPermission;
  resourceType: AuthorizationResourceType; membershipVersion?: string; tenantVersion: string; permissionVersion: string; policyVersion: string;
  serviceGrantVersion?: string; resourceAuthorizationVersion?: string;
}>;
export type AuthorizationVersionDomainsV1 = Readonly<{ tenantVersion: string; membershipVersion?: string; permissionVersion: string; policyVersion: string; serviceGrantVersion?: string; resourceAuthorizationVersion?: string }>;
export type AuthorizationAuditContractResult<T> = Readonly<{ ok: true; value: T }> | Readonly<{ ok: false; code: "invalid_authorization_audit_contract" }>;
const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/; const fail = <T>(): AuthorizationAuditContractResult<T> => Object.freeze({ ok: false, code: "invalid_authorization_audit_contract" });
const AUDIT_KEYS = new Set(["schemaVersion", "eventId", "requestId", "correlationId", "evaluatedAt", "principalKind", "principalReference", "tenantId", "membershipVersion", "tenantVersion", "serviceGrantVersion", "policyVersion", "permissionVersion", "permission", "resourceType", "resourceId", "resourceAuthorizationVersion", "decision", "denialReason", "constraintsEvaluated", "producer", "classification"]);
const safeOptional = (value: unknown) => value === undefined || (typeof value === "string" && SAFE_ID.test(value));

export function parseAuthorizationAuditEvent(input: unknown): AuthorizationAuditContractResult<AuthorizationAuditEventV1> {
  if (!input || typeof input !== "object" || Array.isArray(input)) return fail(); const raw = input as Record<string, any>;
  if (Object.keys(raw).some((key) => !AUDIT_KEYS.has(key))) return fail();
  const requestId = validateRequestId(raw.requestId), correlationId = validateCorrelationId(raw.correlationId), evaluatedAt = validateIsoTimestamp(raw.evaluatedAt), tenantId = raw.tenantId === undefined ? undefined : validateTenantId(raw.tenantId); const constraints = raw.constraintsEvaluated;
  if (raw.schemaVersion !== AUTHORIZATION_AUDIT_EVENT_V1 || !SAFE_ID.test(raw.eventId || "") || !requestId.ok || !correlationId.ok || !evaluatedAt.ok || !["firebase_user", "service", "cron", "external_webhook"].includes(raw.principalKind) || !SAFE_ID.test(raw.principalReference || "") || (tenantId && !tenantId.ok) || !safeOptional(raw.membershipVersion) || !safeOptional(raw.tenantVersion) || !safeOptional(raw.serviceGrantVersion) || !SAFE_ID.test(raw.policyVersion || "") || !SAFE_ID.test(raw.permissionVersion || "") || !AUTHORIZATION_PERMISSIONS.includes(raw.permission) || !AUTHORIZATION_RESOURCE_TYPES.includes(raw.resourceType) || !safeOptional(raw.resourceId) || !safeOptional(raw.resourceAuthorizationVersion) || !["allow", "deny"].includes(raw.decision) || (raw.decision === "allow" ? raw.denialReason !== undefined : !AUTHORIZATION_DENIAL_REASONS.includes(raw.denialReason)) || !Array.isArray(constraints) || constraints.some((item: any) => !item || !AUTHORIZATION_CONSTRAINTS.includes(item.constraint) || !["pass", "fail", "not_applicable"].includes(item.result)) || raw.producer !== AUTHORIZATION_AUDIT_PRODUCER || !AUTHORIZATION_AUDIT_CLASSIFICATIONS.includes(raw.classification)) return fail();
  const frozenConstraints = Object.freeze(constraints.map((item: ConstraintEvaluation) => Object.freeze({ ...item })));
  return Object.freeze({ ok: true, value: Object.freeze({ schemaVersion: AUTHORIZATION_AUDIT_EVENT_V1, eventId: raw.eventId, requestId: requestId.value, correlationId: correlationId.value, evaluatedAt: evaluatedAt.value, principalKind: raw.principalKind, principalReference: raw.principalReference, ...(tenantId?.ok ? { tenantId: tenantId.value } : {}), ...(raw.membershipVersion ? { membershipVersion: raw.membershipVersion } : {}), ...(raw.tenantVersion ? { tenantVersion: raw.tenantVersion } : {}), ...(raw.serviceGrantVersion ? { serviceGrantVersion: raw.serviceGrantVersion } : {}), policyVersion: raw.policyVersion, permissionVersion: raw.permissionVersion, permission: raw.permission, resourceType: raw.resourceType, ...(raw.resourceId ? { resourceId: raw.resourceId } : {}), ...(raw.resourceAuthorizationVersion ? { resourceAuthorizationVersion: raw.resourceAuthorizationVersion } : {}), decision: raw.decision, ...(raw.denialReason ? { denialReason: raw.denialReason } : {}), constraintsEvaluated: frozenConstraints, producer: AUTHORIZATION_AUDIT_PRODUCER, classification: raw.classification }) });
}

export function createAuthorizationAuditEvent(input: Readonly<{ eventId: string; principalReference: string; decision: AuthorizationDecisionV1; membershipVersion?: string; tenantVersion?: string; serviceGrantVersion?: string; permissionVersion: string; resourceAuthorizationVersion?: string; classification: AuthorizationAuditClassification }>): AuthorizationAuditContractResult<AuthorizationAuditEventV1> {
  return parseAuthorizationAuditEvent({ schemaVersion: AUTHORIZATION_AUDIT_EVENT_V1, eventId: input.eventId, requestId: input.decision.requestId, correlationId: input.decision.correlationId, evaluatedAt: input.decision.evaluatedAt, principalKind: input.decision.principalKind, principalReference: input.principalReference, ...(input.decision.tenantId ? { tenantId: input.decision.tenantId } : {}), ...(input.membershipVersion ? { membershipVersion: input.membershipVersion } : {}), ...(input.tenantVersion ? { tenantVersion: input.tenantVersion } : {}), ...(input.serviceGrantVersion ? { serviceGrantVersion: input.serviceGrantVersion } : {}), policyVersion: input.decision.policyVersion, permissionVersion: input.permissionVersion, permission: input.decision.permission, resourceType: input.decision.resourceType, ...(input.decision.resourceId ? { resourceId: input.decision.resourceId } : {}), ...(input.resourceAuthorizationVersion ? { resourceAuthorizationVersion: input.resourceAuthorizationVersion } : {}), decision: input.decision.decision, ...(input.decision.decision === "deny" ? { denialReason: input.decision.reasonCode } : {}), constraintsEvaluated: input.decision.constraintsEvaluated, producer: AUTHORIZATION_AUDIT_PRODUCER, classification: input.classification });
}

export function createAuthorizationCacheKey(input: Omit<AuthorizationCacheKeyV1, "schemaVersion" | "key">): AuthorizationAuditContractResult<AuthorizationCacheKeyV1> {
  const tenantId = validateTenantId(input.tenantId); if (!tenantId.ok || !SAFE_ID.test(input.principalReference) || !AUTHORIZATION_PERMISSIONS.includes(input.permission) || !AUTHORIZATION_RESOURCE_TYPES.includes(input.resourceType) || !safeOptional(input.membershipVersion) || !SAFE_ID.test(input.tenantVersion) || !SAFE_ID.test(input.permissionVersion) || !SAFE_ID.test(input.policyVersion) || !safeOptional(input.serviceGrantVersion) || !safeOptional(input.resourceAuthorizationVersion)) return fail();
  const parts = [tenantId.value, input.principalReference, input.permission, input.resourceType, input.membershipVersion || "none", input.tenantVersion, input.permissionVersion, input.policyVersion, input.serviceGrantVersion || "none", input.resourceAuthorizationVersion || "none"];
  return Object.freeze({ ok: true, value: Object.freeze({ schemaVersion: AUTHORIZATION_CACHE_KEY_V1, key: parts.map(encodeURIComponent).join("|"), tenantId: tenantId.value, principalReference: input.principalReference, permission: input.permission, resourceType: input.resourceType, ...(input.membershipVersion ? { membershipVersion: input.membershipVersion } : {}), tenantVersion: input.tenantVersion, permissionVersion: input.permissionVersion, policyVersion: input.policyVersion, ...(input.serviceGrantVersion ? { serviceGrantVersion: input.serviceGrantVersion } : {}), ...(input.resourceAuthorizationVersion ? { resourceAuthorizationVersion: input.resourceAuthorizationVersion } : {}) }) });
}
