import { AUTHORIZATION_AUDIT_EVENT_V1, AUTHORIZATION_AUDIT_PRODUCER } from "./authorizationAudit";
import { AUTHORIZATION_DECISION_V1, AUTHORIZATION_PERMISSION_VERSION, AUTHORIZATION_POLICY_VERSION } from "./authorization";

const freeze = <T>(value: T): Readonly<T> => Object.freeze(value); const now = "2026-07-11T20:00:00.000Z";
const decision = (effect: "allow" | "deny", reasonCode: string, permission = "application.read", tenantId = "tenant_alpha") => freeze({ schemaVersion: AUTHORIZATION_DECISION_V1, decision: effect, permission, principalKind: "firebase_user", tenantId, resourceType: "application", resourceId: "application_alpha", reasonCode, policyVersion: AUTHORIZATION_POLICY_VERSION, evaluatedAt: now, requestId: "req_audit_fixture", correlationId: "corr_audit_fixture", constraintsEvaluated: freeze([freeze({ constraint: "resource_tenant_match", result: effect === "allow" ? "pass" : "fail" })]), audit: freeze({ action: "application.read", outcome: effect === "allow" ? "allowed" : "denied", piiPresent: false }) });
const event = (effect: "allow" | "deny", reasonCode: string, classification: string, permission = "application.read") => freeze({ schemaVersion: AUTHORIZATION_AUDIT_EVENT_V1, eventId: `event_${classification}`, requestId: "req_audit_fixture", correlationId: "corr_audit_fixture", evaluatedAt: now, principalKind: "firebase_user", principalReference: "user_fixture", tenantId: "tenant_alpha", membershipVersion: "membership.v1", tenantVersion: "tenant.v1", policyVersion: AUTHORIZATION_POLICY_VERSION, permissionVersion: AUTHORIZATION_PERMISSION_VERSION, permission, resourceType: "application", resourceId: "application_alpha", resourceAuthorizationVersion: "application.v1", decision: effect, ...(effect === "deny" ? { denialReason: reasonCode } : {}), constraintsEvaluated: freeze([freeze({ constraint: "resource_tenant_match", result: effect === "allow" ? "pass" : "fail" })]), producer: AUTHORIZATION_AUDIT_PRODUCER, classification });

export const authorizationAuditFixtures = freeze({
  decisions: freeze({ allowed: decision("allow", "authorized"), denied: decision("deny", "permission_missing"), crossTenant: decision("deny", "resource_tenant_mismatch"), unknownRole: decision("deny", "role_unknown"), policyFailure: decision("deny", "policy_invalid") }),
  events: freeze({ allowed: event("allow", "authorized", "access_allowed"), denied: event("deny", "permission_missing", "permission_denied"), crossTenant: event("deny", "resource_tenant_mismatch", "resource_denied"), unknownRole: event("deny", "role_unknown", "security_event"), policyFailure: event("deny", "policy_invalid", "policy_failure") }),
  cacheInput: freeze({ tenantId: "tenant_alpha", principalReference: "user_fixture", permission: "application.read", resourceType: "application", membershipVersion: "membership.v1", tenantVersion: "tenant.v1", permissionVersion: AUTHORIZATION_PERMISSION_VERSION, policyVersion: AUTHORIZATION_POLICY_VERSION, resourceAuthorizationVersion: "application.v1" }),
  malformedEvent: freeze({ ...event("allow", "authorized", "access_allowed"), borrowerName: "Synthetic Borrower" }),
});
