import { AUTHORIZATION_CONTEXT_V1, AUTHORIZATION_PERMISSION_VERSION, AUTHORIZATION_POLICY_VERSION, AUTHORIZATION_REQUEST_V1, RESOLVED_RESOURCE_FACTS_V1 } from "./authorization";

const freeze = <T>(value: T): Readonly<T> => Object.freeze(value);
const now = "2026-07-11T20:00:00.000Z";
const authentication = (principalId: string, principalKind: "firebase_user" | "service" = "firebase_user") => freeze({ principalKind, principalId, requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture" });
const human = (role: string, membershipStatus = "active", tenantStatus = "active", extra: Record<string, unknown> = {}) => freeze({ schemaVersion: AUTHORIZATION_CONTEXT_V1, authentication: authentication(`${role}_user`), tenantId: "tenant_alpha", membershipId: `membership_${role}`, membershipStatus, role, permissionVersion: AUTHORIZATION_PERMISSION_VERSION, tenantStatus, branchIds: freeze(["branch_alpha"]), teamIds: freeze(["team_alpha"]), authorizationSource: "tenant_membership", evaluatedAt: now, membershipUpdatedAt: now, tenantUpdatedAt: now, membershipVersion: "membership.v1", tenantVersion: "tenant.v1", audit: freeze({ action: "tenant_authorization.resolve", outcome: "resolved", piiPresent: false }), ...extra });
const resource = (tenantId: string | undefined, ownershipState: "tenant_owned" | "unresolved_legacy", extra: Record<string, unknown> = {}) => freeze({ ...(tenantId ? { tenantId } : {}), ownershipState, ...extra });

export const authorizationFixtures = freeze({
  contexts: freeze({
    activeOwner: human("owner"), activeAdmin: human("admin"), activeUnderwriter: human("underwriter"), activeProcessor: human("processor"),
    activeLoanOfficer: human("loan_officer"), activeViewer: human("viewer"), unknownRole: human("unknown"), invitedMembership: human("viewer", "invited"),
    suspendedMembership: human("viewer", "suspended"), disabledMembership: human("viewer", "disabled"), suspendedTenant: human("owner", "active", "suspended"),
    missingTenant: freeze({ ...human("owner"), tenantId: undefined }),
    validServiceGrant: freeze({ schemaVersion: AUTHORIZATION_CONTEXT_V1, authentication: authentication("files_service", "service"), tenantId: "tenant_alpha", serviceGrantId: "grant_files_alpha", servicePermissions: freeze(["service.files.process"]), permittedTenantIds: freeze(["tenant_alpha"]), permissionVersion: AUTHORIZATION_PERMISSION_VERSION, tenantStatus: "active", authorizationSource: "service_grant", evaluatedAt: now, grantVersion: "grant.v1", tenantUpdatedAt: now }),
    invalidServiceScope: freeze({ schemaVersion: AUTHORIZATION_CONTEXT_V1, authentication: authentication("files_service", "service"), tenantId: "tenant_alpha", serviceGrantId: "grant_files_beta", servicePermissions: freeze(["service.files.process"]), permittedTenantIds: freeze(["tenant_beta"]), permissionVersion: AUTHORIZATION_PERMISSION_VERSION, tenantStatus: "active", authorizationSource: "service_grant", evaluatedAt: now, grantVersion: "grant.v1", tenantUpdatedAt: now }),
  }),
  resources: freeze({
    sameTenantApplication: resource("tenant_alpha", "tenant_owned", { branchId: "branch_alpha", teamId: "team_alpha", assignedUserId: "underwriter_user", creatorId: "processor_user" }),
    crossTenantApplication: resource("tenant_beta", "tenant_owned"), unresolvedLegacyApplication: resource(undefined, "unresolved_legacy"),
    matchingBranch: resource("tenant_alpha", "tenant_owned", { branchId: "branch_alpha" }), mismatchedBranch: resource("tenant_alpha", "tenant_owned", { branchId: "branch_beta" }),
    assignedUser: resource("tenant_alpha", "tenant_owned", { assignedUserId: "underwriter_user" }), unassignedUser: resource("tenant_alpha", "tenant_owned"),
  }),
  policies: freeze({
    applicationRead: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, permission: "application.read", resourceType: "application", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "unresolved_legacy_denied"]), auditAction: "application.read" }),
    applicationUpdate: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, permission: "application.update", resourceType: "application", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "unresolved_legacy_denied"]), auditAction: "application.update" }),
    decisionApprove: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, permission: "decision.approve", resourceType: "decision", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "assigned_to_user", "unresolved_legacy_denied"]), auditAction: "decision.approve" }),
    decisionDeny: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, permission: "decision.deny", resourceType: "decision", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "assigned_to_user", "unresolved_legacy_denied"]), auditAction: "decision.deny" }),
    branchRead: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, permission: "application.read", resourceType: "application", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "branch_match"]), auditAction: "application.branch_read" }),
    serviceFiles: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, permission: "service.files.process", resourceType: "service_job", requiredConstraints: freeze(["active_tenant", "service_scope_match"]), auditAction: "service.files.process" }),
    malformedPolicy: freeze({ policyVersion: "wrong", permission: "*", resourceType: "application", requiredConstraints: freeze([]), auditAction: "bad policy" }), missingPolicy: undefined, missingPermission: freeze({ policyVersion: AUTHORIZATION_POLICY_VERSION, resourceType: "application", requiredConstraints: freeze([]), auditAction: "application.missing" }),
  }),
  requests: freeze({
    applicationRead: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "application.read", resourceType: "application", resourceId: "application_alpha", action: freeze({ auditAction: "application.read", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "unresolved_legacy_denied"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    applicationUpdate: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "application.update", resourceType: "application", resourceId: "application_alpha", action: freeze({ auditAction: "application.update", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    approval: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "decision.approve", resourceType: "decision", resourceId: "decision_alpha", action: freeze({ auditAction: "decision.approve", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "assigned_to_user", "unresolved_legacy_denied"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    override: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "decision.override", resourceType: "decision", resourceId: "decision_alpha", action: freeze({ auditAction: "decision.override", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    branchRead: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "application.read", resourceType: "application", resourceId: "application_alpha", action: freeze({ auditAction: "application.branch_read", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "branch_match"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    teamRead: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "application.read", resourceType: "application", resourceId: "application_alpha", action: freeze({ auditAction: "application.team_read", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "team_match"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    creatorUpdate: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "application.update", resourceType: "application", resourceId: "application_alpha", action: freeze({ auditAction: "application.creator_update", requiredConstraints: freeze(["active_tenant", "active_membership", "resource_tenant_match", "creator_match"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    serviceFiles: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "service.files.process", resourceType: "service_job", resourceId: "job_alpha", action: freeze({ auditAction: "service.files.process", requiredConstraints: freeze(["active_tenant", "service_scope_match"]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: AUTHORIZATION_POLICY_VERSION }),
    invalidPolicy: freeze({ schemaVersion: AUTHORIZATION_REQUEST_V1, permission: "application.read", resourceType: "application", resourceId: "application_alpha", action: freeze({ auditAction: "application.read", requiredConstraints: freeze([]) }), requestId: "req_authorization_fixture", correlationId: "corr_authorization_fixture", policyVersion: "authorization-policy.invalid" }),
  }),
  resolvedFacts: freeze({
    sameTenantApplication: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_alpha", branchId: "branch_alpha", teamIds: freeze(["team_alpha"]), assignedUserIds: freeze(["underwriter_user"]), assignedTeamIds: freeze(["team_alpha"]), creatorId: "processor_user", legacyState: "tenant_owned", resourceStatus: "active" }),
    crossTenantApplication: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_beta", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), legacyState: "tenant_owned", resourceStatus: "active" }),
    mismatchedBranch: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_alpha", branchId: "branch_beta", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), legacyState: "tenant_owned", resourceStatus: "active" }),
    mismatchedTeam: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_alpha", teamIds: freeze(["team_beta"]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), legacyState: "tenant_owned", resourceStatus: "active" }),
    unassignedDecision: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "decision", resourceId: "decision_alpha", tenantId: "tenant_alpha", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), legacyState: "tenant_owned", resourceStatus: "pending" }),
    assignedDecision: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "decision", resourceId: "decision_alpha", tenantId: "tenant_alpha", teamIds: freeze(["team_alpha"]), assignedUserIds: freeze(["underwriter_user"]), assignedTeamIds: freeze(["team_alpha"]), legacyState: "tenant_owned", resourceStatus: "pending" }),
    creatorMatch: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_alpha", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), creatorId: "processor_user", legacyState: "tenant_owned", resourceStatus: "active" }),
    creatorMismatch: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_alpha", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), creatorId: "other_user", legacyState: "tenant_owned", resourceStatus: "active" }),
    unresolvedLegacy: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "application_alpha", tenantId: "tenant_alpha", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), legacyState: "unresolved_legacy", resourceStatus: "legacy" }),
    serviceJob: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "service_job", resourceId: "job_alpha", tenantId: "tenant_alpha", teamIds: freeze([]), assignedUserIds: freeze([]), assignedTeamIds: freeze([]), legacyState: "not_applicable", resourceStatus: "queued" }),
    malformed: freeze({ schemaVersion: RESOLVED_RESOURCE_FACTS_V1, resourceType: "application", resourceId: "borrower@example.com", tenantId: "tenant_alpha", legacyState: "forged" }),
  }),
  evaluatedAt: now,
});
