import { createHash } from "node:crypto";

export const LEGACY_OWNERSHIP_POLICY_VERSION = "legacy-ownership-policy.provisional.v1" as const;
export const LEGACY_OWNERSHIP_COLLECTOR_VERSION = "legacy-ownership-collector.v1" as const;
export const LEGACY_OWNERSHIP_STATES = ["tenant_owned","ownership_unresolved","ownership_evidence_available","ownership_disputed","adjudication_pending","adjudication_approved","adjudication_rejected","archived_unresolved"] as const;
export type LegacyOwnershipState = typeof LEGACY_OWNERSHIP_STATES[number];
export const LEGACY_OWNERSHIP_EVIDENCE_CLASSES = ["canonical_parent_tenant","application_create_receipt","authorization_audit_lineage","canonical_principal_membership","canonical_application_document_relationship","canonical_storage_metadata","trusted_migration_manifest","signed_customer_manifest","governed_platform_adjudication"] as const;
export type LegacyOwnershipEvidenceClass = typeof LEGACY_OWNERSHIP_EVIDENCE_CLASSES[number];
export type LegacyResourceType = "application"|"application_document"|"legacy_document_metadata"|"storage_object"|"analysis"|"report"|"workflow"|"decision"|"evidence"|"audit_or_receipt";
export type LegacyOwnershipEvidenceV1 = Readonly<{schemaVersion:"legacy-ownership-evidence.v1";evidenceId:string;resourceType:LegacyResourceType;resourceId:string;candidateTenantId:string;evidenceClass:LegacyOwnershipEvidenceClass;evidenceSourceReference:string;sourceVersion:string;observedAt:string;collectorVersion:typeof LEGACY_OWNERSHIP_COLLECTOR_VERSION;safeWarnings:readonly string[];integrityFingerprint:string}>;
export type LegacyInventoryCandidateV1 = Readonly<{resourceType:LegacyResourceType;resourceId:string;applicationId?:string;documentId?:string;tenantId?:string;ownershipState?:string;authorizationVersion?:string;workflowVersion?:string;parentTenantId?:string;storageMetadataTenantId?:string;lineageTenantIds?:readonly string[];evidence?:readonly LegacyOwnershipEvidenceV1[];sourcePattern:string;orphaned?:boolean;malformed?:boolean}>;
export const LEGACY_OWNERSHIP_POLICY = Object.freeze({schemaVersion:LEGACY_OWNERSHIP_POLICY_VERSION,label:"provisional_product_review_required",requiredEvidenceClasses:Object.freeze(["canonical_parent_tenant","application_create_receipt"]),minimumIndependentEvidence:2,conflicts:"any_distinct_candidate_tenant_disputes",freshness:"exact_source_version_or_hash_required",permittedAdjudicators:Object.freeze(["governed_platform_human","named_migration_service"]),requiredScopes:Object.freeze(["platform.legacy_ownership.adjudicate"]),justificationCodes:Object.freeze(["signed_manifest_verified","canonical_lineage_verified","customer_attestation_verified"]),automaticMigrationProhibited:true,childConsistencyRequired:true,storageMigrationSeparateApproval:true,auditAndReceiptRequired:true,rollbackRequiredForMutation:true,executableAuthorityAvailable:false});
export const LEGACY_OWNERSHIP_SCOPES = Object.freeze(["platform.legacy_ownership.inventory","platform.legacy_ownership.adjudicate","platform.legacy_ownership.rollback"]);
export function stableLegacyFingerprint(value:unknown){return createHash("sha256").update(JSON.stringify(value,Object.keys(value as any).sort())).digest("hex")}
export function createLegacyOwnershipEvidence(input:Omit<LegacyOwnershipEvidenceV1,"schemaVersion"|"collectorVersion"|"integrityFingerprint">):LegacyOwnershipEvidenceV1{const base={schemaVersion:"legacy-ownership-evidence.v1" as const,...input,collectorVersion:LEGACY_OWNERSHIP_COLLECTOR_VERSION,safeWarnings:Object.freeze([...input.safeWarnings])};return Object.freeze({...base,integrityFingerprint:stableLegacyFingerprint(base)})}

