export const WORKER_SERVICE_PRINCIPAL_V1 = "worker-service-principal.v1";
export const WORKER_SERVICE_GRANT_V1 = "worker-service-grant.v1";
export const WORKER_SERVICE_AUTH_VERSION = "worker-service-hmac.v1";
export const WORKER_SERVICE_POLICY_VERSION = "worker-service-policy.v1";
export const WORKER_SERVICE_SCOPES = ["worker.files.claim", "worker.files.read_document", "worker.files.process", "worker.files.write_result", "worker.ai.claim", "worker.ai.read_application", "worker.ai.execute", "worker.ai.write_result"] as const;
export type WorkerServiceScope = typeof WORKER_SERVICE_SCOPES[number];
export type WorkerServiceKind = "files_worker" | "ai_worker";
export type WorkerServicePrincipalV1 = Readonly<{ schemaVersion: typeof WORKER_SERVICE_PRINCIPAL_V1; servicePrincipalId: string; serviceKind: WorkerServiceKind; authenticationMethod: "hmac_sha256"; authenticationVersion: typeof WORKER_SERVICE_AUTH_VERSION; credentialVersion: string; environment: string; verifiedAt: string; requestId: string; correlationId: string; producerVersion: typeof WORKER_SERVICE_POLICY_VERSION; authentication: Readonly<{ humanRolePresent: false; firebaseUserPresent: false; credentialPersisted: false }> }>;
export type WorkerServiceGrantV1 = Readonly<{ schemaVersion: typeof WORKER_SERVICE_GRANT_V1; grantId: string; servicePrincipalId: string; serviceKind: WorkerServiceKind; status: "active"; credentialVersion: string; grantVersion: string; environment: string; scopes: readonly WorkerServiceScope[]; tenantIds: readonly string[]; policyVersion: typeof WORKER_SERVICE_POLICY_VERSION; expiresAt?: string; revokedAt?: never; provenance: "firestore_authoritative" }>;
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/, ENV = /^(production|development|test|demo)$/;
const freeze = <T extends object>(value: T): Readonly<T> => Object.freeze(value);
export function parseWorkerServiceGrant(input: unknown, expected: Readonly<{ principalId: string; kind: WorkerServiceKind; credentialVersion: string; environment: string; now: string }>): WorkerServiceGrantV1 | undefined { if (!input || typeof input !== "object" || Array.isArray(input)) return; const r = input as any; if (r.schemaVersion !== WORKER_SERVICE_GRANT_V1 || !ID.test(r.grantId || "") || r.servicePrincipalId !== expected.principalId || r.serviceKind !== expected.kind || r.status !== "active" || r.credentialVersion !== expected.credentialVersion || !ID.test(r.grantVersion || "") || r.environment !== expected.environment || r.policyVersion !== WORKER_SERVICE_POLICY_VERSION || r.revokedAt !== undefined || !Array.isArray(r.scopes) || !r.scopes.length || new Set(r.scopes).size !== r.scopes.length || r.scopes.some((x: unknown) => !WORKER_SERVICE_SCOPES.includes(x as any)) || !Array.isArray(r.tenantIds) || !r.tenantIds.length || r.tenantIds.length > 10 || new Set(r.tenantIds).size !== r.tenantIds.length || r.tenantIds.some((x: unknown) => !ID.test(String(x))) || !ENV.test(r.environment) || (r.expiresAt !== undefined && (!Number.isFinite(Date.parse(r.expiresAt)) || Date.parse(r.expiresAt) <= Date.parse(expected.now)))) return; return freeze({ schemaVersion: WORKER_SERVICE_GRANT_V1, grantId: r.grantId, servicePrincipalId: r.servicePrincipalId, serviceKind: r.serviceKind, status: "active", credentialVersion: r.credentialVersion, grantVersion: r.grantVersion, environment: r.environment, scopes: freeze([...r.scopes]) as readonly WorkerServiceScope[], tenantIds: freeze([...r.tenantIds]) as readonly string[], policyVersion: WORKER_SERVICE_POLICY_VERSION, ...(r.expiresAt ? { expiresAt: r.expiresAt } : {}), provenance: "firestore_authoritative" }); }
