import {deriveEnterpriseWorkflow} from "../workflow/enterprisePipeline";

export const UNDERWRITER_WORKSPACE_VERSION="enterprise-underwriter-workspace.v1" as const;
export type AgendaItem=Readonly<{id:string;type:"integrity"|"finding"|"condition"|"change"|"evidence";severity:string;disposition:string;title:string;explanation:string;blocking:boolean;reviewRequired:boolean;borrowerId:string|null;findingId:string|null;conditionId:string|null;documentReferences:readonly Readonly<{documentId:string;pageNumber:number|null}>[];recommendedAction:string;rank:number;linked:boolean}>;
const clean=(v:any)=>typeof v==="string"?v.slice(0,1000):"";
const refs=(v:any):readonly Readonly<{documentId:string;pageNumber:number|null}>[]=>Object.freeze((Array.isArray(v)?v:[]).map((x:any)=>({documentId:clean(x.documentId),pageNumber:Number.isInteger(x.pageNumber)?x.pageNumber:null})).filter(x=>x.documentId));
const severityRank=(v:string)=>v==="critical"?0:v==="high"?1:v==="medium"||v==="med"?2:v==="low"?3:4;

export function buildReviewAgenda(input:{validationFailures?:readonly string[];findings?:readonly any[];conditions?:readonly any[];changes?:readonly any[]}):readonly AgendaItem[]{
 const items:AgendaItem[]=[];
 for(const failure of input.validationFailures||[])items.push(Object.freeze({id:`integrity:${failure}`,type:"integrity",severity:"critical",disposition:"open",title:"Integrity validation requires attention",explanation:clean(failure),blocking:true,reviewRequired:true,borrowerId:null,findingId:null,conditionId:null,documentReferences:[],recommendedAction:"Resolve the validation failure and rerun analysis.",rank:0,linked:false}));
 const conditionByFinding=new Map((input.conditions||[]).filter((c:any)=>c.generatedFromFindingId||c.findingId).map((c:any)=>[String(c.generatedFromFindingId||c.findingId),c]));
 for(const finding of input.findings||[]){const id=clean(finding.findingId||finding.id);if(!id)continue;const linked=conditionByFinding.get(id);items.push(Object.freeze({id:`finding:${id}`,type:"finding",severity:clean(finding.severity||"informational"),disposition:clean(finding.resolutionStatus||finding.disposition||"open"),title:clean(finding.title||"Review finding"),explanation:clean(finding.summary||finding.explanation),blocking:!!finding.blocking,reviewRequired:!!finding.reviewRequired,borrowerId:finding.borrowerId?clean(finding.borrowerId):null,findingId:id,conditionId:linked?clean(linked.id):finding.generatedConditionRef?clean(finding.generatedConditionRef):null,documentReferences:refs(finding.documents),recommendedAction:clean(finding.recommendedAction||"Review this finding."),rank:finding.blocking?(severityRank(clean(finding.severity))*10+10):(finding.reviewRequired?50+severityRank(clean(finding.severity)):70+severityRank(clean(finding.severity))),linked:!!linked||!!finding.generatedConditionRef}))}
 for(const condition of input.conditions||[]){const id=clean(condition.id);if(!id||condition.status==="cleared"||condition.status==="done")continue;const linkedFinding=clean(condition.generatedFromFindingId||condition.findingId);if(linkedFinding&&items.some(x=>x.findingId===linkedFinding)){const index=items.findIndex(x=>x.findingId===linkedFinding);items[index]=Object.freeze({...items[index],conditionId:id,linked:true});continue}items.push(Object.freeze({id:`condition:${id}`,type:"condition",severity:clean(condition.severity||"med"),disposition:clean(condition.status||"open"),title:clean(condition.title||condition.label||"Underwriting condition"),explanation:clean(condition.summary||condition.resolutionStrategy||"Condition remains unresolved."),blocking:!!condition.blocking||condition.severity==="high",reviewRequired:true,borrowerId:condition.borrowerId?clean(condition.borrowerId):null,findingId:null,conditionId:id,documentReferences:refs(condition.evidence),recommendedAction:clean((condition.requiredActions||[])[0]||"Review and resolve this condition."),rank:(condition.blocking||condition.severity==="high")?20+severityRank(clean(condition.severity)):80+severityRank(clean(condition.severity)),linked:false}))}
 for(const change of input.changes||[]){if(change.materiality==="immaterial"||change.favorability!=="adverse")continue;const id=clean(change.changeId);items.push(Object.freeze({id:`change:${id}`,type:"change",severity:change.materiality==="critical"?"critical":"high",disposition:clean(change.changeType||"modified"),title:`${clean(change.category).replace(/_/g," ")} changed`,explanation:clean(change.explanation),blocking:!!change.blocking,reviewRequired:!!change.reviewRequired,borrowerId:null,findingId:null,conditionId:null,documentReferences:refs(change.documentReferences?.map((documentId:string)=>({documentId}))),recommendedAction:clean(change.recommendedAction||"Review the material change."),rank:30+severityRank(change.materiality),linked:false}))}
 return Object.freeze(items.sort((a,b)=>a.rank-b.rank||a.id.localeCompare(b.id)));
}

export function buildUnderwriterWorkspace(applicationId:string,app:any,documents:readonly any[]){
 const scan=app.scan?.analysis||app.scan||{},enterprise=scan.enterpriseEvidence||{},review=scan.mortgageReview||{},conditions=scan.canonicalConditions||app.uwConditions||app.conditions||[],change=app.latestChangeSummary||scan.changeIntelligence||null,workflow=deriveEnterpriseWorkflow({...app,id:applicationId,scan,documentCount:documents.length});
 const evidence=(enterprise.package?.evidence||[]) as any[],resolutions=(enterprise.package?.resolutions||[]) as any[],derived=(enterprise.package?.derivedValues||[]) as any[];
 const evidenceById=new Map(evidence.map(x=>[x.evidenceId,x]));
 const fields=resolutions.map((field:any)=>{const ids=[field.winningEvidenceId,...(field.supportingEvidenceIds||[]),...(field.rejectedEvidenceIds||[])].filter(Boolean),sources=ids.map((id:string)=>evidenceById.get(id)).filter(Boolean);return Object.freeze({field:clean(field.fieldName),label:clean(field.label||field.fieldName),canonicalValue:field.canonicalValue??null,confidence:typeof field.confidence==="number"?field.confidence:null,verificationState:clean(field.verificationState||"unknown"),sourceCount:sources.length,conflictCount:(enterprise.package?.conflicts||[]).filter((x:any)=>x.fieldName===field.fieldName).length,reviewRequired:field.verificationState==="review_required"||field.verificationState==="conflict",resolutionReason:clean(field.resolutionReason),sources:Object.freeze(sources.map((x:any)=>({evidenceId:clean(x.evidenceId),documentId:clean(x.documentId),pageNumber:Number.isInteger(x.pageNumber)?x.pageNumber:null,rawValue:x.rawValue??null,normalizedValue:x.normalizedValue??null,confidence:typeof x.confidence==="number"?x.confidence:null,role:x.evidenceId===field.winningEvidenceId?"winning":(field.rejectedEvidenceIds||[]).includes(x.evidenceId)?"rejected":"supporting"}))),dependencies:Object.freeze((field.dependencies||[]).map(clean))})});
 const validationFailures=[...(enterprise.blockedReasons||[]),...(enterprise.package?.validation?.valid===false?enterprise.package.validation.errors||["Evidence package validation failed."]:[])];
 const agenda=buildReviewAgenda({validationFailures,findings:review.findings||[],conditions,changes:change?.changes||[]});
 const documentEvidence=new Map<string,any[]>();for(const item of evidence){const list=documentEvidence.get(item.documentId)||[];list.push(item);documentEvidence.set(item.documentId,list)}
 return Object.freeze({schemaVersion:UNDERWRITER_WORKSPACE_VERSION,application:Object.freeze({id:applicationId,borrowerName:clean(app.borrowerName)||"Borrower pending",loanNumber:clean(app.loanNumber)||null,loanAmount:typeof app.loanAmount==="number"?app.loanAmount:null,status:clean(app.status),analysisVersion:clean(scan.analysisVersion)||null,analysisVersionSequence:Number(app.analysisVersionSequence||0)}),workflow,documents:Object.freeze(documents.map(d=>Object.freeze({documentId:clean(d.documentId),mimeType:clean(d.mimeType),sizeBytes:Number(d.sizeBytes||0),uploadedAt:clean(d.uploadedAt),processingState:clean(d.processingState||d.status||app.documentProcessingStatus||"uploaded"),pageCount:Number.isInteger(d.pageCount)?d.pageCount:null,documentType:clean(d.documentType)||"Unclassified document",borrowerId:d.borrowerId?clean(d.borrowerId):null,evidenceCount:(documentEvidence.get(d.documentId)||[]).length,changed:!!change?.changes?.some((x:any)=>x.category==="document"&&x.entityId===d.documentId)}))),canonicalFields:Object.freeze(fields),findings:Object.freeze((review.findings||[]).map((f:any)=>Object.freeze({findingId:clean(f.findingId),title:clean(f.title),summary:clean(f.summary),explanation:clean(f.explanation),severity:clean(f.severity),category:clean(f.category),disposition:clean(f.disposition),blocking:!!f.blocking,reviewRequired:!!f.reviewRequired,resolutionStatus:clean(f.resolutionStatus||"open"),borrowerId:f.borrowerId?clean(f.borrowerId):null,documents:refs(f.documents),recommendedAction:clean(f.recommendedAction),generatedConditionRef:f.generatedConditionRef?clean(f.generatedConditionRef):null,ruleId:clean(f.ruleId),observedValues:(f.observedValues||[]).slice(0,10),expectedRelationship:clean(f.expectedRelationship),affectedFields:(f.affectedFields||[]).map(clean)}))),conditions:Object.freeze(conditions.map((c:any)=>Object.freeze({id:clean(c.id),title:clean(c.title||c.label),summary:clean(c.summary),severity:clean(c.severity),status:clean(c.status),blocking:!!c.blocking||c.severity==="high",owner:clean(c.owner),requiredActions:(c.requiredActions||[]).map(clean),requiredDocuments:(c.requiredDocuments||[]).map(clean),findingId:c.generatedFromFindingId||c.findingId||null}))),changeIntelligence:change?Object.freeze({overallMateriality:clean(change.overallMateriality),overallFavorability:clean(change.overallFavorability),reReviewRequired:!!change.reReviewRequired,recommendedAction:clean(change.recommendedAction),summary:change.summary||{},changes:Object.freeze((change.changes||[]).slice(0,100))}):null,agenda,summary:Object.freeze({unresolvedBlockers:agenda.filter(x=>x.blocking).length,reviewRequired:agenda.filter(x=>x.reviewRequired).length,nextAction:agenda[0]?.recommendedAction||workflow.requiredActions[0]||"Review the application.",baseline:!change}),validation:Object.freeze({valid:true,legacy:!enterprise.package,reviewAvailable:!!review.packageId||Array.isArray(review.findings),evidenceAvailable:!!enterprise.package})});
}
