import {createHash} from "node:crypto";
import type {EvidenceObject,EvidencePackage,FieldName,FieldResolution,DerivedValue} from "../../evidence/contracts";
import type {ApplicationAnalysisResult,VelocityCondition,ConditionCategory} from "../../ai/applicationAnalysisSchema";
import {selectRepresentativeCreditScoreValue} from "../canonicalCalculations";

export const MORTGAGE_REVIEW_ENGINE_VERSION="mortgage-review-engine.v1" as const;
export const MORTGAGE_REVIEW_PACKAGE_VERSION="velocity.mortgage-review-package.v1" as const;
export const MORTGAGE_REVIEW_TOLERANCES=Object.freeze({
  version:"mortgage-review-tolerances.v1",
  currencyRounding:1,
  incomeRelativeDifference:0.05,
  materialCurrencyRelativeDifference:0.02,
  dtiAbsoluteDifference:0.005,
  ltvAbsoluteDifference:0.005,
  lowConfidence:0.7,
} as const);

export type ReviewSeverity="critical"|"high"|"medium"|"low"|"informational";
export type ReviewDisposition="blocked"|"review_required"|"condition_required"|"warning"|"cleared"|"informational";
export type ReviewCategory="identity"|"employment"|"income"|"credit"|"liabilities"|"housing"|"calculation"|"loan"|"property"|"documentation"|"integrity";
export type ReviewFinding=Readonly<{findingId:string;ruleId:string;ruleVersion:"1.0.0";category:ReviewCategory;title:string;summary:string;explanation:string;severity:ReviewSeverity;materiality:"material"|"non_material";disposition:ReviewDisposition;blocking:boolean;reviewRequired:boolean;borrowerId:string|null;affectedFields:readonly string[];supportingEvidenceIds:readonly string[];conflictingEvidenceIds:readonly string[];documents:readonly Readonly<{documentId:string;pageNumber:number|null}>[];resolutionKeys:readonly string[];derivedValueIds:readonly string[];observedValues:readonly (string|number|boolean|null)[];expectedRelationship:string;resolutionStatus:"open"|"cleared";recommendedAction:string;generatedConditionRef:string|null;confidence:number;engineVersion:typeof MORTGAGE_REVIEW_ENGINE_VERSION}>;
export type RuleEvaluation=Readonly<{ruleId:string;ruleVersion:"1.0.0";result:"passed"|"finding"|"not_applicable"|"error";findingIds:readonly string[];failureClass:string|null}>;
export type MortgageReviewPackage=Readonly<{schemaVersion:typeof MORTGAGE_REVIEW_PACKAGE_VERSION;packageId:string;engineVersion:typeof MORTGAGE_REVIEW_ENGINE_VERSION;applicationId:string;evidencePackageId:string;analysisVersion:string;toleranceVersion:string;ruleVersions:Readonly<Record<string,"1.0.0">>;findings:readonly ReviewFinding[];evaluations:readonly RuleEvaluation[];bySeverity:Readonly<Record<ReviewSeverity,readonly string[]>>;byCategory:Readonly<Record<ReviewCategory,readonly string[]>>;blockingFindingIds:readonly string[];reviewRequiredFindingIds:readonly string[];conditionRequiredFindingIds:readonly string[];summary:Readonly<{status:"clear"|"review_required"|"blocked";total:number;critical:number;high:number;medium:number;low:number;informational:number;blocking:number;reviewRequired:number;conditionRequired:number}>;validation:Readonly<{valid:true;identityReproduced:true}>;diagnostics:readonly Readonly<{applicationId:string;ruleId:string;ruleVersion:string;result:string;failureClass:string|null}>[]}>

type Context={applicationId:string;evidence:EvidencePackage;analysis:ApplicationAnalysisResult;resolutions:Map<string,FieldResolution>;derived:Map<string,DerivedValue>;evidenceById:Map<string,EvidenceObject>};
type FindingInput=Omit<ReviewFinding,"findingId"|"ruleVersion"|"engineVersion"|"documents"|"resolutionKeys"|"generatedConditionRef"> & {ruleId:string;resolutionKeys?:readonly string[];generatedCondition?:boolean};
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const key=(field:string)=>`unassociated::${field}`;
const normalizeName=(value:unknown)=>String(value??"").normalize("NFKD").replace(/[^a-zA-Z0-9 ]/g," ").toLowerCase().replace(/\b(junior|jr|senior|sr|ii|iii|iv)\b/g,m=>m.slice(0,2)).replace(/\s+/g," ").trim();
const normalizeEmployer=(value:unknown)=>String(value??"").normalize("NFKD").replace(/[^a-zA-Z0-9 ]/g," ").toLowerCase().replace(/\b(incorporated|inc|limited|ltd|llc|corp(?:oration)?|company|co)\b/g,"").replace(/\s+/g," ").trim();
const numeric=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:null;
const relative=(a:number,b:number)=>Math.abs(a-b)/Math.max(Math.abs(a),Math.abs(b),1);
const evidenceFor=(c:Context,field:string)=>c.evidence.evidence.filter(e=>e.fieldName===field);
const resolutionFor=(c:Context,field:string)=>c.resolutions.get(key(field));
const derivedFor=(c:Context,field:string)=>c.derived.get(field);
function makeFinding(c:Context,input:FindingInput):ReviewFinding{
  const evidenceIds=[...new Set([...input.supportingEvidenceIds,...input.conflictingEvidenceIds])].sort();
  const documents=[...new Map(evidenceIds.map(id=>c.evidenceById.get(id)).filter(Boolean).map(e=>[`${e!.documentId}:${e!.pageNumber}`,Object.freeze({documentId:e!.documentId,pageNumber:e!.pageNumber??null})])).values()].sort((a,b)=>`${a.documentId}:${a.pageNumber}`.localeCompare(`${b.documentId}:${b.pageNumber}`));
  const material={ruleId:input.ruleId,applicationId:c.applicationId,evidencePackageId:c.evidence.packageId,category:input.category,severity:input.severity,disposition:input.disposition,fields:[...input.affectedFields].sort(),evidenceIds,observedValues:input.observedValues,expectedRelationship:input.expectedRelationship};
  const findingId=`mrf_${hash(material).slice(0,32)}`,conditionRef=input.generatedCondition?`condition_${hash([input.ruleId,...input.affectedFields,evidenceIds]).slice(0,32)}`:null;
  return Object.freeze({...input,findingId,ruleVersion:"1.0.0",engineVersion:MORTGAGE_REVIEW_ENGINE_VERSION,documents:Object.freeze(documents),resolutionKeys:Object.freeze(input.resolutionKeys??input.affectedFields.map(key)),generatedConditionRef:conditionRef,supportingEvidenceIds:Object.freeze([...input.supportingEvidenceIds].sort()),conflictingEvidenceIds:Object.freeze([...input.conflictingEvidenceIds].sort()),affectedFields:Object.freeze([...input.affectedFields]),observedValues:Object.freeze([...input.observedValues]),derivedValueIds:Object.freeze([...input.derivedValueIds])});
}
const conflictFinding=(c:Context,ruleId:string,category:ReviewCategory,field:string,title:string,normalizer:(v:unknown)=>unknown,action:string,severity:ReviewSeverity="high")=>{
  const records=evidenceFor(c,field),values=[...new Set(records.map(r=>normalizer(r.normalizedValue)).filter(Boolean))];if(values.length<2)return [];
  return [makeFinding(c,{ruleId,category,title,summary:`Materially different ${field} values remain unresolved.`,explanation:`Available mortgage evidence contains values that do not normalize to the same supported fact.`,severity,materiality:"material",disposition:"condition_required",blocking:false,reviewRequired:true,borrowerId:null,affectedFields:[field],supportingEvidenceIds:[],conflictingEvidenceIds:records.map(r=>r.evidenceId),derivedValueIds:[],observedValues:values as any[],expectedRelationship:`All current sources for ${field} should reconcile after harmless formatting normalization.`,resolutionStatus:"open",recommendedAction:action,confidence:Math.max(...records.map(r=>r.confidence)),generatedCondition:true})];
};
const numericConflict=(c:Context,ruleId:string,category:ReviewCategory,field:string,title:string,tolerance:number,action:string,severity:ReviewSeverity="high")=>{const records=evidenceFor(c,field),values=records.map(r=>numeric(r.normalizedValue)).filter((v):v is number=>v!==null);if(values.length<2||Math.max(...values)-Math.min(...values)<=MORTGAGE_REVIEW_TOLERANCES.currencyRounding||relative(Math.max(...values),Math.min(...values))<=tolerance)return[];return[makeFinding(c,{ruleId,category,title,summary:`Material ${field} disagreement requires review.`,explanation:"The selected canonical value has materially different competing evidence.",severity,materiality:"material",disposition:"review_required",blocking:false,reviewRequired:true,borrowerId:null,affectedFields:[field],supportingEvidenceIds:[],conflictingEvidenceIds:records.map(r=>r.evidenceId),derivedValueIds:[],observedValues:values,expectedRelationship:`Values should agree within ${tolerance*100}% after currency rounding.`,resolutionStatus:"open",recommendedAction:action,confidence:Math.max(...records.map(r=>r.confidence))})]};
const missing=(c:Context,field:string,title:string,category:ReviewCategory,action:string,blocking=false)=>resolutionFor(c,field)?[]:[makeFinding(c,{ruleId:`MR.MISSING.${field.toUpperCase().replace(/\W/g,"_")}`,category,title,summary:`No valid enterprise evidence supports ${field}.`,explanation:"A material underwriting input cannot be traced to a canonical evidence resolution.",severity:blocking?"critical":"high",materiality:"material",disposition:blocking?"blocked":"condition_required",blocking,reviewRequired:true,borrowerId:null,affectedFields:[field],supportingEvidenceIds:[],conflictingEvidenceIds:[],derivedValueIds:[],observedValues:[],expectedRelationship:"A material canonical input must have a valid evidence resolution.",resolutionStatus:"open",recommendedAction:action,confidence:1,generatedCondition:!blocking})];

export function evaluateMortgageReview(applicationId:string,evidence:EvidencePackage,analysis:ApplicationAnalysisResult):MortgageReviewPackage{
  if(evidence.validation?.valid!==true||!evidence.packageId||analysis.analysisVersion.trim()==="")throw new Error("MORTGAGE_REVIEW_INPUT_INVALID");
  const c:Context={applicationId,evidence,analysis,resolutions:new Map(evidence.resolutions.map(r=>[`${r.borrowerId??"unassociated"}::${r.fieldName}`,r])),derived:new Map(evidence.derivedValues.map(d=>[d.fieldName,d])),evidenceById:new Map(evidence.evidence.map(e=>[e.evidenceId,e]))};
  const rules:readonly [string,()=>ReviewFinding[]][]=[
    ["MR.IDENTITY.CONSISTENCY",()=>conflictFinding(c,"MR.IDENTITY.CONSISTENCY","identity","borrower.name","Borrower identity conflict",normalizeName,"Obtain corrected identity or application documentation.")],
    ["MR.EMPLOYER.CONSISTENCY",()=>conflictFinding(c,"MR.EMPLOYER.CONSISTENCY","employment","employment.employer","Employer identity conflict",normalizeEmployer,"Obtain employer clarification or corrected VOE.")],
    ["MR.INCOME.CONSISTENCY",()=>numericConflict(c,"MR.INCOME.CONSISTENCY","income","income.amount","Monthly income disagreement",MORTGAGE_REVIEW_TOLERANCES.incomeRelativeDifference,"Reconcile current qualifying income and pay frequency.")],
    ["MR.CREDIT.CONSISTENCY",()=>{const records=evidenceFor(c,"credit.score"),scores=records.map(r=>numeric(r.normalizedValue)).filter((v):v is number=>v!==null),selected=numeric(resolutionFor(c,"credit.score")?.canonicalValue),expected=selectRepresentativeCreditScoreValue(scores);return selected!==null&&expected!==null&&selected!==expected?[makeFinding(c,{ruleId:"MR.CREDIT.CONSISTENCY",category:"credit",title:"Representative credit score mismatch",summary:"The selected score does not match the canonical representative-score rule.",explanation:"The available bureau score evidence produces a different representative score.",severity:"high",materiality:"material",disposition:"review_required",blocking:false,reviewRequired:true,borrowerId:null,affectedFields:["credit.score"],supportingEvidenceIds:[],conflictingEvidenceIds:records.map(r=>r.evidenceId),derivedValueIds:[],observedValues:[selected,expected,...scores],expectedRelationship:"Use existing canonical middle/lower representative-score selection.",resolutionStatus:"open",recommendedAction:"Re-run credit score selection and confirm borrower association.",confidence:1})]:[]}],
    ["MR.LIABILITY.CONSISTENCY",()=>{const d=derivedFor(c,"custom.total_monthly_liabilities"),calc=analysis.calculations?.monthlyLiabilities.result,res=numeric(resolutionFor(c,"debts.monthly")?.canonicalValue);return !d||calc===null||calc===undefined||res===null||Math.abs(calc-res)>MORTGAGE_REVIEW_TOLERANCES.currencyRounding?[makeFinding(c,{ruleId:"MR.LIABILITY.CONSISTENCY",category:"liabilities",title:"Liability total is not reconstructable",summary:"Canonical liability evidence and calculation output do not reconcile.",explanation:"The monthly liability chain is missing or differs from the selected evidence-backed total.",severity:"critical",materiality:"material",disposition:"blocked",blocking:true,reviewRequired:true,borrowerId:null,affectedFields:["debts.monthly"],supportingEvidenceIds:d?.inputEvidenceIds??[],conflictingEvidenceIds:[],derivedValueIds:d?[d.derivedValueId]:[],observedValues:[res,calc??null],expectedRelationship:"Resolved monthly liabilities must equal the canonical monthly-liabilities calculation.",resolutionStatus:"open",recommendedAction:"Reconcile included liabilities and rerun canonical calculations.",confidence:1})]:[]}],
    ["MR.PITIA.CONSISTENCY",()=>{const d=derivedFor(c,"custom.pitia"),calc=analysis.calculations?.pitia.result;return !d||calc===null||calc===undefined?[makeFinding(c,{ruleId:"MR.PITIA.CONSISTENCY",category:"housing",title:"PITIA support is incomplete",summary:"The PITIA value lacks a complete derived evidence chain.",explanation:"Housing expense cannot be treated as final without reconstructable canonical dependencies.",severity:"high",materiality:"material",disposition:"review_required",blocking:false,reviewRequired:true,borrowerId:null,affectedFields:["custom.pitia"],supportingEvidenceIds:d?.inputEvidenceIds??[],conflictingEvidenceIds:[],derivedValueIds:d?[d.derivedValueId]:[],observedValues:[calc??null],expectedRelationship:"PITIA must have a canonical result and derived evidence chain.",resolutionStatus:"open",recommendedAction:"Confirm PITIA components and rerun analysis.",confidence:1})]:[]}],
    ["MR.DTI.RECONSTRUCTION",()=>calculationFinding(c,"MR.DTI.RECONSTRUCTION","custom.back_end_dti",analysis.calculations?.backEndDti.result,analysis.normalized.backEndDti,MORTGAGE_REVIEW_TOLERANCES.dtiAbsoluteDifference,"Back-end DTI cannot be reproduced")],
    ["MR.LTV.RECONSTRUCTION",()=>calculationFinding(c,"MR.LTV.RECONSTRUCTION","custom.ltv",analysis.calculations?.ltv.result,analysis.normalized.ltv,MORTGAGE_REVIEW_TOLERANCES.ltvAbsoluteDifference,"LTV cannot be reproduced")],
    ["MR.LOAN_AMOUNT.CONSISTENCY",()=>numericConflict(c,"MR.LOAN_AMOUNT.CONSISTENCY","loan","loan.amount","Loan amount conflict",MORTGAGE_REVIEW_TOLERANCES.materialCurrencyRelativeDifference,"Reconcile the application and disclosure loan amount.")],
    ["MR.PROPERTY_VALUE.CONSISTENCY",()=>numericConflict(c,"MR.PROPERTY_VALUE.CONSISTENCY","property","property.appraised_value","Appraised value conflict",MORTGAGE_REVIEW_TOLERANCES.materialCurrencyRelativeDifference,"Reconcile appraisal value evidence.")],
    ["MR.MISSING.MATERIAL_SUPPORT",()=>[...missing(c,"borrower.name","Borrower identity lacks support","documentation","Obtain identity evidence."),...missing(c,"employment.employer","Employer lacks support","documentation","Obtain current employment evidence."),...missing(c,"income.amount","Qualifying income lacks support","income","Obtain usable income documentation."),...missing(c,"credit.score","Credit score lacks support","credit","Obtain sufficient credit evidence."),...missing(c,"debts.monthly","Liabilities lack support","liabilities","Obtain credit liability evidence.",true),...missing(c,"loan.amount","Loan amount lacks support","loan","Obtain application or disclosure evidence.",true),...(resolutionFor(c,"property.appraised_value")||resolutionFor(c,"property.purchase_price")?[]:missing(c,"property.appraised_value","Property value lacks support","property","Obtain appraisal or transaction-value evidence.",true))]],
    ["MR.CROSS_CALCULATION.STALE",()=>{const pairs=[
      ["income.amount",numeric(resolutionFor(c,"income.amount")?.canonicalValue),analysis.normalized.income,MORTGAGE_REVIEW_TOLERANCES.currencyRounding],
      ["debts.monthly",numeric(resolutionFor(c,"debts.monthly")?.canonicalValue),analysis.normalized.debts,MORTGAGE_REVIEW_TOLERANCES.currencyRounding],
      ["loan.amount",numeric(resolutionFor(c,"loan.amount")?.canonicalValue),analysis.normalized.loanAmount,MORTGAGE_REVIEW_TOLERANCES.currencyRounding],
      ["credit.score",numeric(resolutionFor(c,"credit.score")?.canonicalValue),analysis.normalized.creditScore,0],
    ] as const;return pairs.flatMap(([field,canonical,displayed,tolerance])=>canonical!==null&&displayed!==null&&displayed!==undefined&&Math.abs(canonical-displayed)>tolerance?[makeFinding(c,{ruleId:"MR.CROSS_CALCULATION.STALE",category:"integrity",title:`Stale ${field} analysis value`,summary:`The analysis value for ${field} differs from its current canonical resolution.`,explanation:"A downstream analysis or display path appears to be using a stale or parallel value.",severity:"critical",materiality:"material",disposition:"blocked",blocking:true,reviewRequired:true,borrowerId:null,affectedFields:[field],supportingEvidenceIds:resolutionFor(c,field)?.supportingEvidenceIds??[],conflictingEvidenceIds:resolutionFor(c,field)?.rejectedEvidenceIds??[],derivedValueIds:[],observedValues:[canonical,displayed],expectedRelationship:"Analysis and report values must equal the current canonical resolution.",resolutionStatus:"open",recommendedAction:"Block decisioning and regenerate analysis and report from the current evidence package.",confidence:1})]:[])}],
  ];
  const findings:ReviewFinding[]=[],evaluations:RuleEvaluation[]=[];
  for(const [ruleId,run] of rules){try{const result=run();findings.push(...result);evaluations.push(Object.freeze({ruleId,ruleVersion:"1.0.0",result:result.length?"finding":"passed",findingIds:Object.freeze(result.map(f=>f.findingId)),failureClass:null}))}catch{evaluations.push(Object.freeze({ruleId,ruleVersion:"1.0.0",result:"error",findingIds:Object.freeze([]),failureClass:"RULE_EVALUATION_ERROR"}))}}
  const sorted=Object.freeze(findings.sort((a,b)=>a.findingId.localeCompare(b.findingId))),severities=["critical","high","medium","low","informational"] as const,categories=["identity","employment","income","credit","liabilities","housing","calculation","loan","property","documentation","integrity"] as const;
  const bySeverity=Object.freeze(Object.fromEntries(severities.map(s=>[s,Object.freeze(sorted.filter(f=>f.severity===s).map(f=>f.findingId))])) as Record<ReviewSeverity,readonly string[]>),byCategory=Object.freeze(Object.fromEntries(categories.map(x=>[x,Object.freeze(sorted.filter(f=>f.category===x).map(f=>f.findingId))])) as Record<ReviewCategory,readonly string[]>);
  const summary=Object.freeze({status:sorted.some(f=>f.blocking)?"blocked" as const:sorted.some(f=>f.reviewRequired)?"review_required" as const:"clear" as const,total:sorted.length,critical:bySeverity.critical.length,high:bySeverity.high.length,medium:bySeverity.medium.length,low:bySeverity.low.length,informational:bySeverity.informational.length,blocking:sorted.filter(f=>f.blocking).length,reviewRequired:sorted.filter(f=>f.reviewRequired).length,conditionRequired:sorted.filter(f=>f.disposition==="condition_required").length});
  const ruleVersions=Object.freeze(Object.fromEntries(rules.map(([id])=>[id,"1.0.0" as const])));const identityMaterial={schemaVersion:MORTGAGE_REVIEW_PACKAGE_VERSION,engineVersion:MORTGAGE_REVIEW_ENGINE_VERSION,applicationId,evidencePackageId:evidence.packageId,analysisVersion:analysis.analysisVersion,toleranceVersion:MORTGAGE_REVIEW_TOLERANCES.version,ruleVersions,findings:sorted,evaluations};const packageId=hash(identityMaterial);
  return Object.freeze({...identityMaterial,packageId,bySeverity,byCategory,blockingFindingIds:Object.freeze(sorted.filter(f=>f.blocking).map(f=>f.findingId)),reviewRequiredFindingIds:Object.freeze(sorted.filter(f=>f.reviewRequired).map(f=>f.findingId)),conditionRequiredFindingIds:Object.freeze(sorted.filter(f=>f.disposition==="condition_required").map(f=>f.findingId)),summary,validation:Object.freeze({valid:true as const,identityReproduced:true as const}),diagnostics:Object.freeze(evaluations.map(e=>Object.freeze({applicationId,ruleId:e.ruleId,ruleVersion:e.ruleVersion,result:e.result,failureClass:e.failureClass})))}) as MortgageReviewPackage;
}

function calculationFinding(c:Context,ruleId:string,field:string,canonical:number|null|undefined,displayed:number|null|undefined,tolerance:number,title:string):ReviewFinding[]{const d=derivedFor(c,field),invalid=!d||canonical===null||canonical===undefined||displayed===null||displayed===undefined||Math.abs(canonical-displayed)>tolerance;if(!invalid)return[];return[makeFinding(c,{ruleId,category:"calculation",title,summary:`${field} has a broken or stale canonical dependency.`,explanation:"The derived evidence chain and displayed canonical calculation cannot be reproduced within the versioned tolerance.",severity:"critical",materiality:"material",disposition:"blocked",blocking:true,reviewRequired:true,borrowerId:null,affectedFields:[field],supportingEvidenceIds:d?.inputEvidenceIds??[],conflictingEvidenceIds:[],derivedValueIds:d?[d.derivedValueId]:[],observedValues:[canonical??null,displayed??null],expectedRelationship:`Derived and displayed values must agree within ${tolerance}.`,resolutionStatus:"open",recommendedAction:"Block decisioning, rebuild canonical dependencies, and rerun analysis.",confidence:1})]}

export function conditionsFromMortgageReview(review:MortgageReviewPackage,evidence:EvidencePackage):VelocityCondition[]{const byId=new Map(evidence.evidence.map(e=>[e.evidenceId,e]));return review.findings.filter(f=>f.generatedConditionRef).map(f=>({id:f.generatedConditionRef!,title:f.title,summary:f.summary,category:conditionCategory(f.category),severity:f.severity==="critical"||f.severity==="high"?"high":f.severity==="medium"?"med":"low",blocking:f.blocking,status:"open",owner:"underwriter",borrowerVisible:false,autoClearEligible:false,confidence:f.confidence,relatedFields:[...f.affectedFields],evidence:[...f.supportingEvidenceIds,...f.conflictingEvidenceIds].map(id=>byId.get(id)).filter(Boolean).map(e=>({sourceDoc:e!.documentId,sourceType:"unknown" as const,snippet:`Evidence-backed ${e!.fieldName} source`,confidence:e!.confidence,relatedField:e!.fieldName,page:e!.pageNumber})),evidenceRefs:[...f.supportingEvidenceIds,...f.conflictingEvidenceIds],requiredActions:[f.recommendedAction],requiredDocuments:[],dependencyConditions:[],resolutionStrategy:"manual_underwriter_review",source:"conflict"}))}
const conditionCategory=(c:ReviewCategory):ConditionCategory=>c==="employment"?"documentation":c==="housing"?"property":c==="loan"||c==="calculation"||c==="integrity"?"underwriting":c;
