import {createHash} from "node:crypto";
import {resolveGovernanceRole,evaluateApprovalAuthority,DEFAULT_APPROVAL_POLICY} from "../governance/enterpriseGovernance";

export const IDENTITY_LIFECYCLE_VERSION="enterprise-identity-lifecycle.v1" as const;
export const INVITATION_VERSION="enterprise-invitation.v1" as const;
export const IDENTITY_POLICY_VERSION="enterprise-identity-policy.v1" as const;
export const MEMBERSHIP_LIFECYCLE_STATES=["invited","pending","active","suspended","disabled","expired","archived"] as const;
export type MembershipLifecycleState=typeof MEMBERSHIP_LIFECYCLE_STATES[number];
export const MEMBERSHIP_TRANSITIONS=Object.freeze({
 invited:Object.freeze(["pending","expired","archived"]),pending:Object.freeze(["active","expired","archived"]),active:Object.freeze(["suspended","disabled","expired","archived"]),suspended:Object.freeze(["active","disabled","expired","archived"]),disabled:Object.freeze(["active","archived"]),expired:Object.freeze(["active","archived"]),archived:Object.freeze([]),
} satisfies Record<MembershipLifecycleState,readonly MembershipLifecycleState[]>);
export function evaluateMembershipTransition(current:unknown,target:unknown){if(!MEMBERSHIP_LIFECYCLE_STATES.includes(current as any)||!MEMBERSHIP_LIFECYCLE_STATES.includes(target as any))return Object.freeze({allowed:false as const,reason:"membership_state_unknown"});return (MEMBERSHIP_TRANSITIONS[current as MembershipLifecycleState] as readonly MembershipLifecycleState[]).includes(target as MembershipLifecycleState)?Object.freeze({allowed:true as const,reason:"authorized"}):Object.freeze({allowed:false as const,reason:"transition_invalid"})}
export const authorizationVersion=(input:{tenantId:string;userId:string;membershipVersion:number;role:string;teamIds:readonly string[];managerIds:readonly string[];status:string})=>`authority-${createHash("sha256").update(JSON.stringify([IDENTITY_LIFECYCLE_VERSION,input.tenantId,input.userId,input.membershipVersion,input.role,[...input.teamIds].sort(),[...input.managerIds].sort(),input.status])).digest("hex").slice(0,32)}`;
export function evaluateMembershipAuthority(input:{membership?:any;expectedMembershipVersion?:number;expectedAuthorizationVersion?:string;now:string}){
 const membership=input.membership;if(!membership)return Object.freeze({allowed:false as const,reason:"membership_unknown"});if(!MEMBERSHIP_LIFECYCLE_STATES.includes(membership.membershipStatus))return Object.freeze({allowed:false as const,reason:"membership_state_unknown"});if(membership.membershipStatus!=="active")return Object.freeze({allowed:false as const,reason:"membership_"+membership.membershipStatus});if(membership.expiresAt&&Date.parse(membership.expiresAt)<=Date.parse(input.now))return Object.freeze({allowed:false as const,reason:"membership_expired"});if(!resolveGovernanceRole(membership.role).ok)return Object.freeze({allowed:false as const,reason:"role_unknown"});if(input.expectedMembershipVersion!==undefined&&input.expectedMembershipVersion!==membership.membershipVersion)return Object.freeze({allowed:false as const,reason:"membership_stale"});if(input.expectedAuthorizationVersion!==undefined&&input.expectedAuthorizationVersion!==membership.authorizationVersion)return Object.freeze({allowed:false as const,reason:"authorization_stale"});return Object.freeze({allowed:true as const,reason:"authorized",membershipVersion:membership.membershipVersion,authorizationVersion:membership.authorizationVersion,approvalAuthority:evaluateApprovalAuthority({role:membership.role,action:"approve",policy:DEFAULT_APPROVAL_POLICY})})}
export function invitationState(invitation:any,now:string){if(!invitation)return"unknown" as const;if(invitation.status==="cancelled")return"cancelled" as const;if(invitation.status==="accepted")return"accepted" as const;if(Date.parse(invitation.expiresAt)<=Date.parse(now))return"expired" as const;return invitation.status==="pending"?"pending" as const:"unknown" as const}
export function eligibleAssignment(input:{membership?:any;teams?:readonly any[];now:string}){const authority=evaluateMembershipAuthority({membership:input.membership,now:input.now});if(!authority.allowed)return Object.freeze({eligible:false as const,reason:authority.reason});const teamIds=Array.isArray(input.membership.teamIds)?input.membership.teamIds:[];if(teamIds.some((id:string)=>!input.teams?.some(team=>team.teamId===id&&team.status==="active")))return Object.freeze({eligible:false as const,reason:"team_inactive"});return Object.freeze({eligible:true as const,reason:"authorized",teamIds:Object.freeze([...teamIds])})}
