import { createHash } from "node:crypto";
import { DOCUMENT_EVIDENCE_RECORD_V1, DOCUMENT_EVIDENCE_SET_V1, EVIDENCE_CATEGORIES, type DocumentEvidenceRecordV1, type DocumentEvidenceSetV1, type EvidenceType } from "./documentEvidence";

export const APPLICATION_EVIDENCE_SET_V1 = "application-evidence-set.v1" as const;
export const APPLICATION_EVIDENCE_AGGREGATION_POLICY_V1 = "application-evidence-aggregation-policy.v1" as const;
export const APPLICATION_EVIDENCE_ENGINE_VERSION = "deterministic-application-evidence-aggregator.v1" as const;
export const APPLICATION_EVIDENCE_AGGREGATION_POLICY = Object.freeze({ policyVersion: APPLICATION_EVIDENCE_AGGREGATION_POLICY_V1, maximumDocuments: 100, maximumEvidenceRecords: 10_000, maximumCandidatesPerField: 500, maximumConflicts: 1_000, maximumWarnings: 1_000, maximumDiagnostics: 1_000, maximumSourceTextLength: 100_000 } as const);
export type EvidenceAggregationErrorCode = "EVIDENCE_COLLECTION_EMPTY"|"EVIDENCE_SET_INVALID"|"EVIDENCE_TENANT_MISMATCH"|"EVIDENCE_APPLICATION_MISMATCH"|"EVIDENCE_DOCUMENT_DUPLICATE"|"EVIDENCE_LINEAGE_INVALID"|"EVIDENCE_SCHEMA_UNSUPPORTED"|"AGGREGATION_POLICY_INVALID"|"AGGREGATION_LIMIT_EXCEEDED"|"INTERNAL_ERROR";
export class EvidenceAggregationError extends Error { constructor(readonly code: EvidenceAggregationErrorCode) { super(code); this.name = "EvidenceAggregationError"; Object.freeze(this); } }
type Candidate = DocumentEvidenceRecordV1 & Readonly<{ aggregationWarnings: readonly string[] }>;
type ValueRef = Readonly<{ kind: string; value: string }>;
type Group = Readonly<{ evidenceType: EvidenceType; fieldIdentifier: string; normalizedValues: readonly ValueRef[]; evidenceIds: readonly string[]; documentIds: readonly string[] }>;
export type ApplicationEvidenceSetV1 = Readonly<{ schemaVersion: typeof APPLICATION_EVIDENCE_SET_V1; tenantId:string; applicationId:string; aggregationPolicyVersion:typeof APPLICATION_EVIDENCE_AGGREGATION_POLICY_V1; evidenceEngineVersion:typeof APPLICATION_EVIDENCE_ENGINE_VERSION; aggregatedAt:string; requestId:string; correlationId:string; documentLineage:readonly Readonly<{documentId:string;documentAuthorizationVersion:string;sourceContentHash:string;processingFingerprint:string;evidenceCount:number}>[]; candidates:readonly Candidate[]; fieldGroups:readonly Group[]; agreementGroups:readonly Group[]; conflictGroups:readonly Group[]; duplicateGroups:readonly Readonly<{duplicateKey:string;evidenceIds:readonly string[];documentIds:readonly string[]}>[]; missingCategories:readonly EvidenceType[]; warnings:readonly string[]; diagnostics:readonly string[]; aggregationFingerprint:string }>;
const id=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/; const hash=/^[a-f0-9]{64}$/;
const arr=<T>(x:T[])=>Object.freeze(x.map(v=>typeof v==="object"&&v!==null?Object.freeze(v):v)) as readonly T[];
const fail=(code:EvidenceAggregationErrorCode):never=>{throw new EvidenceAggregationError(code)};
export function aggregateApplicationEvidence(sets:readonly DocumentEvidenceSetV1[],policy:typeof APPLICATION_EVIDENCE_AGGREGATION_POLICY,metadata:Readonly<{aggregatedAt:string;requestId:string;correlationId:string}>):ApplicationEvidenceSetV1{
 if(policy!==APPLICATION_EVIDENCE_AGGREGATION_POLICY)fail("AGGREGATION_POLICY_INVALID");if(!Array.isArray(sets)||sets.length===0)fail("EVIDENCE_COLLECTION_EMPTY");if(sets.length>policy.maximumDocuments)fail("AGGREGATION_LIMIT_EXCEEDED");if(!metadata||!id.test(metadata.requestId)||!id.test(metadata.correlationId)||Number.isNaN(Date.parse(metadata.aggregatedAt)))fail("EVIDENCE_SET_INVALID");
 const sorted=[...sets].sort((a,b)=>String(a?.documentId).localeCompare(String(b?.documentId)));const first=sorted[0];if(!first||first.schemaVersion!==DOCUMENT_EVIDENCE_SET_V1)fail("EVIDENCE_SCHEMA_UNSUPPORTED");const seen=new Set<string>();let count=0,warningCount=0,diagnosticCount=0;
 for(const set of sorted){if(!set||set.schemaVersion!==DOCUMENT_EVIDENCE_SET_V1)fail("EVIDENCE_SCHEMA_UNSUPPORTED");if(set.tenantId!==first.tenantId)fail("EVIDENCE_TENANT_MISMATCH");if(set.applicationId!==first.applicationId)fail("EVIDENCE_APPLICATION_MISMATCH");if(seen.has(set.documentId))fail("EVIDENCE_DOCUMENT_DUPLICATE");seen.add(set.documentId);if(!id.test(set.tenantId)||!id.test(set.applicationId)||!id.test(set.documentId)||!id.test(set.documentAuthorizationVersion)||!hash.test(set.sourceContentHash)||!hash.test(set.summary?.processingFingerprint))fail("EVIDENCE_LINEAGE_INVALID");count+=set.evidence.length;if(count>policy.maximumEvidenceRecords)fail("AGGREGATION_LIMIT_EXCEEDED");for(const r of set.evidence){warningCount+=r.warnings.length;diagnosticCount+=r.diagnostics.length;if(warningCount>policy.maximumWarnings||diagnosticCount>policy.maximumDiagnostics)fail("AGGREGATION_LIMIT_EXCEEDED");if(r.schemaVersion!==DOCUMENT_EVIDENCE_RECORD_V1||r.tenantId!==set.tenantId||r.applicationId!==set.applicationId||r.documentId!==set.documentId||!hash.test(r.evidenceId)||r.sourceContentHash!==set.sourceContentHash||!hash.test(r.processingFingerprint)||r.processingFingerprint!==set.summary.processingFingerprint||r.provenance?.documentAuthorizationVersion!==set.documentAuthorizationVersion||r.sourceText.length>policy.maximumSourceTextLength)fail("EVIDENCE_LINEAGE_INVALID");}}
 const base=sorted.flatMap(s=>s.evidence).sort((a,b)=>[a.evidenceType,a.fieldIdentifier,a.normalizedValue.kind,a.normalizedValue.value,a.documentId,a.pageNumber,a.evidenceId].join("\0").localeCompare([b.evidenceType,b.fieldIdentifier,b.normalizedValue.kind,b.normalizedValue.value,b.documentId,b.pageNumber,b.evidenceId].join("\0")));
 const exact=new Map<string,number[]>();base.forEach((r,i)=>{const k=JSON.stringify([r.evidenceType,r.fieldIdentifier,r.normalizedValue.kind,r.normalizedValue.value,r.sourceText,r.extractionMethod]);const x=exact.get(k)||[];x.push(i);exact.set(k,x)});const duplicateIndexes=new Set([...exact.values()].filter(x=>x.length>1).flat());
 const fields=new Map<string,DocumentEvidenceRecordV1[]>();base.forEach(r=>{const k=`${r.evidenceType}\0${r.fieldIdentifier}`;fields.set(k,[...(fields.get(k)||[]),r])});if([...fields.values()].some(x=>x.length>policy.maximumCandidatesPerField))fail("AGGREGATION_LIMIT_EXCEEDED");const conflictIds=new Set<string>();
 const groups=[...fields.entries()].sort().map(([,rs])=>{const values=[...new Map(rs.map(r=>[`${r.normalizedValue.kind}\0${r.normalizedValue.value}`,Object.freeze({...r.normalizedValue})])).values()].sort((a,b)=>`${a.kind}\0${a.value}`.localeCompare(`${b.kind}\0${b.value}`));if(values.length>1)rs.forEach(r=>conflictIds.add(r.evidenceId));return Object.freeze({evidenceType:rs[0].evidenceType,fieldIdentifier:rs[0].fieldIdentifier,normalizedValues:arr(values),evidenceIds:arr(rs.map(r=>r.evidenceId).sort()),documentIds:arr([...new Set(rs.map(r=>r.documentId))].sort())})});const conflicts=groups.filter(g=>g.documentIds.length>1&&g.normalizedValues.length>1);if(conflicts.length>policy.maximumConflicts)fail("AGGREGATION_LIMIT_EXCEEDED");
 const candidates=base.map((r,i)=>Object.freeze({...r,aggregationWarnings:arr([...(duplicateIndexes.has(i)?["duplicate_evidence"]:[]),...(conflictIds.has(r.evidenceId)?["conflicting_evidence"]:[])].sort())}));const duplicateGroups=[...exact.entries()].filter(([,xs])=>xs.length>1).sort(([a],[b])=>a.localeCompare(b)).map(([key,xs])=>Object.freeze({duplicateKey:createHash("sha256").update(key).digest("hex"),evidenceIds:arr(xs.map(i=>base[i].evidenceId).sort()),documentIds:arr([...new Set(xs.map(i=>base[i].documentId))].sort())}));
 const lineage=sorted.map(s=>Object.freeze({documentId:s.documentId,documentAuthorizationVersion:s.documentAuthorizationVersion,sourceContentHash:s.sourceContentHash,processingFingerprint:s.summary.processingFingerprint,evidenceCount:s.evidence.length}));const warnings=arr([...(conflicts.length?["conflicting_evidence"]:[]),...(duplicateGroups.length?["duplicate_evidence"]:[]),...(base.length?[]:["no_evidence_extracted"])].sort());const diagnostics=arr([] as string[]);const material={tenantId:first.tenantId,applicationId:first.applicationId,lineage,candidates:candidates.map(r=>[r.evidenceId,r.documentId,r.evidenceType,r.fieldIdentifier,r.normalizedValue.kind,r.normalizedValue.value]),policyVersion:policy.policyVersion,engineVersion:APPLICATION_EVIDENCE_ENGINE_VERSION};const fingerprint=createHash("sha256").update(JSON.stringify(material)).digest("hex");
 return Object.freeze({schemaVersion:APPLICATION_EVIDENCE_SET_V1,tenantId:first.tenantId,applicationId:first.applicationId,aggregationPolicyVersion:policy.policyVersion,evidenceEngineVersion:APPLICATION_EVIDENCE_ENGINE_VERSION,aggregatedAt:metadata.aggregatedAt,requestId:metadata.requestId,correlationId:metadata.correlationId,documentLineage:arr(lineage),candidates:arr(candidates),fieldGroups:arr(groups),agreementGroups:arr(groups.filter(g=>g.documentIds.length>1&&g.normalizedValues.length===1)),conflictGroups:arr(conflicts),duplicateGroups:arr(duplicateGroups),missingCategories:arr(EVIDENCE_CATEGORIES.filter(c=>c!=="unknown"&&!base.some(r=>r.evidenceType===c))),warnings,diagnostics,aggregationFingerprint:fingerprint});
}
