import {createHash} from "node:crypto";
import {parseServerAuthContext,type ServerAuthContextV1} from "../../contracts/serverAuth";
import {permissionsForRole} from "../authorization/permissionPolicy";
import {applyEvidenceReviewAction,EVIDENCE_REVIEW_AUTHORIZATION_V1,EVIDENCE_REVIEW_POLICY,EvidenceReviewError,type EvidenceReviewActionV1,type EvidenceReviewPermission,type EvidenceReviewRecordV1,type EvidenceReviewStatus} from "./evidenceReview";
import type {ApplicationEvidenceSetV1} from "./applicationEvidence";

export const EVIDENCE_REVIEW_COMMAND_RECEIPT_V1="evidence-review-command-receipt.v1" as const;
export const EVIDENCE_REVIEW_COMMAND_POLICY=Object.freeze({schemaVersion:"evidence-review-command-policy.v1" as const,status:"provisional_product_review_required" as const,policyVersion:"evidence-review-command-policy.v1",producerVersion:"evidence-review-command.v1",maximumCommandBytes:16_384,maximumTransactionAttempts:1,idempotencyRetentionDays:30});
export type EvidenceReviewCommandErrorCode="EVIDENCE_REVIEW_AUTHORIZATION_REQUIRED"|"EVIDENCE_REVIEW_PERMISSION_DENIED"|"EVIDENCE_AGGREGATION_NOT_FOUND"|"EVIDENCE_AGGREGATION_STALE"|"EVIDENCE_REVIEW_TARGET_NOT_FOUND"|"EVIDENCE_REVIEW_TARGET_STALE"|"EVIDENCE_REVIEW_HISTORY_INVALID"|"EVIDENCE_REVIEW_TRANSITION_INVALID"|"EVIDENCE_REVIEW_STALE"|"EVIDENCE_REVIEW_CONFLICT"|"EVIDENCE_REVIEW_ALREADY_COMPLETED"|"EVIDENCE_REVIEW_AUDIT_REQUIRED"|"EVIDENCE_REVIEW_WRITE_FAILED"|"DEPENDENCY_FAILURE"|"INTERNAL_ERROR";
export class EvidenceReviewCommandError extends Error{constructor(readonly code:EvidenceReviewCommandErrorCode){super(code);this.name="EvidenceReviewCommandError";Object.freeze(this)}}
export type EvidenceReviewCommandReceiptV1=Readonly<{schemaVersion:typeof EVIDENCE_REVIEW_COMMAND_RECEIPT_V1;commandId:string;reviewId:string;tenantId:string;applicationId:string;target:Readonly<{type:string;id:string}>;resultingStatus:EvidenceReviewStatus;aggregationFingerprint:string;priorStateVersion:number;newStateVersion:number;reviewRecordIntegrityFingerprint:string;auditEventId:string;writeResult:"created"|"already_exists_identical";persistedAt:string;requestId:string;correlationId:string;producerVersion:string}>;
export type EvidenceReviewAtomicInput=Readonly<{tenantId:string;applicationId:string;aggregationId:string;expectedAggregationFingerprint:string;expectedAggregationPolicyVersion:string;expectedEvidenceEngineVersion:string;expectedStateVersion:number;commandId:string;commandFingerprint:string;idempotencyKey:string;action:EvidenceReviewActionV1;authorization:Readonly<{reviewerUserId:string;membershipVersion:string;role:string;permission:EvidenceReviewPermission;decisionId:string}>;requestId:string;correlationId:string;persistedAt:string}>;
export type EvidenceReviewDenialAuditV1=Readonly<{schemaVersion:"evidence-review-denial-audit.v1";eventId:string;tenantId:string;applicationId:string;reviewerUserId:string;membershipVersion:string;tenantVersion:string;permission:EvidenceReviewPermission;action:string;targetType:string;targetId:string;aggregationFingerprint:string|"unavailable";policyVersion:string;requestId:string;correlationId:string;allow:false;safeReason:string;auditClassification:"sensitive_evidence_review_denial"}>;
export type EvidenceReviewCommandRepository=Readonly<{resolveTenant(authentication:ServerAuthContextV1,tenant?:unknown):Promise<Readonly<{tenantId:string;tenantVersion:string;membershipVersion:string;role:any}>>;authorizeApplication(tenantId:string,applicationId:string):Promise<boolean>;persistDenialAudit(audit:EvidenceReviewDenialAuditV1):Promise<void>;executeAtomic(input:EvidenceReviewAtomicInput,reduce:(aggregation:ApplicationEvidenceSetV1,history:readonly EvidenceReviewRecordV1[])=>ReturnType<typeof applyEvidenceReviewAction>):Promise<EvidenceReviewCommandReceiptV1>}>;
export type ExecuteEvidenceReviewCommandInput=Readonly<{authentication:unknown;requestedTenantId?:unknown;applicationId:string;aggregationId:string;aggregationFingerprint:string;aggregationPolicyVersion:string;evidenceEngineVersion:string;expectedStateVersion:number;idempotencyKey:string;action:EvidenceReviewActionV1;policy:typeof EVIDENCE_REVIEW_COMMAND_POLICY;persistedAt:string;repository:EvidenceReviewCommandRepository;onStep?:(step:string)=>void}>;
const sha=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex"),id=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
export function evidenceReviewCommandFingerprint(material:Readonly<Record<string,unknown>>){return sha(material)}
export async function executeEvidenceReviewCommand(input:ExecuteEvidenceReviewCommandInput):Promise<EvidenceReviewCommandReceiptV1>{
 const step=(s:string)=>input.onStep?.(s);step("validate_authentication");const parsed=parseServerAuthContext(input.authentication);if(!parsed.ok||parsed.value.principal.kind!=="firebase_user")throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_AUTHORIZATION_REQUIRED");const reviewerUserId=parsed.value.principal.uid;if(input.policy!==EVIDENCE_REVIEW_COMMAND_POLICY||!id.test(input.applicationId)||!id.test(input.aggregationId)||!id.test(input.idempotencyKey)||!Number.isSafeInteger(input.expectedStateVersion)||input.expectedStateVersion<0||Buffer.byteLength(JSON.stringify(input))>input.policy.maximumCommandBytes)throw new EvidenceReviewCommandError("INTERNAL_ERROR");
 step("resolve_tenant_membership");let tenant;try{tenant=await input.repository.resolveTenant(parsed.value,input.requestedTenantId)}catch{throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_PERMISSION_DENIED")}
 const permission=EVIDENCE_REVIEW_POLICY.permissionByAction[input.action.action]||"evidence.review";const denial=async(code:EvidenceReviewCommandErrorCode,aggregationFingerprint:string|"unavailable"="unavailable"):Promise<never>=>{step("persist_denial_audit");try{await input.repository.persistDenialAudit(Object.freeze({schemaVersion:"evidence-review-denial-audit.v1",eventId:`erd_${sha([tenant.tenantId,input.applicationId,parsed.value.requestId,code]).slice(0,32)}`,tenantId:tenant.tenantId,applicationId:input.applicationId,reviewerUserId,membershipVersion:tenant.membershipVersion,tenantVersion:tenant.tenantVersion,permission,action:input.action.action,targetType:input.action.targetType,targetId:input.action.targetId,aggregationFingerprint,policyVersion:input.policy.policyVersion,requestId:parsed.value.requestId,correlationId:parsed.value.correlationId,allow:false,safeReason:code,auditClassification:"sensitive_evidence_review_denial"}))}catch{throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_AUDIT_REQUIRED")}throw new EvidenceReviewCommandError(code)};
 step("authorize_application");let accessible=false;try{accessible=await input.repository.authorizeApplication(tenant.tenantId,input.applicationId)}catch{throw new EvidenceReviewCommandError("DEPENDENCY_FAILURE")}if(!accessible)return denial("EVIDENCE_REVIEW_PERMISSION_DENIED");
 step("require_review_permission");if(!EVIDENCE_REVIEW_POLICY.permissionByAction[input.action.action]||!permissionsForRole(tenant.role).includes("evidence.read")||!permissionsForRole(tenant.role).includes(permission as any))return denial("EVIDENCE_REVIEW_PERMISSION_DENIED");
 const commandId=`erc_${sha([tenant.tenantId,input.applicationId,input.idempotencyKey]).slice(0,32)}`;const fingerprint=evidenceReviewCommandFingerprint({tenantId:tenant.tenantId,applicationId:input.applicationId,aggregationFingerprint:input.aggregationFingerprint,targetType:input.action.targetType,targetId:input.action.targetId,targetEvidenceFingerprint:input.action.targetEvidenceFingerprint,action:input.action.action,reviewId:input.action.reviewId,priorReviewId:input.action.priorReviewId,justificationCode:input.action.justificationCode,note:input.action.note,reviewer:reviewerUserId,permission,policyVersion:input.policy.policyVersion,expectedStateVersion:input.expectedStateVersion});
 step("execute_atomic_persistence");try{return await input.repository.executeAtomic({tenantId:tenant.tenantId,applicationId:input.applicationId,aggregationId:input.aggregationId,expectedAggregationFingerprint:input.aggregationFingerprint,expectedAggregationPolicyVersion:input.aggregationPolicyVersion,expectedEvidenceEngineVersion:input.evidenceEngineVersion,expectedStateVersion:input.expectedStateVersion,commandId,commandFingerprint:fingerprint,idempotencyKey:input.idempotencyKey,action:input.action,authorization:{reviewerUserId,membershipVersion:tenant.membershipVersion,role:tenant.role,permission,decisionId:`${commandId}:authorization`},requestId:parsed.value.requestId,correlationId:parsed.value.correlationId,persistedAt:input.persistedAt},(aggregation,history)=>applyEvidenceReviewAction(aggregation,history,Object.freeze({schemaVersion:EVIDENCE_REVIEW_AUTHORIZATION_V1,decision:"allow",tenantId:tenant.tenantId,applicationId:input.applicationId,reviewerUserId,reviewerMembershipVersion:tenant.membershipVersion,reviewerRole:tenant.role,permission,authorizationDecisionId:`${commandId}:authorization`}),input.action,EVIDENCE_REVIEW_POLICY,{requestId:parsed.value.requestId,correlationId:parsed.value.correlationId}))}catch(error){const code=error instanceof EvidenceReviewError?error.code:error instanceof EvidenceReviewCommandError?error.code:undefined;const safeDenials=["EVIDENCE_AGGREGATION_NOT_FOUND","EVIDENCE_AGGREGATION_STALE","EVIDENCE_REVIEW_TARGET_NOT_FOUND","EVIDENCE_REVIEW_TARGET_STALE","EVIDENCE_REVIEW_HISTORY_INVALID","EVIDENCE_REVIEW_TRANSITION_INVALID","EVIDENCE_REVIEW_STALE","EVIDENCE_REVIEW_CONFLICT","EVIDENCE_REVIEW_ALREADY_COMPLETED"] as const;if(code&&safeDenials.includes(code as typeof safeDenials[number]))return denial(code as EvidenceReviewCommandErrorCode,input.aggregationFingerprint);if(error instanceof EvidenceReviewCommandError)throw error;throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_WRITE_FAILED")}
}
