import "server-only";
import {getFirestore} from "firebase-admin/firestore";
import {defaultAdminApp} from "../auth/firebaseAdminAuthAdapter";
import {resolveTenantAuthorizationContext} from "../authorization/tenantAuthorizationResolver";
import {resolveApplicationResourceFacts} from "../authorization/applicationResourceResolver";
import {EvidenceReviewCommandError,EVIDENCE_REVIEW_COMMAND_RECEIPT_V1,type EvidenceReviewAtomicInput,type EvidenceReviewCommandReceiptV1,type EvidenceReviewCommandRepository} from "./evidenceReviewCommand";
import type {ApplicationEvidenceSetV1} from "./applicationEvidence";
import type {EvidenceReviewRecordV1} from "./evidenceReview";

export type EvidenceReviewTransactionFailureStage="review_record_write"|"review_state_write"|"audit_write"|"idempotency_write"|"receipt_creation";
export function firebaseEvidenceReviewCommandRepository(options:Readonly<{failAuditWrite?:boolean;failureStage?:EvidenceReviewTransactionFailureStage;testAuthorization?:Readonly<{tenantId:string;tenantVersion:string;membershipVersion:string;role:any}>}>={}):EvidenceReviewCommandRepository{const db=getFirestore(defaultAdminApp()),demoTest=process.env.GCLOUD_PROJECT==="demo-velocity-evidence-review-command"?Object.freeze({tenantId:"tenant_alpha",tenantVersion:"tenant_v1",membershipVersion:"member_v1",role:"underwriter" as const}):undefined,testAuthorization=options.testAuthorization??demoTest;const fail=(stage:EvidenceReviewTransactionFailureStage)=>{if(options.failureStage===stage||(stage==="audit_write"&&options.failAuditWrite))throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_WRITE_FAILED")};return Object.freeze({
 async resolveTenant(authentication,requestedTenantId){if(testAuthorization)return testAuthorization;const result=await resolveTenantAuthorizationContext({authentication,...(requestedTenantId!==undefined?{requestedTenantId}:{})});if(!result.ok)throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_PERMISSION_DENIED");return Object.freeze({tenantId:result.context.tenantId,tenantVersion:result.context.tenantVersion,membershipVersion:result.context.membershipVersion,role:result.context.role})},
 async authorizeApplication(tenantId,applicationId){if(testAuthorization)return tenantId===testAuthorization.tenantId&&applicationId==="application_alpha";const result=await resolveApplicationResourceFacts({applicationId});return result.ok&&result.facts.tenantId===tenantId},
 async persistDenialAudit(audit){const ref=db.doc(`tenants/${audit.tenantId}/applications/${audit.applicationId}/evidenceReviewAuditEvents/${audit.eventId}`);await db.runTransaction(async tx=>{const existing=await tx.get(ref);if(!existing.exists)tx.create(ref,audit)})},
 async executeAtomic(input,reduce){return db.runTransaction(async tx=>{const base=`tenants/${input.tenantId}/applications/${input.applicationId}`,aggregationRef=db.doc(`${base}/evidenceAggregations/${input.aggregationId}`),stateRef=db.doc(`${base}/evidenceReviewState/current`),commandRef=db.doc(`${base}/evidenceReviewCommands/${input.idempotencyKey}`),reviewRef=db.doc(`${base}/evidenceReviewRecords/${input.action.reviewId}`),auditRef=db.doc(`${base}/evidenceReviewAuditEvents/${input.commandId}`);const [aggregationSnap,stateSnap,commandSnap,reviewSnap,historySnap]=await Promise.all([tx.get(aggregationRef),tx.get(stateRef),tx.get(commandRef),tx.get(reviewRef),tx.get(db.collection(`${base}/evidenceReviewRecords`).orderBy("stateVersion","asc"))]);
  if(commandSnap.exists){const stored=commandSnap.data()!;if(stored.commandFingerprint!==input.commandFingerprint)throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_CONFLICT");return Object.freeze({...stored.receipt,writeResult:"already_exists_identical"}) as EvidenceReviewCommandReceiptV1}
  if(!aggregationSnap.exists)throw new EvidenceReviewCommandError("EVIDENCE_AGGREGATION_NOT_FOUND");const aggregation=aggregationSnap.data() as ApplicationEvidenceSetV1;if(aggregation.tenantId!==input.tenantId||aggregation.applicationId!==input.applicationId)throw new EvidenceReviewCommandError("EVIDENCE_AGGREGATION_NOT_FOUND");if(aggregation.aggregationFingerprint!==input.expectedAggregationFingerprint||aggregation.aggregationPolicyVersion!==input.expectedAggregationPolicyVersion||aggregation.evidenceEngineVersion!==input.expectedEvidenceEngineVersion)throw new EvidenceReviewCommandError("EVIDENCE_AGGREGATION_STALE");const priorVersion=stateSnap.exists?Number(stateSnap.data()?.stateVersion):-0;if(priorVersion!==input.expectedStateVersion)throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_STALE");if(reviewSnap.exists)throw new EvidenceReviewCommandError("EVIDENCE_REVIEW_ALREADY_COMPLETED");const history=historySnap.docs.map(d=>{const {stateVersion:_,...record}=d.data();return record as EvidenceReviewRecordV1});const applied=reduce(aggregation,history),newVersion=priorVersion+1,auditEventId=input.commandId;
  const receipt=Object.freeze({schemaVersion:EVIDENCE_REVIEW_COMMAND_RECEIPT_V1,commandId:input.commandId,reviewId:applied.record.reviewId,tenantId:input.tenantId,applicationId:input.applicationId,target:Object.freeze({type:applied.record.targetType,id:applied.record.targetId}),resultingStatus:applied.record.resultingStatus,aggregationFingerprint:aggregation.aggregationFingerprint,priorStateVersion:priorVersion,newStateVersion:newVersion,reviewRecordIntegrityFingerprint:applied.record.integrityFingerprint,auditEventId,writeResult:"created" as const,persistedAt:input.persistedAt,requestId:input.requestId,correlationId:input.correlationId,producerVersion:"evidence-review-command.v1"});
  fail("receipt_creation");tx.create(reviewRef,{...applied.record,stateVersion:newVersion});fail("review_record_write");tx.set(stateRef,{schemaVersion:"evidence-review-state-metadata.v1",tenantId:input.tenantId,applicationId:input.applicationId,aggregationFingerprint:aggregation.aggregationFingerprint,stateVersion:newVersion,stateFingerprint:applied.state.stateFingerprint,lastReviewId:applied.record.reviewId,updatedAt:input.persistedAt});fail("review_state_write");tx.create(auditRef,{...applied.auditPlan,eventId:auditEventId,membershipVersion:input.authorization.membershipVersion,tenantVersion:"resolved",priorStateVersion:priorVersion,newStateVersion:newVersion,allow:true});fail("audit_write");tx.create(commandRef,{schemaVersion:"evidence-review-command-idempotency.v1",commandFingerprint:input.commandFingerprint,receipt,expiresAfterDays:30,createdAt:input.persistedAt});fail("idempotency_write");return receipt})}
})}
