import { AUTHORIZATION_DECISION_V1, AUTHORIZATION_PERMISSION_VERSION, AUTHORIZATION_POLICY_VERSION, AUTHORIZATION_REQUEST_V1, RESOLVED_RESOURCE_FACTS_V1, parseAuthorizationDecision, parseAuthorizationRequest, parseResolvedResourceFacts, type AuthorizationContextV1, type AuthorizationDecisionV1, type AuthorizationDenialReason, type AuthorizationPermission } from "../../contracts/authorization";
import { createAuthorizationAuditEvent, type AuthorizationAuditEventV1 } from "../../contracts/authorizationAudit";
import type { ResolvedApplicationDocumentResourceFactsV1 } from "../../contracts/applicationDocumentResourceFacts";
import { toResolvedResourceFacts, type ResolvedApplicationResourceFactsV1 } from "../../contracts/applicationResourceFacts";
import { parseServerAuthContext } from "../../contracts/serverAuth";
import type { ApplicationResourceResolutionResult } from "./applicationResourceResolverCore";
import type { ApplicationDocumentResourceResult } from "./applicationDocumentResourceResolverCore";
import { applicationPolicyForPermission } from "./applicationActionPolicies";
import { applicationDocumentPolicyForPermission, type ApplicationDocumentActionPolicyV1 } from "./applicationDocumentActionPolicies";
import type { AuthorizationDecisionResult } from "./authorizationDecisionCore";
import type { TenantAuthorizationResolverResult } from "./tenantAuthorizationResolverCore";

export type DocumentAuthorizationPublicCode = "RESOURCE_NOT_AVAILABLE" | "FORBIDDEN" | "AUTHORIZATION_REQUIRED" | "TENANT_SELECTION_REQUIRED" | "INTERNAL_ERROR";
export type ApplicationDocumentAuthorizationAuditPlanV1 = Readonly<{ event: AuthorizationAuditEventV1; documentPermission: ApplicationDocumentActionPolicyV1["permission"]; parentApplicationPermission: ApplicationDocumentActionPolicyV1["parentApplicationPermission"]; applicationResourceAuthorizationVersion?: string; documentAuthorizationVersion?: string; auditClassification: AuthorizationAuditEventV1["classification"] }>;
export type ApplicationDocumentAuthorizationResult = Readonly<{ ok:true; context:AuthorizationContextV1; applicationFacts:ResolvedApplicationResourceFactsV1; documentFacts:ResolvedApplicationDocumentResourceFactsV1; decision:AuthorizationDecisionV1 & {decision:"allow"}; auditPlan:ApplicationDocumentAuthorizationAuditPlanV1 }> | Readonly<{ok:false;code:string;internalReason:string;publicError:Readonly<{code:DocumentAuthorizationPublicCode;status:401|403|404|500;message:string}>;auditPlan?:ApplicationDocumentAuthorizationAuditPlanV1}>;
export type AuthorizeApplicationDocumentActionInput = Readonly<{ authentication:unknown; requestedTenantId?:unknown; applicationId:unknown; documentId:unknown; permission:unknown; policy:unknown; evaluatedAt:string }>;
export type ApplicationDocumentAuthorizationDependencies = Readonly<{resolveTenant(i:any):Promise<TenantAuthorizationResolverResult>;resolveApplication(i:any):Promise<ApplicationResourceResolutionResult>;resolveDocument(i:any):Promise<ApplicationDocumentResourceResult>;evaluateDecision(i:any):AuthorizationDecisionResult;onStep?:(step:string)=>void}>;
const PUBLIC={AUTHORIZATION_REQUIRED:{code:"AUTHORIZATION_REQUIRED",status:401,message:"Authentication is required."},FORBIDDEN:{code:"FORBIDDEN",status:403,message:"The requested action is not available."},TENANT_SELECTION_REQUIRED:{code:"TENANT_SELECTION_REQUIRED",status:403,message:"A tenant selection is required."},RESOURCE_NOT_AVAILABLE:{code:"RESOURCE_NOT_AVAILABLE",status:404,message:"The requested resource is not available."},INTERNAL_ERROR:{code:"INTERNAL_ERROR",status:500,message:"Authorization could not be completed."}} as const;
const failure=(code:string,internalReason:string,p:keyof typeof PUBLIC,auditPlan?:ApplicationDocumentAuthorizationAuditPlanV1):ApplicationDocumentAuthorizationResult=>Object.freeze({ok:false,code,internalReason,publicError:PUBLIC[p],...(auditPlan?{auditPlan}:{})});
export const normalizeApplicationDocumentAuthorizationError=(r:Extract<ApplicationDocumentAuthorizationResult,{ok:false}>)=>r.publicError;
const request=(permission:any,resourceType:"application"|"application_document",resourceId:string,action:string,constraints:readonly any[],auth:any)=>parseAuthorizationRequest({schemaVersion:AUTHORIZATION_REQUEST_V1,permission,resourceType,resourceId,action:{auditAction:action,requiredConstraints:constraints},requestId:auth.requestId,correlationId:auth.correlationId,policyVersion:AUTHORIZATION_POLICY_VERSION});
const auditClassification=(reason:string):AuthorizationAuditEventV1["classification"]=>reason==="permission_missing"?"permission_denied":reason.includes("tenant")||reason.includes("membership")?"tenant_denied":reason==="policy_invalid"||reason==="internal_error"?"policy_failure":"resource_denied";
function denialAuditPlan(auth:any,context:AuthorizationContextV1,policy:ApplicationDocumentActionPolicyV1,documentId:unknown,evaluatedAt:string,reason:AuthorizationDenialReason,applicationResourceAuthorizationVersion?:string,documentAuthorizationVersion?:string):ApplicationDocumentAuthorizationAuditPlanV1|undefined{
 const resourceId=typeof documentId==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(documentId)?documentId:undefined;
 const parsed=parseAuthorizationDecision({schemaVersion:AUTHORIZATION_DECISION_V1,decision:"deny",permission:policy.permission as AuthorizationPermission,principalKind:"firebase_user",tenantId:context.tenantId,resourceType:"application_document",...(resourceId?{resourceId}:{}),reasonCode:reason,policyVersion:AUTHORIZATION_POLICY_VERSION,evaluatedAt,requestId:auth.requestId,correlationId:auth.correlationId,constraintsEvaluated:[],audit:{action:policy.auditAction,outcome:"denied",piiPresent:false}});if(!parsed.ok)return undefined;
 const classification=auditClassification(reason),built=createAuthorizationAuditEvent({eventId:`docauth:${auth.requestId}:${policy.permission.replace(".",":")}`,principalReference:context.authentication.principalId,decision:parsed.value,membershipVersion:context.membershipVersion,tenantVersion:context.tenantVersion,permissionVersion:context.permissionVersion,...(documentAuthorizationVersion?{resourceAuthorizationVersion:documentAuthorizationVersion}:{}),classification});if(!built.ok)return undefined;
 return Object.freeze({event:built.value,documentPermission:policy.permission,parentApplicationPermission:policy.parentApplicationPermission,...(applicationResourceAuthorizationVersion?{applicationResourceAuthorizationVersion}:{}),...(documentAuthorizationVersion?{documentAuthorizationVersion}:{}),auditClassification:classification});
}
export async function authorizeApplicationDocumentActionCore(input:AuthorizeApplicationDocumentActionInput,d:ApplicationDocumentAuthorizationDependencies):Promise<ApplicationDocumentAuthorizationResult>{
 d.onStep?.("validate_authentication");const auth=parseServerAuthContext(input.authentication);if(!auth.ok||auth.value.principal.kind!=="firebase_user")return failure("AUTH_INVALID","authentication_required","AUTHORIZATION_REQUIRED");
 const policy=input.policy as ApplicationDocumentActionPolicyV1,canonical=applicationDocumentPolicyForPermission(input.permission);if(!canonical||!policy||JSON.stringify(policy)!==JSON.stringify(canonical))return failure("POLICY_INVALID","policy_invalid","FORBIDDEN");
 d.onStep?.("resolve_tenant");const tenant=await d.resolveTenant({authentication:auth.value,...(input.requestedTenantId!==undefined?{requestedTenantId:input.requestedTenantId}:{})});if(!tenant.ok)return failure("TENANT_RESOLUTION_FAILED",tenant.error.code,tenant.error.code==="TENANT_SELECTION_REQUIRED"?"TENANT_SELECTION_REQUIRED":tenant.error.code==="INTERNAL_ERROR"?"INTERNAL_ERROR":"FORBIDDEN");const context=tenant.context;
 d.onStep?.("resolve_application");const app=await d.resolveApplication({applicationId:input.applicationId,requestId:auth.value.requestId,correlationId:auth.value.correlationId});if(!app.ok){const reason:AuthorizationDenialReason=app.error.code==="DEPENDENCY_FAILURE"?"internal_error":app.error.code.includes("OWNERSHIP")?"unresolved_legacy":"resource_not_found";return failure("APPLICATION_RESOLUTION_FAILED",app.error.code,app.error.code==="DEPENDENCY_FAILURE"?"INTERNAL_ERROR":"RESOURCE_NOT_AVAILABLE",denialAuditPlan(auth.value,context,policy,input.documentId,input.evaluatedAt,reason));}
 d.onStep?.("resolve_document");const doc=await d.resolveDocument({applicationId:app.facts.applicationId,documentId:input.documentId,requestedTenantId:context.tenantId,requestId:auth.value.requestId,correlationId:auth.value.correlationId});if(!doc.ok){const reason:AuthorizationDenialReason=doc.error.code==="DEPENDENCY_FAILURE"?"internal_error":doc.error.code.includes("OWNERSHIP")?"unresolved_legacy":"resource_not_found";return failure("DOCUMENT_RESOLUTION_FAILED",doc.error.code,doc.error.code==="DEPENDENCY_FAILURE"?"INTERNAL_ERROR":"RESOURCE_NOT_AVAILABLE",denialAuditPlan(auth.value,context,policy,input.documentId,input.evaluatedAt,reason,app.facts.resourceAuthorizationVersion));}
 d.onStep?.("verify_relationship");if(doc.facts.applicationId!==app.facts.applicationId)return failure("RELATIONSHIP_MISMATCH","document_application_mismatch","RESOURCE_NOT_AVAILABLE",denialAuditPlan(auth.value,context,policy,doc.facts.documentId,input.evaluatedAt,"resource_not_found",app.facts.resourceAuthorizationVersion,doc.facts.documentAuthorizationVersion));d.onStep?.("verify_tenant_equality");if(!app.facts.tenantId||doc.facts.tenantId!==app.facts.tenantId||app.facts.tenantId!==context.tenantId)return failure("TENANT_MISMATCH","resource_tenant_mismatch","RESOURCE_NOT_AVAILABLE",denialAuditPlan(auth.value,context,policy,doc.facts.documentId,input.evaluatedAt,"resource_tenant_mismatch",app.facts.resourceAuthorizationVersion,doc.facts.documentAuthorizationVersion));
 d.onStep?.("authorize_parent_application");const pp=applicationPolicyForPermission(policy.parentApplicationPermission)!,pr=request(pp.permission,"application",app.facts.applicationId,`parent.${pp.auditAction}`,pp.requiredConstraints,auth.value);if(!pr.ok)return failure("POLICY_INVALID","policy_invalid","INTERNAL_ERROR");const parent=d.evaluateDecision({context,request:pr.value,resourceFacts:toResolvedResourceFacts(app.facts),evaluatedAt:input.evaluatedAt});if(!parent.ok)return failure("PARENT_DECISION_INVALID","internal_error","INTERNAL_ERROR");if(parent.decision.decision!=="allow")return failure("PARENT_APPLICATION_DENIED",parent.decision.reasonCode,"FORBIDDEN",denialAuditPlan(auth.value,context,policy,doc.facts.documentId,input.evaluatedAt,parent.decision.reasonCode as AuthorizationDenialReason,app.facts.resourceAuthorizationVersion,doc.facts.documentAuthorizationVersion));
 d.onStep?.("convert_document_resource_facts");const rf=parseResolvedResourceFacts({schemaVersion:RESOLVED_RESOURCE_FACTS_V1,resourceType:"application_document",resourceId:doc.facts.documentId,tenantId:doc.facts.tenantId,...(app.facts.branchId?{branchId:app.facts.branchId}:{}),teamIds:app.facts.teamIds,assignedUserIds:[app.facts.assignedProcessorId,app.facts.assignedUnderwriterId].filter(Boolean),assignedTeamIds:[],...(doc.facts.createdBy?{creatorId:doc.facts.createdBy}:{}),legacyState:doc.facts.ownershipState,resourceStatus:doc.facts.documentStatus,applicationDocumentRelationshipVerified:true});if(!rf.ok)return failure("RESOURCE_FACTS_INVALID","internal_error","INTERNAL_ERROR");
 d.onStep?.("build_request");const rq=request(policy.permission,"application_document",doc.facts.documentId,policy.auditAction,policy.requiredConstraints,auth.value);if(!rq.ok)return failure("POLICY_INVALID","policy_invalid","INTERNAL_ERROR");d.onStep?.("evaluate_decision");const evaluated=d.evaluateDecision({context,request:rq.value,resourceFacts:rf.value,evaluatedAt:input.evaluatedAt});if(!evaluated.ok)return failure("DECISION_INVALID","internal_error","INTERNAL_ERROR");
 d.onStep?.("build_audit_plan");const classification=evaluated.decision.decision==="allow"?"access_allowed":evaluated.decision.reasonCode==="permission_missing"?"permission_denied":"resource_denied";const event=createAuthorizationAuditEvent({eventId:`docauth:${auth.value.requestId}:${policy.permission.replace(".",":")}`,principalReference:context.authentication.principalId,decision:evaluated.decision,membershipVersion:context.membershipVersion,tenantVersion:context.tenantVersion,permissionVersion:AUTHORIZATION_PERMISSION_VERSION,resourceAuthorizationVersion:doc.facts.documentAuthorizationVersion,classification});if(!event.ok)return failure("AUDIT_PLAN_INVALID","internal_error","INTERNAL_ERROR");const auditPlan=Object.freeze({event:event.value,documentPermission:policy.permission,parentApplicationPermission:policy.parentApplicationPermission,applicationResourceAuthorizationVersion:app.facts.resourceAuthorizationVersion,documentAuthorizationVersion:doc.facts.documentAuthorizationVersion,auditClassification:event.value.classification});if(evaluated.decision.decision!=="allow")return failure("DECISION_DENIED",evaluated.decision.reasonCode,evaluated.decision.reasonCode==="resource_tenant_mismatch"||evaluated.decision.reasonCode==="unresolved_legacy"?"RESOURCE_NOT_AVAILABLE":"FORBIDDEN",auditPlan);
 return Object.freeze({ok:true,context,applicationFacts:app.facts,documentFacts:doc.facts,decision:evaluated.decision as AuthorizationDecisionV1&{decision:"allow"},auditPlan});
}
