import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { FieldPath, getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { defaultAdminApp } from "../auth/firebaseAdminAuthAdapter";
import type { LegacyInventoryCandidateV1, LegacyResourceType } from "../../contracts/legacyOwnership";
import { runLegacyOwnershipInventory } from "./legacyOwnershipInventoryCore";

const MAX=100;
export const LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY=Object.freeze([
  "applications/{applicationId}","applicationDocuments/{documentId}","applications/{applicationId}.storedDocs[]","applications/{applicationId}/analysisState/current","applications/{applicationId}/analysisCommands/{commandId}","applications/{applicationId}/reports/{reportId}","applications/{applicationId}/workflowCommands/{commandId}","applications/{applicationId}/decisionState/current","applications/{applicationId}/decisionHistory/{decisionId}","applications/{applicationId}/evidenceAggregations/{aggregationId}","applications/{applicationId}/evidenceReviews/{reviewId}","tenants/{tenantId}/**/*Audit*","tenants/{tenantId}/**/*Commands*","applications/{applicationId}/...storage","tenants/{tenantId}/applications/{applicationId}/...storage"
]);
const clean=(x:any)=>typeof x==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(x)?x:undefined;
const cursorSecret=()=>{const value=process.env.LEGACY_OWNERSHIP_CURSOR_SECRET||(process.env.GCLOUD_PROJECT?.startsWith("demo-")?"demo-legacy-ownership-cursor-secret-0001":"");if(value.length<32)throw Error("LEGACY_OWNERSHIP_CURSOR_SECRET_REQUIRED");return value},encodeCursor=(applicationId:string)=>{const payload=Buffer.from(JSON.stringify({applicationId,version:1})).toString("base64url"),signature=createHmac("sha256",cursorSecret()).update(payload).digest("base64url");return `${payload}.${signature}`},decodeCursor=(value?:string)=>{if(!value)return;const[payload,signature,...extra]=value.split(".");if(!payload||!signature||extra.length)throw Error("INVALID_LEGACY_OWNERSHIP_CURSOR");const expected=createHmac("sha256",cursorSecret()).update(payload).digest(),actual=Buffer.from(signature,"base64url");if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw Error("INVALID_LEGACY_OWNERSHIP_CURSOR");const parsed=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));if(parsed.version!==1||!clean(parsed.applicationId))throw Error("INVALID_LEGACY_OWNERSHIP_CURSOR");return parsed.applicationId as string};
export async function inventoryLegacyOwnership(input:Readonly<{requestId:string;correlationId:string;pageSize?:number;continuationCursor?:string}>){
  const size=Math.min(MAX,Math.max(1,input.pageSize||25)),startAfterApplicationId=decodeCursor(input.continuationCursor),db=getFirestore(defaultAdminApp());let query:any=db.collection("applications").orderBy(FieldPath.documentId()).limit(size+1);if(startAfterApplicationId)query=query.startAfter(startAfterApplicationId);const snaps=await query.get(),docs=snaps.docs.slice(0,size),candidates:LegacyInventoryCandidateV1[]=[];
  const discoveredDocuments=new Set<string>();
  for(const appSnap of docs){const a=appSnap.data(),tenantId=clean(a.tenantId);candidates.push({resourceType:"application",resourceId:appSnap.id,tenantId,ownershipState:a.ownershipState,authorizationVersion:clean(a.authorizationVersion),workflowVersion:clean(a.workflowVersion),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[0],malformed:!!a.tenantId&&!tenantId});
    const children=await db.collection("applicationDocuments").where("applicationId","==",appSnap.id).limit(20).get();for(const dSnap of children.docs){discoveredDocuments.add(dSnap.id);const d=dSnap.data();candidates.push({resourceType:"application_document",resourceId:dSnap.id,applicationId:appSnap.id,documentId:dSnap.id,tenantId:clean(d.tenantId),ownershipState:d.ownershipState,authorizationVersion:clean(d.authorizationVersion),parentTenantId:tenantId,storageMetadataTenantId:clean(d.storageMetadataTenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[1],malformed:!!d.tenantId&&!clean(d.tenantId)})}
    if(Array.isArray(a.storedDocs))for(let i=0;i<Math.min(a.storedDocs.length,10);i++)candidates.push({resourceType:"legacy_document_metadata",resourceId:`${appSnap.id}:stored:${i}`,applicationId:appSnap.id,parentTenantId:tenantId,sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[2]});
    for(const [resourceType,collection,document,pattern]of [["analysis","analysisState","current",3],["report","reportState","current",5],["workflow","workflowState","current",6],["decision","decisionState","current",7],["evidence","evidenceAggregation","current",9]]as const){const s=await appSnap.ref.collection(collection).doc(document).get();if(s.exists){const x=s.data()!;candidates.push({resourceType:resourceType as LegacyResourceType,resourceId:`${appSnap.id}:${collection}:${document}`,applicationId:appSnap.id,tenantId:clean(x.tenantId),parentTenantId:tenantId,lineageTenantIds:[clean(x.tenantId)].filter(Boolean) as string[],sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[pattern]})}}
    const bucket=getStorage(defaultAdminApp()).bucket(),[files]=await bucket.getFiles({prefix:`applications/${appSnap.id}/`,maxResults:10});for(const file of files)candidates.push({resourceType:"storage_object",resourceId:`${appSnap.id}:object:${file.metadata.generation||"unknown"}`,applicationId:appSnap.id,parentTenantId:tenantId,storageMetadataTenantId:clean(file.metadata.metadata?.tenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[13]});if(tenantId){const[canonical]=await bucket.getFiles({prefix:`tenants/${tenantId}/applications/${appSnap.id}/`,maxResults:10});for(const file of canonical)candidates.push({resourceType:"storage_object",resourceId:`${appSnap.id}:canonical:${file.metadata.generation||"unknown"}`,applicationId:appSnap.id,parentTenantId:tenantId,storageMetadataTenantId:clean(file.metadata.metadata?.tenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[14]})}
  }
  const allDocuments=await db.collection("applicationDocuments").orderBy(FieldPath.documentId()).limit(size).get();for(const dSnap of allDocuments.docs)if(!discoveredDocuments.has(dSnap.id)){const d=dSnap.data(),parent=clean(d.applicationId)?await db.doc(`applications/${d.applicationId}`).get():undefined,parentTenant=parent?.exists?clean(parent.data()?.tenantId):undefined;candidates.push({resourceType:"application_document",resourceId:dSnap.id,applicationId:clean(d.applicationId),documentId:dSnap.id,tenantId:clean(d.tenantId),ownershipState:d.ownershipState,authorizationVersion:clean(d.authorizationVersion),parentTenantId:parentTenant,storageMetadataTenantId:clean(d.storageMetadataTenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[1],orphaned:!parent?.exists,malformed:!!d.applicationId&&!clean(d.applicationId)})}
  const result=runLegacyOwnershipInventory({candidates:candidates.slice(0,MAX),requestId:input.requestId,correlationId:input.correlationId,batchSeed:startAfterApplicationId||"first",hasMore:false}),hasMore=snaps.docs.length>size,last=docs.at(-1)?.id;
  return Object.freeze({receipt:Object.freeze({...result.receipt,continuationCursor:hasMore&&last?encodeCursor(last):null})});
}
