import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { FieldPath, getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { defaultAdminApp } from "../auth/firebaseAdminAuthAdapter";
import type { LegacyInventoryCandidateV1, LegacyResourceType } from "../../contracts/legacyOwnership";
import { PLATFORM_LEGACY_INVENTORY_RESOURCE_CLASSES, type PlatformLegacyInventoryResourceClass } from "../../contracts/platformLegacyInventory";
import { runLegacyOwnershipInventory } from "./legacyOwnershipInventoryCore";

const MAX=100;
export const LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY=Object.freeze([
  "applications/{applicationId}","applicationDocuments/{documentId}","applications/{applicationId}.storedDocs[]","applications/{applicationId}/analysisState/current","applications/{applicationId}/analysisCommands/{commandId}","applications/{applicationId}/reports/{reportId}","applications/{applicationId}/workflowCommands/{commandId}","applications/{applicationId}/decisionState/current","applications/{applicationId}/decisionHistory/{decisionId}","applications/{applicationId}/evidenceAggregations/{aggregationId}","applications/{applicationId}/evidenceReviews/{reviewId}","tenants/{tenantId}/**/*Audit*","tenants/{tenantId}/**/*Commands*","applications/{applicationId}/...storage","tenants/{tenantId}/applications/{applicationId}/...storage"
]);
const clean=(x:any)=>typeof x==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(x)?x:undefined;
const cursorSecret=()=>{const value=process.env.LEGACY_OWNERSHIP_CURSOR_SECRET||(process.env.GCLOUD_PROJECT?.startsWith("demo-")?"demo-legacy-ownership-cursor-secret-0001":"");if(value.length<32)throw Error("LEGACY_OWNERSHIP_CURSOR_SECRET_REQUIRED");return value},encodeCursor=(applicationId:string)=>{const payload=Buffer.from(JSON.stringify({applicationId,version:1})).toString("base64url"),signature=createHmac("sha256",cursorSecret())["update"](payload).digest("base64url");return `${payload}.${signature}`},decodeCursor=(value?:string)=>{if(!value)return;const[payload,signature,...extra]=value.split(".");if(!payload||!signature||extra.length)throw Error("INVALID_LEGACY_OWNERSHIP_CURSOR");const expected=createHmac("sha256",cursorSecret())["update"](payload).digest(),actual=Buffer.from(signature,"base64url");if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw Error("INVALID_LEGACY_OWNERSHIP_CURSOR");const parsed=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));if(parsed.version!==1||!clean(parsed.applicationId))throw Error("INVALID_LEGACY_OWNERSHIP_CURSOR");return parsed.applicationId as string};
export async function inventoryLegacyOwnership(input:Readonly<{requestId:string;correlationId:string;pageSize?:number;continuationCursor?:string;includeResourceClasses?:readonly PlatformLegacyInventoryResourceClass[];dependencyCallCounters?:Partial<Record<PlatformLegacyInventoryResourceClass,number>>}>){
  const bump=(name:PlatformLegacyInventoryResourceClass)=>{if(input.dependencyCallCounters)input.dependencyCallCounters[name]=(input.dependencyCallCounters[name]||0)+1};
  const size=Math.min(MAX,Math.max(1,input.pageSize||25)),classes=new Set(input.includeResourceClasses||PLATFORM_LEGACY_INVENTORY_RESOURCE_CLASSES),startAfterApplicationId=decodeCursor(input.continuationCursor),db=getFirestore(defaultAdminApp()),needsApplicationScan=[...classes].some(x=>x!=="application_documents");let docs:any[]=[];let hasMore=false;if(needsApplicationScan){for(const selected of classes)if(selected!=="application_documents")bump(selected);let query:any=db.collection("applications").orderBy(FieldPath.documentId()).limit(size+1);if(startAfterApplicationId)query=query.startAfter(startAfterApplicationId);const snapshot=await query.get();docs=snapshot.docs.slice(0,size);hasMore=snapshot.docs.length>size}const candidates:LegacyInventoryCandidateV1[]=[];
  const discoveredDocuments=new Set<string>();
  for(const appSnap of docs){const a=appSnap.data(),tenantId=clean(a.tenantId);if(classes.has("applications"))candidates.push({resourceType:"application",resourceId:appSnap.id,tenantId,ownershipState:a.ownershipState,authorizationVersion:clean(a.authorizationVersion),workflowVersion:clean(a.workflowVersion),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[0],malformed:!!a.tenantId&&!tenantId});
    if(classes.has("legacy_application_metadata")&&Array.isArray(a.storedDocs))for(let i=0;i<Math.min(a.storedDocs.length,10);i++)candidates.push({resourceType:"legacy_document_metadata",resourceId:`${appSnap.id}:stored:${i}`,applicationId:appSnap.id,parentTenantId:tenantId,sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[2]});
    for(const [className,resourceType,collection,document,pattern]of [["analysis","analysis","analysisState","current",3],["reports","report","reportState","current",5],["workflow","workflow","workflowState","current",6],["decisions","decision","decisionState","current",7],["evidence","evidence","evidenceAggregation","current",9]]as const)if(classes.has(className)){const s=await appSnap.ref.collection(collection).doc(document).get();if(s.exists){const x=s.data()!;candidates.push({resourceType:resourceType as LegacyResourceType,resourceId:`${appSnap.id}:${collection}:${document}`,applicationId:appSnap.id,tenantId:clean(x.tenantId),parentTenantId:tenantId,lineageTenantIds:[clean(x.tenantId)].filter(Boolean) as string[],sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[pattern]})}}
    const bucket=getStorage(defaultAdminApp()).bucket();if(classes.has("legacy_storage_metadata")){const[files]=await bucket.getFiles({prefix:`applications/${appSnap.id}/`,maxResults:10});for(const file of files)candidates.push({resourceType:"storage_object",resourceId:`${appSnap.id}:object:${file.metadata.generation||"unknown"}`,applicationId:appSnap.id,parentTenantId:tenantId,storageMetadataTenantId:clean(file.metadata.metadata?.tenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[13]})}if(classes.has("canonical_storage_metadata")&&tenantId){const[canonical]=await bucket.getFiles({prefix:`tenants/${tenantId}/applications/${appSnap.id}/`,maxResults:10});for(const file of canonical)candidates.push({resourceType:"storage_object",resourceId:`${appSnap.id}:canonical:${file.metadata.generation||"unknown"}`,applicationId:appSnap.id,parentTenantId:tenantId,storageMetadataTenantId:clean(file.metadata.metadata?.tenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[14]})}
  }
  if(classes.has("application_documents")){bump("application_documents");const parents=new Map(docs.map(s=>[s.id,clean(s.data().tenantId)]));const allDocuments=await db.collection("applicationDocuments").orderBy(FieldPath.documentId()).limit(size).get();for(const dSnap of allDocuments.docs)if(!discoveredDocuments.has(dSnap.id)){const d=dSnap.data(),applicationId=clean(d.applicationId),parentKnown=!!applicationId&&parents.has(applicationId),parentTenantId=applicationId?parents.get(applicationId):undefined;candidates.push({resourceType:"application_document",resourceId:dSnap.id,applicationId,documentId:dSnap.id,tenantId:clean(d.tenantId),ownershipState:d.ownershipState,authorizationVersion:clean(d.authorizationVersion),parentTenantId,storageMetadataTenantId:clean(d.storageMetadataTenantId),sourcePattern:LEGACY_OWNERSHIP_PERSISTED_SHAPE_INVENTORY[1],orphaned:needsApplicationScan&&!parentKnown,malformed:!!d.applicationId&&!applicationId})}}
  const result=runLegacyOwnershipInventory({candidates:candidates.slice(0,MAX),requestId:input.requestId,correlationId:input.correlationId,batchSeed:`${startAfterApplicationId||"first"}:${[...classes].sort().join(",")}`,hasMore:false}),last=docs.at(-1)?.id;
  return Object.freeze({receipt:Object.freeze({...result.receipt,continuationCursor:hasMore&&last?encodeCursor(last):null})});
}
