import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { applicationResourceFixtures as f } from "../lib/contracts/applicationResourceFixtures";
import { parseResolvedApplicationResourceFacts, toResolvedResourceFacts } from "../lib/contracts/applicationResourceFacts";
import { resolveApplicationResourceFactsCore } from "../lib/server/authorization/applicationResourceResolverCore";

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)); const at = () => new Date("2026-01-01T00:00:00.000Z");
const resolve = (record: unknown, applicationId = (record as any)?.applicationId ?? "application_alpha") => resolveApplicationResourceFactsCore({ applicationId }, { getApplicationById: async () => ({ exists: true, data: record }) }, at);
let count = 0; const test = async (name: string, fn: () => unknown | Promise<unknown>) => { await fn(); count++; console.log(`PASS ${count}: ${name}`); };

async function main() {
await test("tenant-owned facts are deterministic, immutable, valid, compatible, and PII-free", async () => { const input = clone(f.tenantOwned); const before = JSON.stringify(input); const a = await resolve(input), b = await resolve(clone(input)); assert(a.ok && b.ok); assert.deepEqual(a.facts, b.facts); assert.equal(JSON.stringify(input), before); assert(parseResolvedApplicationResourceFacts(a.facts).ok); assert.equal(toResolvedResourceFacts(a.facts).resourceId, "application_alpha"); assert(Object.isFrozen(a.facts) && Object.isFrozen(a.facts.teamIds) && Object.isFrozen(a.facts.provenance)); const text = JSON.stringify(a.facts); for (const forbidden of ["borrowerName", "email", "loanAmount", "Synthetic Borrower", "synthetic@example.invalid"]) assert(!text.includes(forbidden)); });
await test("legacy, pending, and rejected ownership fail closed without inference", async () => { const legacy = await resolve(f.unresolved), pending = await resolve(f.pending), rejected = await resolve(f.rejected); assert(legacy.ok && legacy.facts.ownershipState === "unresolved_legacy" && !legacy.facts.tenantId); assert(pending.ok && pending.facts.ownershipState === "migration_pending" && !pending.facts.tenantId); assert(!rejected.ok && rejected.error.code === "APPLICATION_OWNERSHIP_REJECTED"); });
await test("assignments, branch, teams, missing optionals, duplicate teams, and unknown status normalize", async () => { const full = await resolve(f.tenantOwned), dup = await resolve(f.duplicateTeams), unknown = await resolve(f.unknownStatus); assert(full.ok && full.facts.assignedUnderwriterId && full.facts.assignedProcessorId && full.facts.branchId); assert(dup.ok && dup.facts.teamIds.join(",") === "team_alpha,team_beta" && dup.facts.warnings.includes("duplicate_team_ids_normalized")); assert(unknown.ok && unknown.facts.applicationStatus === "unknown"); });
await test("missing, malformed ID, malformed ownership/tenant/version, and dependency failure map stably", async () => { const missing = await resolveApplicationResourceFactsCore({ applicationId: "application_missing" }, { getApplicationById: async () => ({ exists: false }) }, at); const badId = await resolveApplicationResourceFactsCore({ applicationId: "bad/id" }, { getApplicationById: async () => ({ exists: false }) }, at); const tenant = await resolve(f.malformedTenant), contradictory = await resolve(f.contradictory), version = await resolve(f.malformedVersion); const dependency = await resolveApplicationResourceFactsCore({ applicationId: "application_alpha" }, { getApplicationById: async () => { throw new Error("raw firestore pii"); } }, at); assert(!missing.ok && missing.error.code === "APPLICATION_NOT_FOUND"); assert(!badId.ok && badId.error.code === "APPLICATION_ID_INVALID"); assert(!tenant.ok && tenant.error.code === "APPLICATION_TENANT_INVALID"); assert(!contradictory.ok && contradictory.error.code === "APPLICATION_MALFORMED"); assert(!version.ok && version.error.code === "APPLICATION_VERSION_INVALID"); assert(!dependency.ok && dependency.error.code === "DEPENDENCY_FAILURE" && !JSON.stringify(dependency).includes("firestore")); });
await test("authorization version changes only from authorization-relevant source facts", async () => { const a = await resolve(f.tenantOwned), b = await resolve({ ...f.tenantOwned, authorizationVersion: "auth-v2" }), pii = await resolve({ ...f.tenantOwned, borrowerName: "Different Synthetic Name" }); assert(a.ok && b.ok && pii.ok); assert.notEqual(a.facts.resourceAuthorizationVersion, b.facts.resourceAuthorizationVersion); assert.equal(a.facts.resourceAuthorizationVersion, pii.facts.resourceAuthorizationVersion); });
await test("contract rejects malformed values and resolver makes no permission decision", async () => { assert(!parseResolvedApplicationResourceFacts({}).ok); const result = await resolve(f.tenantOwned); assert(result.ok && !("decision" in result.facts) && !("permission" in result.facts)); });
await test("no production route or page imports resolver", () => { const root = process.cwd(); for (const dir of ["app/api", "app"]) { const files: string[] = []; const walk = (p: string) => fs.readdirSync(p, { withFileTypes: true }).forEach((e) => { const next = path.join(p, e.name); if (e.isDirectory()) walk(next); else if (/\.(ts|tsx)$/.test(e.name)) files.push(next); }); walk(path.join(root, dir)); for (const file of new Set(files)) assert(!fs.readFileSync(file, "utf8").includes("applicationResourceResolver"), `${file} imports resolver`); } });
console.log(`Application resource resolver deterministic regression: ${count}/${count} passed`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
