import assert from "node:assert/strict";
import {DEFAULT_APPROVAL_POLICY,ENTERPRISE_FEATURES,FEATURE_FLAG_VERSION,GOVERNANCE_POLICY_VERSION,GOVERNANCE_ROLE_REGISTRY,PERMISSION_REGISTRY,TEAM_VERSION,evaluateApprovalAuthority,evaluateFeature,permissionsForGovernanceRole,resolveGovernanceRole,routeTeam,type GovernanceTeam} from "../lib/governance/enterpriseGovernance";
import {permissionsForRole} from "../lib/server/authorization/permissionPolicy";

assert.ok(PERMISSION_REGISTRY.length>30);
assert.equal(new Set(PERMISSION_REGISTRY.map(x=>x.permission)).size,PERMISSION_REGISTRY.length);
assert.ok(PERMISSION_REGISTRY.some(x=>x.permission==="application.read"));
assert.ok(PERMISSION_REGISTRY.some(x=>x.permission==="decision.approve"));
assert.ok(PERMISSION_REGISTRY.some(x=>x.permission==="membership.manage"));
assert.equal(resolveGovernanceRole("underwriter").ok,true);
assert.equal(resolveGovernanceRole("fabricated").ok,false);
assert.equal(GOVERNANCE_ROLE_REGISTRY.viewer.approvalAuthority,"none");
assert.equal(GOVERNANCE_ROLE_REGISTRY.underwriter.permissions.includes("decision.approve"),true);
assert.equal(GOVERNANCE_ROLE_REGISTRY.processor.permissions.includes("decision.approve"),false);
assert.deepEqual(permissionsForRole("underwriter"),permissionsForGovernanceRole("underwriter"),"production authorization consumes centralized registry");
assert.deepEqual(permissionsForRole("owner"),permissionsForGovernanceRole("owner"));
assert.equal(permissionsForRole("unknown").length,0);
assert.equal(permissionsForRole("viewer").includes("configuration.manage"),false);
assert.equal(evaluateApprovalAuthority({role:"underwriter",action:"approve",policy:DEFAULT_APPROVAL_POLICY}).allowed,true);
assert.equal(evaluateApprovalAuthority({role:"processor",action:"approve",policy:DEFAULT_APPROVAL_POLICY}).reason,"permission_missing");
assert.equal(evaluateApprovalAuthority({role:"underwriter",action:"deny",policy:DEFAULT_APPROVAL_POLICY}).allowed,true);
assert.equal(evaluateApprovalAuthority({role:"unknown",action:"deny",policy:DEFAULT_APPROVAL_POLICY}).allowed,false);
assert.equal(evaluateApprovalAuthority({role:"underwriter",action:"approve"}).reason,"policy_unavailable");
const escalation={...DEFAULT_APPROVAL_POLICY,requireEscalationAbove:500000};
assert.equal(evaluateApprovalAuthority({role:"underwriter",action:"approve",loanAmount:600000,policy:escalation}).reason,"escalation_required");
assert.equal(evaluateApprovalAuthority({role:"underwriter",action:"approve",loanAmount:400000,policy:escalation}).allowed,true);
assert.equal(evaluateFeature({feature:"underwriter_workspace"}).enabled,true,"absent flags preserve existing features");
assert.equal(evaluateFeature({feature:"underwriter_workspace",organizationFlags:{underwriter_workspace:false}}).enabled,false);
assert.equal(evaluateFeature({feature:"underwriter_workspace",organizationFlags:{underwriter_workspace:false},tenantFlags:{underwriter_workspace:true}}).enabled,true);
assert.equal(evaluateFeature({feature:"unknown"}).enabled,false);
assert.ok(ENTERPRISE_FEATURES.includes("change_intelligence"));
assert.equal(FEATURE_FLAG_VERSION,"enterprise-feature-flags.v1");
assert.equal(GOVERNANCE_POLICY_VERSION,"enterprise-governance-policy.v1");
assert.equal(TEAM_VERSION,"enterprise-team.v1");
const team=(id:string,underwriterIds:string[],status:"active"|"archived"="active"):GovernanceTeam=>({schemaVersion:TEAM_VERSION,teamId:id,name:id,status,managerIds:[],memberIds:underwriterIds,underwriterIds,processorIds:[],version:1});
const members=[{userId:"u1",role:"underwriter",membershipStatus:"active",teamIds:["t1"]},{userId:"u2",role:"underwriter",membershipStatus:"inactive",teamIds:["t1"]},{userId:"u3",role:"processor",membershipStatus:"active",teamIds:["t2"]}];
const routed=routeTeam({teams:[team("t2",["u3"]),team("t1",["u1","u2"])],members});
assert.equal(routed.ok,true);
if(routed.ok){assert.equal(routed.teamId,"t1");assert.deepEqual(routed.eligibleUnderwriterIds,["u1"])}
assert.equal(routeTeam({teams:[team("t1",["u1"],"archived")],members}).ok,false);
assert.equal(routeTeam({teams:[team("t1",["u1"])],members,preferredTeamId:"t2"}).ok,false);
assert.equal(Object.isFrozen(PERMISSION_REGISTRY),true);
assert.equal(Object.isFrozen(GOVERNANCE_ROLE_REGISTRY),true);
assert.equal(JSON.stringify(PERMISSION_REGISTRY).includes("borrower"),false);
console.log("PASS enterprise-governance regression (38 assertions)");
