import assert from "node:assert/strict";
import {authorizationVersion,eligibleAssignment,evaluateMembershipAuthority,evaluateMembershipTransition,IDENTITY_LIFECYCLE_VERSION,invitationState,MEMBERSHIP_LIFECYCLE_STATES} from "../lib/identity/lifecycle";
import {parseTenantMembership} from "../lib/contracts/tenantSystem";

const now="2026-07-22T12:00:00.000Z";
assert.deepEqual(MEMBERSHIP_LIFECYCLE_STATES,["invited","pending","active","suspended","disabled","expired","archived"]);
assert.equal(evaluateMembershipTransition("invited","pending").allowed,true);
assert.equal(evaluateMembershipTransition("pending","active").allowed,true);
assert.equal(evaluateMembershipTransition("active","suspended").allowed,true);
assert.equal(evaluateMembershipTransition("suspended","active").allowed,true);
assert.equal(evaluateMembershipTransition("active","disabled").allowed,true);
assert.equal(evaluateMembershipTransition("active","expired").allowed,true);
assert.equal(evaluateMembershipTransition("active","archived").allowed,true);
assert.equal(evaluateMembershipTransition("archived","active").allowed,false);
assert.equal(evaluateMembershipTransition("unknown","active").allowed,false);
assert.equal(evaluateMembershipTransition("invited","active").allowed,false);
const input={tenantId:"tenant1",userId:"user1",membershipVersion:2,role:"underwriter",teamIds:["team2","team1"],managerIds:["manager1"],status:"active"};
const version=authorizationVersion(input);
assert.match(version,/^authority-[a-f0-9]{32}$/);
assert.equal(version,authorizationVersion({...input,teamIds:["team1","team2"]}),"authority identity is deterministic");
assert.notEqual(version,authorizationVersion({...input,membershipVersion:3}));
assert.notEqual(version,authorizationVersion({...input,role:"viewer"}));
assert.notEqual(version,authorizationVersion({...input,status:"suspended"}));
const membership={membershipStatus:"active",membershipVersion:2,authorizationVersion:version,role:"underwriter",teamIds:["team1"],managerIds:["manager1"]};
assert.equal(evaluateMembershipAuthority({membership,now}).allowed,true);
assert.equal(evaluateMembershipAuthority({membership,now,expectedMembershipVersion:1}).reason,"membership_stale");
assert.equal(evaluateMembershipAuthority({membership,now,expectedAuthorizationVersion:"old"}).reason,"authorization_stale");
assert.equal(evaluateMembershipAuthority({membership:{...membership,membershipStatus:"suspended"},now}).allowed,false);
assert.equal(evaluateMembershipAuthority({membership:{...membership,membershipStatus:"archived"},now}).allowed,false);
assert.equal(evaluateMembershipAuthority({membership:{...membership,role:"invented"},now}).reason,"role_unknown");
assert.equal(evaluateMembershipAuthority({now}).reason,"membership_unknown");
assert.equal(evaluateMembershipAuthority({membership:{...membership,expiresAt:"2026-07-21T00:00:00.000Z"},now}).reason,"membership_expired");
assert.equal(invitationState({status:"pending",expiresAt:"2026-07-23T00:00:00.000Z"},now),"pending");
assert.equal(invitationState({status:"pending",expiresAt:"2026-07-21T00:00:00.000Z"},now),"expired");
assert.equal(invitationState({status:"cancelled",expiresAt:"2026-07-23T00:00:00.000Z"},now),"cancelled");
assert.equal(invitationState({status:"accepted",expiresAt:"2026-07-23T00:00:00.000Z"},now),"accepted");
assert.equal(eligibleAssignment({membership,teams:[{teamId:"team1",status:"active"}],now}).eligible,true);
assert.equal(eligibleAssignment({membership,teams:[{teamId:"team1",status:"archived"}],now}).reason,"team_inactive");
assert.equal(eligibleAssignment({membership:{...membership,membershipStatus:"disabled"},teams:[],now}).eligible,false);
const contract=(status:string)=>({schemaVersion:"tenant-membership.v1",tenantId:"tenant1",userId:"user1",role:"underwriter",membershipStatus:status,createdAt:now,createdBy:"admin1",updatedAt:now,compatibility:{migrationStatus:"not_required",warnings:[],legacyFieldNames:[],adapterVersion:"identity-lifecycle-adapter.v1"}});
for(const status of ["invited","pending","active","suspended","disabled","expired","archived"])assert.equal(parseTenantMembership(contract(status)).ok,true,`${status} contract rejected`);
assert.equal(parseTenantMembership(contract("mystery")).ok,true,"unknown legacy state safely adapts");
assert.equal(IDENTITY_LIFECYCLE_VERSION,"enterprise-identity-lifecycle.v1");
assert.equal(JSON.stringify(membership).includes("email"),false);
console.log("PASS identity-lifecycle regression (43 assertions)");
