import assert from "node:assert/strict";
import {buildReviewAgenda,buildUnderwriterWorkspace,UNDERWRITER_WORKSPACE_VERSION} from "../lib/workspace/underwriterWorkspace";

const finding={findingId:"f1",title:"Income conflict",summary:"Paystub and VOE differ.",explanation:"Sources do not agree.",severity:"high",category:"income",disposition:"condition_required",blocking:true,reviewRequired:true,borrowerId:"b1",documents:[{documentId:"d1",pageNumber:1},{documentId:"d2",pageNumber:1}],recommendedAction:"Resolve income conflict.",generatedConditionRef:"c1",ruleId:"MR.INCOME"};
const condition={id:"c1",title:"Verify income",summary:"Obtain acceptable support.",severity:"high",status:"open",blocking:true,owner:"processor",generatedFromFindingId:"f1",requiredActions:["Obtain VOE"]};
const change={changeId:"ch1",category:"income",changeType:"modified",entityId:"monthlyIncome",materiality:"material",favorability:"adverse",reviewRequired:true,blocking:false,explanation:"Income decreased.",recommendedAction:"Re-review qualifying income.",documentReferences:["d1"]};
const agenda=buildReviewAgenda({validationFailures:["Evidence validation failed."],findings:[finding],conditions:[condition],changes:[change]});
assert.equal(agenda[0].type,"integrity");
assert.equal(agenda[1].type,"finding");
assert.equal(agenda.filter(x=>x.conditionId==="c1").length,1,"linked finding and condition are deduplicated");
assert.equal(agenda[1].linked,true);
assert.equal(agenda[1].blocking,true);
assert.equal(agenda[1].documentReferences[0].pageNumber,1);
assert.equal(agenda.find(x=>x.type==="change")?.reviewRequired,true);
assert.deepEqual(agenda.map(x=>x.id),buildReviewAgenda({validationFailures:["Evidence validation failed."],findings:[finding],conditions:[condition],changes:[change]}).map(x=>x.id),"agenda order is deterministic");

const app={tenantId:"t1",borrowerName:"Jane Doe",loanNumber:"L-1",loanAmount:300000,status:"UW Review",workflowVersion:"wv1",priority:"high",documentProcessingStatus:"complete",analysisVersionSequence:2,latestChangeSummary:{overallMateriality:"material",overallFavorability:"adverse",reReviewRequired:true,recommendedAction:"Review changes.",summary:{total:1,material:1,critical:0,adverse:1},changes:[change]},scan:{analysisVersion:"a1",readiness:{readinessLabel:"not_ready"},decision:{state:"blocked"},enterpriseEvidence:{state:"review_required",blockedReasons:["Evidence validation failed."],package:{packageId:"ep1",validation:{valid:false,errors:["Evidence validation failed."]},evidence:[{evidenceId:"e1",documentId:"d1",pageNumber:1,rawValue:"$10,000",normalizedValue:10000,confidence:.9}],resolutions:[{fieldName:"custom.monthly_qualifying_income",label:"Monthly qualifying income",canonicalValue:10000,confidence:.9,verificationState:"review_required",winningEvidenceId:"e1",supportingEvidenceIds:[],rejectedEvidenceIds:[],resolutionReason:"Highest-authority recent evidence."}],derivedValues:[],conflicts:[]}},mortgageReview:{packageId:"mr1",summary:{status:"blocked"},findings:[finding]},canonicalConditions:[condition]}};
app.latestChangeSummary.changes.push({...change,changeId:"doc-change",category:"document",entityId:"d1",favorability:"neutral"});
const documents=[{documentId:"d1",tenantId:"t1",applicationId:"app1",mimeType:"application/pdf",sizeBytes:100,uploadedAt:"2026-01-01T00:00:00.000Z",status:"uploaded",pageCount:2,documentType:"Paystub"},{documentId:"d2",tenantId:"t1",applicationId:"app1",mimeType:"text/plain",sizeBytes:20,uploadedAt:"2026-01-02T00:00:00.000Z",status:"uploaded"}];
const workspace=buildUnderwriterWorkspace("app1",app,documents);
assert.equal(workspace.schemaVersion,UNDERWRITER_WORKSPACE_VERSION);
assert.equal(workspace.application.id,"app1");
assert.equal(workspace.application.analysisVersionSequence,2);
assert.equal(workspace.workflow.priority,"high");
assert.equal(workspace.documents.length,2);
assert.equal(workspace.documents[0].pageCount,2);
assert.equal(workspace.documents[0].evidenceCount,1);
assert.equal(workspace.documents[0].changed,true);
assert.equal(workspace.canonicalFields.length,1);
assert.equal(workspace.canonicalFields[0].canonicalValue,10000);
assert.equal(workspace.canonicalFields[0].sourceCount,1);
assert.equal(workspace.canonicalFields[0].sources[0].documentId,"d1");
assert.equal(workspace.canonicalFields[0].sources[0].pageNumber,1);
assert.equal(workspace.findings[0].findingId,"f1");
assert.equal(workspace.conditions[0].id,"c1");
assert.equal(workspace.changeIntelligence?.reReviewRequired,true);
assert.ok(workspace.summary.unresolvedBlockers>0);
assert.equal(workspace.summary.baseline,false);
assert.equal(workspace.validation.evidenceAvailable,true);
assert.equal(workspace.validation.reviewAvailable,true);
assert.equal(JSON.stringify(workspace).includes("normalizedText"),false,"projection excludes OCR");
assert.equal(JSON.stringify(workspace).includes("storagePath"),false,"projection excludes storage paths");
assert.equal(workspace.documents.some((document:any)=>"storagePath" in document||"tenantId" in document),false,"document projection excludes storage and tenant authority fields");

const legacy=buildUnderwriterWorkspace("legacy",{status:"New",workflowVersion:"legacy-v1"},[]);
assert.equal(legacy.validation.legacy,true);
assert.equal(legacy.validation.evidenceAvailable,false);
assert.equal(legacy.summary.baseline,true);
assert.equal(legacy.documents.length,0);
assert.equal(legacy.canonicalFields.length,0);
assert.ok(legacy.workflow.requiredActions.length>0);
const missingPage=buildReviewAgenda({findings:[{...finding,findingId:"f2",generatedConditionRef:null,documents:[{documentId:"d1"}]}]});
assert.equal(missingPage[0].documentReferences[0].pageNumber,null);
assert.equal(buildReviewAgenda({findings:[{...finding,findingId:"f3",severity:"low",blocking:false,reviewRequired:false}],conditions:[]})[0].rank>agenda[1].rank,true);
console.log("PASS underwriter-workspace regression (35 assertions)");
