import assert from "node:assert/strict";
import { initializeTestEnvironment, assertFails } from "@firebase/rules-unit-testing";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { ref, getBytes, uploadBytes } from "firebase/storage";
import { initializeApp, deleteApp } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { executePlatformLegacyInventory } from "../lib/server/legacyOwnership/platformLegacyInventoryCommand";
import { signPlatformLegacyInventoryRequest } from "../lib/server/legacyOwnership/platformLegacyInventoryCore";
import { PLATFORM_LEGACY_INVENTORY_POLICY, PLATFORM_LEGACY_INVENTORY_SCOPE } from "../lib/contracts/platformLegacyInventory";
console.log("PLATFORM_LEGACY_INVENTORY_EMULATOR_CHILD_STARTED");
async function main(){
 const projectId=process.env.GCLOUD_PROJECT||"demo-velocity-platform-legacy-inventory",app=initializeApp({projectId,storageBucket:`${projectId}.appspot.com`}),db=getFirestore(app),bucket=getStorage(app).bucket();
 const [fh,fp]=process.env.FIRESTORE_EMULATOR_HOST!.split(":"),[sh,sp]=process.env.FIREBASE_STORAGE_EMULATOR_HOST!.split(":"),env=await initializeTestEnvironment({projectId,firestore:{host:fh,port:+fp},storage:{host:sh,port:+sp}});
 const principalId="legacy_inventory_service_001",credentialVersion="credential_version_001",secret="synthetic-platform-inventory-secret-000001",path="/api/platform/legacy-ownership/inventory";
 Object.assign(process.env,{NODE_ENV:"test",LEGACY_INVENTORY_SERVICE_ID:principalId,LEGACY_INVENTORY_CREDENTIAL_VERSION:credentialVersion,LEGACY_INVENTORY_CREDENTIAL:secret,LEGACY_OWNERSHIP_OPERATIONAL_CURSOR_SECRET:"synthetic-operational-cursor-secret-0001"});
 const make=(body:any,nonce:string)=>{const text=JSON.stringify(body),timestamp=new Date().toISOString(),headers:any={"content-type":"application/json","x-velocity-service-id":principalId,"x-velocity-credential-version":credentialVersion,"x-velocity-timestamp":timestamp,"x-velocity-nonce":nonce};headers["x-velocity-signature"]=signPlatformLegacyInventoryRequest({secret,method:"POST",path,timestamp,nonce,body:text});return new Request(`http://localhost${path}`,{method:"POST",headers,body:text})};
 try{
  await db.doc(`platformServiceGrants/${principalId}`).set({schemaVersion:"platform-legacy-inventory-grant.v1",principalId,principalKind:"legacy_inventory_service",status:"active",credentialVersion,grantVersion:"grant_version_001",scope:PLATFORM_LEGACY_INVENTORY_SCOPE,environment:"test",allowedProjectIds:[projectId],expiresAt:"2027-01-01T00:00:00.000Z",policyVersion:PLATFORM_LEGACY_INVENTORY_POLICY,provenance:{source:"governed_service_grant",humanRolePresent:false,tenantAuthorityPresent:false}});
  for(const[id,data]of[["app_a",{tenantId:"tenant_alpha",ownershipState:"tenant_owned",authorizationVersion:"auth-v1",borrowerName:"SECRET"}],["app_b",{borrowerName:"UNRESOLVED",storedDocs:[{name:"secret.pdf"}]}],["app_c",{tenantId:"tenant_alpha",ownershipState:"ownership_unresolved"}]]as const)await db.doc(`applications/${id}`).set(data);
  await db.doc("applicationDocuments/doc_a").set({applicationId:"app_a",tenantId:"tenant_alpha",ownershipState:"tenant_owned",authorizationVersion:"doc-v1"});await bucket.file("applications/app_b/secret.pdf").save(Buffer.from("legacy"),{metadata:{contentType:"application/pdf"}});
  const businessBefore=JSON.stringify((await db.collection("applications").get()).docs.map(x=>[x.id,x.data()])),docsBefore=JSON.stringify((await db.collection("applicationDocuments").get()).docs.map(x=>[x.id,x.data()])),[metaBefore]=await bucket.file("applications/app_b/secret.pdf").getMetadata();
  const body={idempotencyKey:"inventory_command_0001",runMode:"dry_run",pageSize:1,includeResourceClasses:["applications","application_documents","legacy_storage_metadata"]};
  const first=await executePlatformLegacyInventory(make(body,"nonce_inventory_0001"));assert(first.ok&&first.receipt.continuationCursor&&!first.receipt.mutationPerformed);
  const retry=await executePlatformLegacyInventory(make(body,"nonce_inventory_0002"));assert(retry.ok&&retry.receipt.receiptId===first.receipt.receiptId);
  const conflict=await executePlatformLegacyInventory(make({...body,pageSize:2},"nonce_inventory_0003"));assert(!conflict.ok&&conflict.error.code==="INVENTORY_COMMAND_CONFLICT");
  const replayBody={...body,idempotencyKey:"inventory_replay_0001"};assert((await executePlatformLegacyInventory(make(replayBody,"nonce_inventory_replay"))).ok);const replay=await executePlatformLegacyInventory(make(replayBody,"nonce_inventory_replay"));assert(!replay.ok&&replay.error.code==="SERVICE_REQUEST_REPLAYED");
  const next=await executePlatformLegacyInventory(make({...body,idempotencyKey:"inventory_next_0001",continuationCursor:first.receipt.continuationCursor},"nonce_inventory_next"));assert(next.ok);
  const tampered=await executePlatformLegacyInventory(make({...body,idempotencyKey:"inventory_tamper_0001",continuationCursor:first.receipt.continuationCursor+"x"},"nonce_inventory_tamper"));assert(!tampered.ok&&tampered.error.code==="INVENTORY_CURSOR_INVALID");
  const concurrentBody={...body,idempotencyKey:"inventory_concurrent_0001",pageSize:2},[c1,c2]=await Promise.all([executePlatformLegacyInventory(make(concurrentBody,"nonce_concurrent_0001")),executePlatformLegacyInventory(make(concurrentBody,"nonce_concurrent_0002"))]);assert(c1.ok||c2.ok);if(c1.ok&&c2.ok)assert.equal(c1.receipt.receiptId,c2.receipt.receiptId);
  const startFail=await executePlatformLegacyInventory(make({...body,idempotencyKey:"inventory_start_fail_0001"},"nonce_start_fail"),{failStartAudit:true});assert(!startFail.ok&&startFail.error.code==="AUDIT_REQUIRED");
  const completionFail=await executePlatformLegacyInventory(make({...body,idempotencyKey:"inventory_completion_fail_0001"},"nonce_completion_fail"),{failCompletionAudit:true});assert(!completionFail.ok&&completionFail.error.code==="AUDIT_REQUIRED");assert(!(await db.collection("legacyOwnershipInventoryCommands").where("status","==","completion_audit_recovery_required").get()).empty);
  for(const [key,classes,total]of[["class_apps_0001",["applications"],3],["class_docs_0001",["application_documents"],1],["class_storage_0001",["legacy_storage_metadata"],1]]as const){const counters:Record<string,number>={};const result=await executePlatformLegacyInventory(make({idempotencyKey:key,runMode:"dry_run",pageSize:10,includeResourceClasses:classes},`nonce_${key}`),{dependencyCallCounters:counters});assert(result.ok&&result.receipt.totalScanned===total,`${key} filtered discovery`);assert.deepEqual(Object.keys(counters),[...classes]) }
  await db.doc(`platformServiceGrants/${principalId}`).update({status:"revoked",revokedAt:new Date().toISOString()});const denied=await executePlatformLegacyInventory(make({...body,idempotencyKey:"denied_grant_0001"},"nonce_denied_grant"));assert(!denied.ok&&denied.error.code==="PLATFORM_AUTHORITY_REQUIRED");const denialAudits=await db.collection("legacyOwnershipInventoryAuditEvents").where("reasonCode","==","GRANT_REVOKED").get();assert.equal(denialAudits.size,1);assert.equal(denialAudits.docs[0].data().action,"dry_run_denied");const deniedCounters:Record<string,number>={};const auditRequired=await executePlatformLegacyInventory(make({...body,idempotencyKey:"denied_audit_fail_0001"},"nonce_denied_audit_fail"),{failDenialAudit:true,dependencyCallCounters:deniedCounters});assert(!auditRequired.ok&&auditRequired.error.code==="AUDIT_REQUIRED");assert.deepEqual(deniedCounters,{});
  const commands=await db.collection("legacyOwnershipInventoryCommands").get(),receipts=await db.collection("legacyOwnershipInventoryReceipts").get(),audits=await db.collection("legacyOwnershipInventoryAuditEvents").get();assert(!commands.empty&&!receipts.empty&&!audits.empty);assert(!/SECRET|UNRESOLVED|secret\.pdf|applications\/app_b/.test(JSON.stringify([...commands.docs,...receipts.docs,...audits.docs].map(x=>x.data()))));
  assert.equal(JSON.stringify((await db.collection("applications").get()).docs.map(x=>[x.id,x.data()])),businessBefore);assert.equal(JSON.stringify((await db.collection("applicationDocuments").get()).docs.map(x=>[x.id,x.data()])),docsBefore);const[metaAfter]=await bucket.file("applications/app_b/secret.pdf").getMetadata();assert.equal(metaAfter.generation,metaBefore.generation);
  const client=env.authenticatedContext("tenant_admin");await assertFails(getDoc(doc(client.firestore(),"applications/app_a")));await assertFails(setDoc(doc(client.firestore(),"applications/browser_claim"),{tenantId:"tenant_alpha"}));await assertFails(getBytes(ref(client.storage(),"applications/app_b/secret.pdf")));await assertFails(uploadBytes(ref(client.storage(),"applications/app_b/new.pdf"),new Uint8Array([1])));
  console.log("PLATFORM_LEGACY_INVENTORY_EMULATOR_CHILD_COMPLETED");console.log("Platform legacy inventory emulator regression: signed authority, replay, idempotency, concurrency, cursor, recovery, persistence and read-only invariance passed");
 }finally{await env.cleanup();await deleteApp(app)}
}main().catch(e=>{console.error(e);process.exitCode=1});
