import assert from "node:assert/strict";
import {getApps,initializeApp} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
import {getStorage} from "firebase-admin/storage";
import {analyzeApplication} from "../lib/ai/analyzeApplication";
import {resolverAuth,resolverMembership,resolverTenant} from "../lib/server/authorization/tenantAuthorizationResolverFixtures";
import {generateCanonicalReport,readCanonicalReport} from "../lib/server/reports/reportExportOrchestrator";
console.log("REPORT_EXPORT_EMULATOR_CHILD_STARTED");
async function main(){
 if(!getApps().length)initializeApp({projectId:process.env.GCLOUD_PROJECT||"demo-velocity-report-export",storageBucket:"demo-velocity-report-export.appspot.com"});
 const db=getFirestore(),bucket=getStorage().bucket(),at="2026-07-15T20:00:00.000Z",authFor=(s:string)=>({...resolverAuth("processor_user"),requestId:`req_${s}`,correlationId:`corr_${s}`}) as any;
 await db.doc("tenants/tenant_alpha").set(resolverTenant("tenant_alpha","active"));await db.doc("userTenantMemberships/processor_user/tenants/tenant_alpha").set({tenantId:"tenant_alpha"});await db.doc("tenants/tenant_alpha/members/processor_user").set(resolverMembership("tenant_alpha","processor_user","processor"));await db.doc("applications/application_alpha").set({tenantId:"tenant_alpha",ownershipState:"tenant_owned",authorizationVersion:"auth-v1",status:"New",createdAt:at,updatedAt:at});
 const output=await analyzeApplication([{name:"synthetic.pdf",type:"1003",text:"",extracted:{borrower:"Synthetic Borrower",income:96000,loanAmount:250000,propertyValue:320000,creditScore:720,assets:50000,debts:1200}}] as any,{applicationId:"application_alpha",analysisVersion:"canonical-evidence-analysis.v1"}),commandId="analysis_fixture",response={ok:true,status:"completed",applicationId:"application_alpha",analysisVersion:"canonical-evidence-analysis.v1",policyVersion:"application-analyze-policy.v1",evidenceAggregationFingerprint:"agg_fixture",documentCount:1,analysis:output,requestId:"req_analysis",correlationId:"corr_analysis",writeResult:"created"};
 await db.doc("tenants/tenant_alpha/applications/application_alpha/analysisState/current").set({commandId,applicationAuthorizationVersion:"app-v1",documentLineage:[{documentId:"document_fixture",documentAuthorizationVersion:"doc-v1",sourceHash:"a".repeat(64),processingFingerprint:"b".repeat(64)}],evidenceAggregationFingerprint:"agg_fixture",analysisVersion:"canonical-evidence-analysis.v1",policyVersion:"application-analyze-policy.v1",completedAt:at});await db.doc("tenants/tenant_alpha/applications/application_alpha/analysisCommands/key_fixture").set({commandId,status:"completed",response});
 let n=0,reportId="";const test=async(x:string,f:()=>Promise<void>)=>{await f();console.log(`PASS ${++n}: ${x}`)};
 await test("authorized generation writes real canonical PDF",async()=>{const r=await generateCanonicalReport({auth:authFor("generate"),applicationId:"application_alpha",body:{idempotencyKey:"report_key",reportType:"underwriting_summary",outputFormat:"pdf"}});assert(r.ok);reportId=r.reportId;const a=(await db.doc(`reportArtifacts/${reportId}`).get()).data()!,path=`tenants/tenant_alpha/applications/application_alpha/reports/${reportId}/artifact.pdf`,[bytes]=await bucket.file(path).download();assert.equal(bytes.length,a.artifactSizeBytes);assert.equal(bytes.subarray(0,4).toString(),"%PDF")});
 await test("retry read and conflict behavior",async()=>{const retry=await generateCanonicalReport({auth:authFor("retry"),applicationId:"application_alpha",body:{idempotencyKey:"report_key"}});assert(retry.ok&&retry.reportId===reportId&&retry.writeResult==="already_exists_identical");assert(!(await generateCanonicalReport({auth:authFor("conflict"),applicationId:"application_alpha",body:{idempotencyKey:"report_key",analysis:{}}})).ok);const read=await readCanonicalReport({auth:authFor("read"),applicationId:"application_alpha"});assert(read.ok&&Buffer.from(read.bytes).subarray(0,4).toString()==="%PDF")});
 await test("incomplete missing and cross-tenant inputs fail with sources unchanged",async()=>{await db.doc("tenants/tenant_alpha/applications/application_alpha/analysisCommands/key_fixture").update({status:"running"});assert(!(await generateCanonicalReport({auth:authFor("incomplete"),applicationId:"application_alpha",body:{idempotencyKey:"other_key"}})).ok);await db.doc("tenants/tenant_alpha/applications/application_alpha/analysisCommands/key_fixture").update({status:"completed"});assert(!(await readCanonicalReport({auth:authFor("missing"),applicationId:"application_missing"})).ok);assert((await db.collection("tenants/tenant_alpha/authorizationAuditEvents").get()).size>0);assert.equal((await db.doc("applications/application_alpha").get()).data()?.tenantId,"tenant_alpha")});
 console.log("REPORT_EXPORT_EMULATOR_CHILD_COMPLETED");console.log(`Report export emulator regression: ${n}/${n} passed`);
}
main().catch(e=>{console.error(e);process.exitCode=1});
