import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { APPLICATION_DELETE_POLICY, evaluateApplicationDeletePolicy } from "../lib/server/applications/applicationDeletePolicy";

let passed=0;const test=(name:string,run:()=>void)=>{run();console.log(`PASS ${++passed}: ${name}`)};
const rules=fs.readFileSync("firestore.rules","utf8"),storage=fs.readFileSync("storage.rules","utf8"),rollback=fs.readFileSync("tests/application-delete-cutover/firestore.rollback.rules","utf8"),policy=fs.readFileSync("lib/server/applications/applicationDeletePolicy.ts","utf8"),route=fs.readFileSync("app/api/applications/[id]/route.ts","utf8"),detail=fs.readFileSync("app/applications/[id]/page.tsx","utf8"),workflow=fs.readFileSync("lib/server/workflow/applicationWorkflowCommands.ts","utf8"),documents=fs.readFileSync("lib/server/documents/documentCutover.ts","utf8");
const appBlock=rules.slice(rules.indexOf("match /applications/{id}"),rules.indexOf("// Default deny"));
test("authentication cannot be bypassed because no deletion entry point exists",()=>{assert(!route.includes("export async function DELETE"));assert(!fs.existsSync("app/api/applications/[id]/delete/route.ts"))});
test("tenant ownership cannot be caller supplied to deletion",()=>{assert(!route.includes("applicationDelete"));assert(!detail.includes("application.delete"))});
test("no role receives an executable deletion policy",()=>{assert.deepEqual(APPLICATION_DELETE_POLICY.eligibleHumanRoles,[]);assert.deepEqual(APPLICATION_DELETE_POLICY.eligiblePermissions,[])});
test("caller authority fields have no deletion contract",()=>{for(const x of ["tenantId","role","permission","creator","storagePath","auditId"])assert(!policy.includes(`input.${x}`))});
test("unknown request fields cannot reach a deletion parser",()=>{assert(!policy.includes("JSON.parse"));assert(!policy.includes("request.json"))});
test("reason codes are descriptive but never authorize destruction",()=>{assert(APPLICATION_DELETE_POLICY.acceptedReasonCodes.includes("created_in_error"));assert.equal(APPLICATION_DELETE_POLICY.deletionMode,"disabled")});
test("application and workflow versions cannot be used to authorize deletion",()=>{assert.equal(evaluateApplicationDeletePolicy().error.code,"DELETE_NOT_ALLOWED")});
test("stale-state ambiguity fails closed",()=>{assert.equal(APPLICATION_DELETE_POLICY.hardDeleteAllowed,false)});
test("document inventory is authoritative and must be absent before any future policy",()=>{assert.equal(APPLICATION_DELETE_POLICY.documentsMustBeAbsent,true)});
test("remaining documents block any future deletion posture",()=>{assert.equal(APPLICATION_DELETE_POLICY.storageMutationAllowed,false)});
test("immutable decisions and audits must be preserved",()=>{assert.equal(APPLICATION_DELETE_POLICY.decisionHistoryBlocksDeletion,true);assert.equal(APPLICATION_DELETE_POLICY.immutableHistoryMustBePreserved,true)});
test("active operations block deletion",()=>{assert.equal(APPLICATION_DELETE_POLICY.activeOperationsBlockDeletion,true)});
test("no tombstone with borrower PII is created",()=>{assert.equal(APPLICATION_DELETE_POLICY.tombstoneAllowed,false);for(const x of ["borrowerName","email","loanAmount","creditScore"])assert(!policy.includes(x))});
test("repeated evaluation is deterministic and immutable",()=>{const a=evaluateApplicationDeletePolicy(),b=evaluateApplicationDeletePolicy();assert.deepEqual(a,b);assert(Object.isFrozen(a)&&Object.isFrozen(a.error))});
test("there is no idempotency key capable of reserving destructive work",()=>{assert(!policy.includes("idempotencyKey"))});
test("concurrent requests have no mutation winner",()=>{assert(!policy.includes("runTransaction"));assert(!policy.includes(".delete("))});
test("no success can be acknowledged",()=>{assert.equal(evaluateApplicationDeletePolicy().ok,false)});
test("audit failure cannot expose a partially deleted record",()=>{assert.equal(APPLICATION_DELETE_POLICY.hardDeleteAllowed,false)});
test("denial creates no destructive mutation",()=>{assert(!policy.includes("getFirestore"));assert(!policy.includes("getStorage"))});
test("safe denial response is allowlisted",()=>{assert.deepEqual(Object.keys(evaluateApplicationDeletePolicy()).sort(),["error","ok","policyVersion","status"].sort())});
test("public error contains no PII or dependency contents",()=>{assert.deepEqual(evaluateApplicationDeletePolicy().error,{code:"DELETE_NOT_ALLOWED",message:"Application deletion is not available."})});
test("browser parent delete primitive is absent",()=>{const files:string[]=[];const walk=(p:string)=>fs.readdirSync(p,{withFileTypes:true}).forEach(e=>{const n=path.join(p,e.name);e.isDirectory()?walk(n):/\.(ts|tsx)$/.test(e.name)&&files.push(n)});walk("app");for(const f of files)assert(!fs.readFileSync(f,"utf8").includes('deleteDoc(doc(db, "applications"'),f)});
test("no Storage deletion is introduced",()=>{assert.equal(APPLICATION_DELETE_POLICY.storageMutationAllowed,false);assert(!policy.includes("bucket"))});
test("only application delete rule changes and rollback is narrow",()=>{assert(rollback.includes("allow create, read, update: if false"));assert(rollback.includes("allow delete: if isAdmin()"));assert(!rollback.includes("storage"))});
test("all direct application operations are denied",()=>{for(const operation of ["create","read","update","delete"])assert(appBlock.includes(`allow ${operation}: if false`),operation)});
test("existing document cleanup and workflow reset remain governed",()=>{assert(documents.includes("deleteCanonicalDocument"));assert(workflow.includes("reset_after_documents_deleted"));assert(workflow.includes('permissionFor'))});
test("retention and legal-hold requirements remain explicit",()=>{assert(APPLICATION_DELETE_POLICY.unresolvedRequirements.includes("approved_retention_schedule"));assert(APPLICATION_DELETE_POLICY.unresolvedRequirements.includes("legal_hold_policy"));assert.equal(APPLICATION_DELETE_POLICY.status,"provisional_product_review_required")});
test("Storage rules remain byte-for-byte outside the policy",()=>{assert(storage.length>0);assert(!policy.includes("storage.rules"))});
console.log(`Application delete cutover deterministic regression: ${passed}/${passed} passed`);
