import fs from "fs";
import path from "path";
import { resolveTenantAuthorizationContextCore, type TenantAuthorizationRepository } from "../lib/server/authorization/tenantAuthorizationResolverCore";
import { resolverAuth, resolverMembership, resolverTenant, tenantAuthorizationResolverFixtures as f } from "../lib/server/authorization/tenantAuthorizationResolverFixtures";

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
const repository = (discovered: readonly string[], tenants: Record<string, unknown> = {}, memberships: Record<string, unknown> = {}): TenantAuthorizationRepository => ({ listDiscoveredTenantIds: async () => discovered, getTenant: async (id) => tenants[id], getMembership: async (tenantId, userId) => memberships[`${tenantId}/${userId}`] });
const resolve = (userId: string, repo: TenantAuthorizationRepository, requestedTenantId?: unknown) => resolveTenantAuthorizationContextCore({ authentication: resolverAuth(userId), ...(requestedTenantId !== undefined ? { requestedTenantId } : {}) }, repo, () => new Date(f.now));

async function main() {
  const activeRepo = repository([f.tenants.alpha], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha) }, { [`${f.tenants.alpha}/${f.users.single}`]: resolverMembership(f.tenants.alpha, f.users.single) });
  const single = await resolve(f.users.single, activeRepo); assert(single.ok && single.context.tenantId === f.tenants.alpha && single.context.role === "processor" && single.context.authentication.principalId === f.users.single, "active single membership failed");
  const multiRepo = repository([f.tenants.alpha, f.tenants.beta], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha), [f.tenants.beta]: resolverTenant(f.tenants.beta) }, { [`${f.tenants.alpha}/${f.users.multi}`]: resolverMembership(f.tenants.alpha, f.users.multi), [`${f.tenants.beta}/${f.users.multi}`]: resolverMembership(f.tenants.beta, f.users.multi, "viewer") });
  const ambiguous = await resolve(f.users.multi, multiRepo); assert(!ambiguous.ok && ambiguous.error.code === "TENANT_SELECTION_REQUIRED", "multi-tenant selection guessed");
  const explicit = await resolve(f.users.multi, multiRepo, f.tenants.beta); assert(explicit.ok && explicit.context.tenantId === f.tenants.beta && explicit.context.role === "viewer", "explicit selection failed");
  const wrong = await resolve(f.users.single, activeRepo, f.tenants.beta); assert(!wrong.ok && wrong.error.code === "TENANT_NOT_FOUND", "wrong tenant selection leaked existence");
  const noDiscoveryExplicit = await resolve(f.users.single, repository([], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha) }, { [`${f.tenants.alpha}/${f.users.single}`]: resolverMembership(f.tenants.alpha, f.users.single) }), f.tenants.alpha); assert(noDiscoveryExplicit.ok, "discovery incorrectly became authority");
  const missing = await resolve(f.users.missing, repository([f.tenants.alpha], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha) })); assert(!missing.ok && missing.error.code === "MEMBERSHIP_NOT_FOUND", "missing membership accepted");
  const mismatch = await resolve(f.users.wrongUid, repository([f.tenants.alpha], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha) }, { [`${f.tenants.alpha}/${f.users.wrongUid}`]: resolverMembership(f.tenants.alpha, "another_user") })); assert(!mismatch.ok && mismatch.error.code === "MEMBERSHIP_NOT_FOUND", "mismatched UID accepted");
  for (const [user, status] of [[f.users.invited, "invited"], [f.users.suspended, "suspended"], [f.users.disabled, "disabled"]] as const) { const result = await resolve(user, repository([f.tenants.alpha], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha) }, { [`${f.tenants.alpha}/${user}`]: resolverMembership(f.tenants.alpha, user, "processor", status) })); assert(!result.ok && result.error.code === "MEMBERSHIP_INACTIVE", `${status} membership accepted`); }
  for (const [tenantId, status] of [[f.tenants.suspended, "suspended"], [f.tenants.disabled, "disabled"]] as const) { const result = await resolve(f.users.single, repository([tenantId], { [tenantId]: resolverTenant(tenantId, status) }, { [`${tenantId}/${f.users.single}`]: resolverMembership(tenantId, f.users.single) })); assert(!result.ok && result.error.code === "TENANT_INACTIVE", `${status} tenant accepted`); }
  const unknown = await resolve(f.users.unknown, repository([f.tenants.alpha], { [f.tenants.alpha]: resolverTenant(f.tenants.alpha) }, { [`${f.tenants.alpha}/${f.users.unknown}`]: resolverMembership(f.tenants.alpha, f.users.unknown, "unknown") })); assert(!unknown.ok && unknown.error.code === "ROLE_UNKNOWN", "unknown role accepted");
  const invalidDiscovery = await resolve(f.users.single, repository([f.tenants.invalidDiscovery])); assert(!invalidDiscovery.ok && invalidDiscovery.error.code === "TENANT_NOT_FOUND", "invalid discovery target accepted");
  const dependency = await resolve(f.users.single, { listDiscoveredTenantIds: async () => { throw new Error("raw Firestore secret"); }, getTenant: async () => undefined, getMembership: async () => undefined }); assert(!dependency.ok && dependency.error.code === "INTERNAL_ERROR" && !JSON.stringify(dependency).includes("Firestore"), "dependency error escaped");
  const unauthenticated = await resolveTenantAuthorizationContextCore({ authentication: {} }, activeRepo); assert(!unauthenticated.ok && unauthenticated.error.code === "AUTH_INVALID", "unauthenticated input accepted");
  const contextText = JSON.stringify(single); assert(!/email|localStorage|companyProfileId|requestRole|token|cookie/i.test(contextText), "context accepted client authority or PII"); assert(single.ok && Object.isFrozen(single.context) && Object.isFrozen(single.context.authentication) && Object.isFrozen(single.context.audit), "context output mutable");
  const production = ["app", "components", "middleware.ts"].flatMap((root) => !fs.existsSync(root) ? [] : fs.statSync(root).isFile() ? [root] : [...fs.readdirSync(root, { recursive: true })].map(String).map((entry) => path.join(root, entry)).filter((file) => fs.statSync(file).isFile() && /\.(ts|tsx)$/.test(file))); assert(production.every((file) => !/tenantAuthorizationResolver/.test(fs.readFileSync(file, "utf8"))), "production surface imports resolver");
  console.log("Tenant authorization resolver regression: PASS");
  console.log("PASS: selection, authoritative membership, inactive/mismatch/unknown denial, discovery non-authority, stable errors and production isolation");
}
main().catch((error) => { console.error(error?.message || String(error)); process.exitCode = 1; });
