import { executeBillingCommand, InMemoryBillingCommandRepository } from "../lib/server/billing/stripeBillingService";
import { allow, auth, context, harness, NOW } from "../tests/stripe-billing/billingTestFixtures";
let passed = 0; const assert = (v: unknown, m: string) => { if (!v) throw new Error(m); passed++; };
const run = (action: "checkout" | "portal", key: string, h: ReturnType<typeof harness>, a = auth(), c = context(a)) => executeBillingCommand({ auth: a, context: c, decision: allow(a, c, action), action, idempotencyKey: key, appOrigin: "https://velocity.test" }, h.dependencies);
async function main() {
  delete process.env.STRIPE_SECRET_KEY;
  const checkout = harness(), inputAuth = auth(), inputContext = context(inputAuth), before = JSON.stringify({ inputAuth, inputContext }); const ok = await executeBillingCommand({ auth: inputAuth, context: inputContext, decision: allow(inputAuth, inputContext), action: "checkout", idempotencyKey: "checkout_key_001", appOrigin: "https://velocity.test" }, checkout.dependencies); assert(ok.ok, "authorized checkout failed"); assert(checkout.counts().checkoutCalls === 1, "checkout call count"); assert(checkout.events[0] === "audit:authorization" && checkout.events[1] === "provider:checkout", "audit was not before provider"); assert(JSON.stringify({ inputAuth, inputContext }) === before, "inputs mutated"); assert(ok.ok && Object.keys(ok).sort().join() === "commandId,correlationId,ok,redirectUrl,requestId", "response not allowlisted"); assert(ok.ok && ok.redirectUrl === "https://checkout.stripe.test/session", "redirect changed");
  const portal = harness(); const portalResult = await run("portal", "portal_key_001", portal); assert(portalResult.ok && portal.counts().portalCalls === 1, "portal failed");
  const noPermission = context(auth(), "tenant_alpha", "admin"); const denied = await executeBillingCommand({ auth: auth(), context: noPermission, decision: { ...allow(auth(), noPermission), decision: "deny", reasonCode: "permission_missing", audit: { action: "billing.checkout", outcome: "denied", piiPresent: false } } as any, action: "checkout", idempotencyKey: "denied_key_001", appOrigin: "https://velocity.test" }, harness().dependencies); assert(!denied.ok && denied.error.code === "FORBIDDEN", "canonical denial ignored");
  const wrongPrincipal = await executeBillingCommand({ auth: auth("user_alpha"), context: context(auth("user_beta")), decision: allow(auth("user_beta"), context(auth("user_beta"))), action: "checkout", idempotencyKey: "principal_key_001", appOrigin: "https://velocity.test" }, harness().dependencies); assert(!wrongPrincipal.ok && wrongPrincipal.error.code === "AUTH_INVALID", "principal mismatch allowed");
  const missingTenant = harness({ missingMapping: true }); const missing = await run("checkout", "mapping_key_001", missingTenant); assert(!missing.ok && missing.error.code === "BILLING_CUSTOMER_NOT_AVAILABLE" && missingTenant.counts().checkoutCalls === 0, "missing mapping not closed");
  const cross = harness({ mappingTenant: "cross" }); const crossResult = await run("checkout", "cross_tenant_001", cross); assert(!crossResult.ok && crossResult.error.code === "BILLING_CUSTOMER_NOT_AVAILABLE" && cross.counts().checkoutCalls === 0, "cross tenant mapping used");
  const auditFailure = harness({ authorizationAuditFailure: true }); const auditDenied = await run("checkout", "audit_fail_001", auditFailure); assert(!auditDenied.ok && auditDenied.error.code === "AUDIT_REQUIRED" && auditFailure.counts().checkoutCalls === 0, "provider called after auth audit failure");
  const providerFailure = harness({ providerFailure: true }); const failed = await run("checkout", "provider_fail_001", providerFailure); assert(!failed.ok && failed.error.code === "BILLING_PROVIDER_FAILED", "provider failure unsafe"); assert(!JSON.stringify(failed).match(/secret|cus_private|unset/i), "provider details leaked");
  const missingProduction = harness({ providerFailure: true }); const missingConfig = await run("checkout", "missing_secret_001", missingProduction); assert(!missingConfig.ok && missingConfig.error.code === "BILLING_PROVIDER_FAILED", "missing provider configuration not stable");
  const commands = new InMemoryBillingCommandRepository(), retry = harness({ commands }); const first = await run("checkout", "retry_key_001", retry), second = await run("checkout", "retry_key_001", retry); assert(first.ok && second.ok && first.commandId === second.commandId, "identical retry changed receipt"); assert(retry.counts().checkoutCalls === 1, "retry duplicated provider effect");
  const changedPrincipal = auth("user_beta", "request_beta"), conflict = await run("checkout", "retry_key_001", retry, changedPrincipal, context(changedPrincipal)); assert(!conflict.ok && conflict.error.code === "BILLING_COMMAND_CONFLICT", "conflicting reuse allowed");
  const portalCommands = new InMemoryBillingCommandRepository(), portalRetry = harness({ commands: portalCommands }); const p1 = await run("portal", "portal_retry_001", portalRetry), p2 = await run("portal", "portal_retry_001", portalRetry); assert(p1.ok && p2.ok && portalRetry.counts().portalCalls === 1, "portal retry duplicated");
  for (const origin of ["https://evil.test/path", "//evil.test", "https://user:pass@evil.test", "https://velocity.test\\@evil.test"]) { const h = harness(); const r = await executeBillingCommand({ auth: auth(), context: context(), decision: allow(), action: "checkout", idempotencyKey: "redirect_key_001", appOrigin: origin }, h.dependencies); assert(!r.ok && h.counts().checkoutCalls === 0, `unsafe origin accepted: ${origin}`); }
  const operationAuditFailure = harness({ operationAuditFailure: true }); const oa = await run("checkout", "operation_audit_001", operationAuditFailure); assert(!oa.ok && oa.error.code === "AUDIT_REQUIRED", "operation audit failure acknowledged");
  assert(!JSON.stringify(checkout.events).match(/cus_|stripe\.test\/session/), "audit captured customer or URL"); assert(!JSON.stringify(ok).includes("providerReference"), "raw provider response leaked"); assert(!JSON.stringify({ NOW, result: ok }).includes("STRIPE_SECRET_KEY"), "secret name leaked");
  console.log(`Stripe billing deterministic regression: ${passed}/${passed} passed`);
}
main().catch(e => { console.error(e); process.exit(1); });
