import assert from "node:assert/strict";
import fs from "node:fs";
import { resolverAuth } from "../lib/server/authorization/tenantAuthorizationResolverFixtures";
import { resolveApplicationResourceFactsCore } from "../lib/server/authorization/applicationResourceResolverCore";
import { executeApplicationReadRoute } from "../lib/server/applications/applicationReadRouteCore";

async function main() {
const nowText = "2026-07-12T12:00:00.000Z", auth = resolverAuth("processor_user");
const record = { applicationId: "application_alpha", ownershipState: "tenant_owned", tenantId: "tenant_alpha", authorizationVersion: "auth-v1", status: "New", assignedProcessorId: "processor_user", teamIds: ["team_alpha"], createdAt: nowText, updatedAt: nowText, borrowerName: "Synthetic Borrower", borrowerEmail: "synthetic@example.invalid", loanAmount: 100000, unknownField: "secret" };
const resolved = await resolveApplicationResourceFactsCore({ applicationId: "application_alpha" }, { getApplicationById: async () => ({ exists: true, data: record }) }, () => new Date(nowText)); assert(resolved.ok);
const auditPlan = { tenantId: "tenant_alpha", eventId: "opaque_event" } as any;
const run = async (options: { method?: string; authorization?: any; persistOk?: boolean } = {}) => { const steps: string[] = []; const response = await executeApplicationReadRoute(new Request("https://velocity.test/api/applications/application_alpha", { method: options.method ?? "GET", headers: { "x-velocity-tenant-id": "tenant_alpha" } }), "application_alpha", { authenticate: async () => ({ ok: true, state: "authenticated", context: auth } as any), authorize: async () => options.authorization ?? ({ ok: true, context: {}, applicationFacts: resolved.ok ? resolved.facts : undefined, decision: { decision: "allow" }, auditPlan }), persist: async () => ({ ok: options.persistOk ?? true }), now: () => new Date(nowText), onStep: (step) => steps.push(step) }); return { response, body: await response.json(), steps }; };
let count = 0; const test = async (name: string, fn: () => Promise<void> | void) => { await fn(); console.log(`PASS ${++count}: ${name}`); };
await test("exact allow order authenticates, authorizes, audits, projects, then responds", async () => { const result = await run(); assert.equal(result.response.status, 200); assert.deepEqual(result.steps, ["validate_method", "authenticate", "validate_application_id", "resolve_tenant_selection", "authorize", "require_audit_plan", "persist_audit", "project_response", "respond_allow"]); });
await test("projection is allowlisted and contains no mortgage PII", async () => { const { body } = await run(); assert.deepEqual(Object.keys(body).sort(), ["applicationId","assignedProcessorId","compatibilityWarnings","correlationId","createdAt","ownershipState","requestId","resourceAuthorizationVersion","schemaVersion","status","teamIds","updatedAt"].sort()); for (const prohibited of ["borrower", "email", "loanAmount", "Synthetic Borrower", "synthetic@example.invalid", "unknownField"]) assert(!JSON.stringify(body).includes(prohibited)); });
await test("audit failure blocks all application data", async () => { const { response, body, steps } = await run({ persistOk: false }); assert.equal(response.status, 500); assert.equal(body.error.code, "INTERNAL_ERROR"); assert(!("applicationId" in body)); assert(!steps.includes("project_response")); });
await test("denial is audited before normalized response and never returns data", async () => { const denied = { ok: false, code: "DECISION_DENIED", internalReason: "permission_missing", publicError: { code: "FORBIDDEN", status: 403, message: "The requested action is not available." }, auditPlan }; const { body, steps } = await run({ authorization: denied }); assert.equal(body.error.code, "FORBIDDEN"); assert(steps.indexOf("persist_audit") < steps.indexOf("respond_denial")); assert(!("applicationId" in body)); });
await test("GET only and all responses are private no-store", async () => { const get = await run(), post = await run({ method: "POST" }); assert.equal(post.response.status, 405); assert.match(get.response.headers.get("cache-control") || "", /private, no-store/); assert.match(post.response.headers.get("cache-control") || "", /private, no-store/); });
await test("request and correlation IDs propagate", async () => { const { response, body } = await run(); assert.equal(body.requestId, auth.requestId); assert.equal(body.correlationId, auth.correlationId); assert.equal(response.headers.get("x-request-id"), auth.requestId); assert.equal(response.headers.get("x-correlation-id"), auth.correlationId); });
await test("route has no second lookup and prohibited surfaces remain unimported", () => { const route = fs.readFileSync("app/api/applications/[id]/route.ts", "utf8"), core = fs.readFileSync("lib/server/applications/applicationReadRouteCore.ts", "utf8"); assert(!/getFirestore|applications\/\$|\.doc\(/.test(core)); for (const forbidden of ["page.tsx", "analyze/route", "report/route", "workflow", "stripe"]) assert(!route.toLowerCase().includes(forbidden)); });
console.log(`Application read route regression: ${count}/${count} passed`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
