import { buildIntakeManifest, type Detection, type IntakeUpload, type PageObservation } from "../lib/document-intake";
function assert(value:unknown,message:string):asserts value {if(!value)throw new Error(message)}
const no=(version="vision.v1"):Detection=>Object.freeze({status:"not_detected",confidence:.99,detectorVersion:version});
const page=(pageNumber:number,overrides:Partial<PageObservation>={}):PageObservation=>Object.freeze({pageNumber,widthPixels:2550,heightPixels:3300,dpi:300,rotationDegrees:0,contrast:.9,noise:.05,compression:.05,cropping:.02,completeness:.99,scanConfidence:.96,blur:no("blur.v1"),fax:no("fax.v1"),screenshot:no("screenshot.v1"),handwritten:no("handwriting.v1"),...overrides});
const upload=(overrides:Partial<IntakeUpload>={}):IntakeUpload=>Object.freeze({documentId:"doc-001",fileName:"closing-disclosure.pdf",contentType:"application/pdf",sizeBytes:2048,sha256:"a".repeat(64),uploadOrder:2,pageCount:2,inputKind:"searchable_pdf",nativeText:"Closing Disclosure Loan Terms",borrowerId:"borrower-1",pages:Object.freeze([page(1),page(2)]),receivedAt:"2026-07-22T12:00:00.000Z",source:"lender_upload",...overrides});

function completeManifest(){const result=buildIntakeManifest(upload());assert(result.ok,"Expected manifest success");const m=result.manifest;assert(m.classification.documentType==="Closing Disclosure","Classification mismatch");assert(m.classification.confidence===.98,"Classification must be deterministic");assert(m.quality.normalizedScore>.9,"Quality score unexpectedly low");assert(m.orientation.rotationAngle===0&&!m.orientation.requiresRotation,"Orientation mismatch");assert(m.grouping.pages.length===2&&m.grouping.pages[1].groupIndex===1,"Grouping mismatch");assert(m.borrowerAssociation.status==="matched","Borrower association missing");assert(m.pipelineReadiness.readyForExtraction,"Clean classified document should be extraction ready");assert(m.validation.valid,"Manifest must be validated")}
function duplicateFailsClosed(){const result=buildIntakeManifest(upload(),{knownDocuments:[{documentId:"doc-prior",sha256:"a".repeat(64)}]});assert(result.ok,"Expected valid duplicate manifest");assert(result.manifest.duplicate.matchType==="exact","Exact duplicate missed");assert(!result.manifest.pipelineReadiness.readyForOcr,"Duplicate must be blocked")}
function unavailableDetectorFailsClosed(){const unavailable:Detection={status:"unavailable",confidence:0,detectorVersion:null};const result=buildIntakeManifest(upload({pageCount:1,pages:[page(1,{blur:unavailable})]}));assert(result.ok,"Unavailable detector is a valid finding");assert(result.manifest.pipelineReadiness.blockedReasons.includes("BLUR_ANALYSIS_UNAVAILABLE"),"Unavailable blur analysis must block readiness")}
function invalidInputRejected(){const result=buildIntakeManifest(upload({sha256:"invalid",pageCount:3}));assert(!result.ok,"Invalid upload must be rejected");assert(result.errors.some(e=>e.ruleId==="upload.sha256")&&result.errors.some(e=>e.ruleId==="upload.pages"),"Expected aggregate validation errors")}
function qualityAndRotation(){const result=buildIntakeManifest(upload({fileName:"bank_statement.jpg",nativeText:undefined,contentType:"image/jpeg",inputKind:"image",pageCount:1,pages:[page(1,{rotationDegrees:90,contrast:.2,noise:.9,compression:.9,cropping:.7,completeness:.5,scanConfidence:.3,blur:{status:"detected",confidence:.9,detectorVersion:"blur.v1"}})]}));assert(result.ok,"Expected degraded manifest");assert(result.manifest.classification.documentType==="Bank Statement","Filename classification failed");assert(result.manifest.orientation.requiresRotation&&result.manifest.orientation.rotationAngle===90,"Rotation not surfaced");assert(result.manifest.estimatedOcrDifficulty==="high","OCR difficulty should be high");assert(!result.manifest.pipelineReadiness.readyForOcr,"Poor quality should fail closed")}
const tests=[completeManifest,duplicateFailsClosed,unavailableDetectorFailsClosed,invalidInputRejected,qualityAndRotation];let passed=0;for(const test of tests){try{test();passed++;console.log(`PASS: ${test.name}`)}catch(error){console.error(`FAIL: ${test.name}`);throw error}}console.log(`\nDocument intake regression result: ${passed}/${tests.length} passed`);
