import fs from "node:fs";
import { WORKER_SERVICE_GRANT_V1, WORKER_SERVICE_POLICY_VERSION } from "../lib/contracts/workerServiceAuth";
import { authorizeWorkerServiceRequest, signWorkerServiceRequest } from "../lib/server/workers/workerServiceAuthCore";
let passed=0;const assert=(v:unknown,m:string)=>{if(!v)throw Error(m);passed++};const now="2026-07-16T16:00:00.000Z",secret="synthetic_worker_credential_12345678901234567890";
const grant=(kind:"files_worker"|"ai_worker"="files_worker",overrides:any={})=>({schemaVersion:WORKER_SERVICE_GRANT_V1,grantId:`grant_${kind}`,servicePrincipalId:`velocity_${kind}`,serviceKind:kind,status:"active",credentialVersion:"credential-v1",grantVersion:"grant-v1",environment:"test",scopes:kind==="files_worker"?["worker.files.claim","worker.files.read_document","worker.files.process","worker.files.write_result"]:["worker.ai.claim","worker.ai.read_application","worker.ai.execute","worker.ai.write_result"],tenantIds:["tenant_alpha"],policyVersion:WORKER_SERVICE_POLICY_VERSION,...overrides});
function harness(kind:"files_worker"|"ai_worker"="files_worker",overrides:any={}){let grants=0,nonces=0;const used=new Set<string>();const principal=`velocity_${kind}`,nonce=overrides.nonce||"nonce_synthetic_001",timestamp=overrides.timestamp||now,path=kind==="files_worker"?"/api/worker/files/process":"/api/worker/ai/process",body=overrides.body||JSON.stringify({idempotencyKey:"worker_command_001"}),signature=signWorkerServiceRequest({secret,method:"POST",path,timestamp,nonce,body}),request=new Request(`https://velocity.test${path}${overrides.query||""}`,{method:"POST",headers:{"content-type":"application/json","x-velocity-service-id":principal,"x-velocity-credential-version":"credential-v1","x-velocity-timestamp":timestamp,"x-velocity-nonce":nonce,"x-velocity-signature":overrides.signature||signature},body});return{request,counts:()=>({grants,nonces}),d:{environment:"test",now:()=>new Date(now),secretFor:(id:string)=>overrides.missingSecret?undefined:id===principal?secret:undefined,getGrant:async()=>{grants++;return grant(kind,overrides.grant||{})},reserveNonce:async(i:any)=>{nonces++;if(used.has(i.nonce))return false;used.add(i.nonce);return true},ids:()=>({requestId:"service_request_001",correlationId:"service_correlation_001"})}}}
async function main(){for(const kind of ["files_worker","ai_worker"] as const){const missing=harness(kind,{missingSecret:true}),r=await authorizeWorkerServiceRequest(missing.request,kind,missing.d);assert(!r.ok&&r.code==="SERVICE_AUTH_INVALID"&&missing.counts().grants===0,"missing credential queried grant");const valid=harness(kind),ok=await authorizeWorkerServiceRequest(valid.request,kind,valid.d);assert(ok.ok&&ok.authorization.principal.serviceKind===kind,"valid service denied");assert(ok.ok&&ok.authorization.principal.authentication.humanRolePresent===false,"service modeled as human")}
const invalid=harness("files_worker",{signature:"0".repeat(64)});assert(!(await authorizeWorkerServiceRequest(invalid.request,"files_worker",invalid.d)).ok&&invalid.counts().grants===0,"invalid signature queried grant");const expired=harness("files_worker",{timestamp:"2026-07-16T15:00:00.000Z"});const er=await authorizeWorkerServiceRequest(expired.request,"files_worker",expired.d);assert(!er.ok&&er.code==="SERVICE_REQUEST_EXPIRED","expired request accepted");for(const g of [{status:"inactive"},{revokedAt:now},{environment:"production"},{scopes:["worker.files.claim"]},{tenantIds:[]}]){const h=harness("files_worker",{grant:g}),r=await authorizeWorkerServiceRequest(h.request,"files_worker",h.d);assert(!r.ok,"invalid grant accepted")}
const replay=harness(),first=await authorizeWorkerServiceRequest(replay.request,"files_worker",replay.d),second=await authorizeWorkerServiceRequest(replay.request,"files_worker",replay.d);assert(first.ok&&second.ok&&!first.authorization.requestReplay&&second.authorization.requestReplay&&first.authorization.executionFingerprint===second.authorization.executionFingerprint,"signed replay identity changed");for(const query of ["?tenantId=tenant_beta","?scope=worker.ai.execute","?secret=x"]){const h=harness("files_worker",{query}),r=await authorizeWorkerServiceRequest(h.request,"files_worker",h.d);assert(!r.ok&&h.counts().grants===0,"caller authority accepted")}
const files=fs.readFileSync("app/api/worker/files/process/route.ts","utf8"),ai=fs.readFileSync("app/api/worker/ai/process/route.ts","utf8"),cron=fs.readFileSync("app/api/cron/tick/route.ts","utf8");assert(!/if \(!required\) return/.test(files)&&files.includes("authorizeProductionWorker"),"files fail-open remains");assert(ai.includes("authorizeProductionWorker")&&!files.includes("x-worker-secret")&&!ai.includes("x-worker-secret"),"generic secret remains in workers");assert(files.includes('.where("tenantId", "in"')&&ai.includes('.where("tenantId", "in"'),"global claim remains");assert(files.includes("applicationDocuments")&&files.includes("canonicalPrefix"),"document ownership not validated");assert(!/searchParams\.get\("secret"\)/.test(cron),"cron query secret remains");assert(!files.includes("export async function GET()")&&!ai.includes("export async function GET()"),"worker readiness surface remains");assert(!fs.readFileSync("firestore.rules","utf8").includes("serviceGrants"),"production rules modified for Admin boundary");console.log(`Worker service authorization deterministic regression: ${passed}/${passed} passed`)}main().catch(e=>{console.error(e);process.exit(1)});
