import { initializeApp, deleteApp } from "firebase-admin/app";
import { getFirestore, Timestamp } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { PDFDocument, StandardFonts } from "pdf-lib";
import { WORKER_SERVICE_GRANT_V1, WORKER_SERVICE_POLICY_VERSION } from "../lib/contracts/workerServiceAuth";
import { signWorkerServiceRequest } from "../lib/server/workers/workerServiceAuthCore";
const assert=(v:unknown,m:string)=>{if(!v)throw Error(m)};
async function main(){
  if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_STORAGE_EMULATOR_HOST||process.env.GCLOUD_PROJECT!=="demo-velocity-worker-service")throw Error("DEMO_EMULATORS_REQUIRED");
  console.log("WORKER_SERVICE_AUTH_EMULATOR_CHILD_STARTED");
  Object.assign(process.env,{NODE_ENV:"test",WORKER_FILES_SERVICE_ID:"velocity_files_worker",WORKER_FILES_CREDENTIAL_VERSION:"credential-v1",WORKER_FILES_CREDENTIAL:"synthetic_files_credential_12345678901234567890",WORKER_AI_SERVICE_ID:"velocity_ai_worker",WORKER_AI_CREDENTIAL_VERSION:"credential-v1",WORKER_AI_CREDENTIAL:"synthetic_ai_credential_1234567890123456789012"});
  const app=initializeApp({projectId:process.env.GCLOUD_PROJECT,storageBucket:`${process.env.GCLOUD_PROJECT}.appspot.com`}),db=getFirestore(app),bucket=getStorage(app).bucket();
  const grant=async(kind:"files_worker"|"ai_worker")=>{const id=`velocity_${kind}`,prefix=kind==="files_worker"?"worker.files":"worker.ai";await db.doc(`serviceGrants/${id}`).set({schemaVersion:WORKER_SERVICE_GRANT_V1,grantId:`grant_${kind}`,servicePrincipalId:id,serviceKind:kind,status:"active",credentialVersion:"credential-v1",grantVersion:"grant-v1",environment:"test",scopes:kind==="files_worker"?[`${prefix}.claim`,`${prefix}.read_document`,`${prefix}.process`,`${prefix}.write_result`]:[`${prefix}.claim`,`${prefix}.read_application`,`${prefix}.execute`,`${prefix}.write_result`],tenantIds:["tenant_alpha"],policyVersion:WORKER_SERVICE_POLICY_VERSION})};await grant("files_worker");await grant("ai_worker");
  const pdf=await PDFDocument.create(),page=pdf.addPage([300,300]),font=await pdf.embedFont(StandardFonts.Helvetica);page.drawText("Income verified synthetic document",{x:20,y:250,font,size:12});const bytes=await pdf.save({useObjectStreams:false});
  async function seedFiles(id:string){const documentId=`document_${id}`,storagePath=`tenants/tenant_alpha/applications/${id}/documents/${documentId}/source.pdf`;await db.doc(`applications/${id}`).set({tenantId:"tenant_alpha",ownershipState:"tenant_owned",processingStage:"parsing",sourceDocumentId:documentId,authorizationVersion:"app-v1",companyProfileId:"company_alpha",updatedAt:Timestamp.now()});await db.doc(`applicationDocuments/${documentId}`).set({tenantId:"tenant_alpha",applicationId:id,ownershipState:"tenant_owned",storagePath,authorizationVersion:"doc-v1"});await bucket.file(storagePath).save(Buffer.from(bytes),{metadata:{contentType:"application/pdf"}});return storagePath}
  await db.doc("companyProfiles/company_alpha").set({rulePackId:"rules_alpha"});await db.doc("rulePacks/rules_alpha").set({rulePackVersion:"1",rules:[{ruleId:"income",title:"Income found",pattern:"income",type:"finding"}]});
  const signed=(kind:"files_worker"|"ai_worker",key:string,nonce:string,extra:Record<string,string>={})=>{const path=kind==="files_worker"?"/api/worker/files/process":"/api/worker/ai/process",principal=`velocity_${kind}`,secret=kind==="files_worker"?process.env.WORKER_FILES_CREDENTIAL!:process.env.WORKER_AI_CREDENTIAL!,timestamp=new Date().toISOString(),body=JSON.stringify({idempotencyKey:key}),signature=signWorkerServiceRequest({secret,method:"POST",path,timestamp,nonce,body});return new Request(`http://localhost${path}`,{method:"POST",headers:{"content-type":"application/json","x-velocity-service-id":principal,"x-velocity-credential-version":"credential-v1","x-velocity-timestamp":timestamp,"x-velocity-nonce":nonce,"x-velocity-signature":signature,...extra},body})};
  const filesRoute=await import("../app/api/worker/files/process/route"),aiRoute=await import("../app/api/worker/ai/process/route");
  await seedFiles("application_main");const filesRequest=()=>signed("files_worker","files_main_command","files_main_nonce");const filesResponse=await filesRoute.POST(filesRequest()),filesBody=await filesResponse.json();assert(filesResponse.status===200&&filesBody.ok&&filesBody.worker==="files"&&filesBody.processed===1,"production files route failed");const replayResponse=await filesRoute.POST(filesRequest()),replayBody=await replayResponse.json();assert(replayResponse.status===200&&JSON.stringify(replayBody)===JSON.stringify(filesBody),"completed files retry did not return original receipt");
  const aiRequest=()=>signed("ai_worker","ai_main_command","ai_main_nonce");const aiResponse=await aiRoute.POST(aiRequest()),aiBody=await aiResponse.json();assert(aiResponse.status===200&&aiBody.ok&&aiBody.worker==="ai"&&aiBody.processed===1,"production AI route failed");const aiReplay=await aiRoute.POST(aiRequest());assert(aiReplay.status===200&&JSON.stringify(await aiReplay.json())===JSON.stringify(aiBody),"completed AI retry changed receipt");
  await seedFiles("application_audit_failure");const auditResponse=await filesRoute.POST(signed("files_worker","files_audit_command","files_audit_nonce",{"x-velocity-test-audit-failure":"start"})),auditBody=await auditResponse.json(),auditApp=(await db.doc("applications/application_audit_failure").get()).data()!;assert(auditResponse.status===500&&auditBody.error.code==="AUDIT_REQUIRED"&&auditApp.processingStage==="parsing"&&!auditApp.workerLease,"audit failure did not recover lease");const auditRetry=await filesRoute.POST(signed("files_worker","files_audit_command","files_audit_nonce_retry"));assert(auditRetry.status===200&&(await auditRetry.json()).processed===1,"audit failure was not safely retryable");
  await seedFiles("application_stale");const staleResponse=await filesRoute.POST(signed("files_worker","files_stale_command","files_stale_nonce",{"x-velocity-test-lease-mode":"stale"})),staleApp=(await db.doc("applications/application_stale").get()).data()!;assert(staleResponse.status===500&&staleApp.workerLease?.holder==="stale_lease_holder","stale completion was acknowledged");
  staleApp.processingStage="done";await db.doc("applications/application_stale").update({processingStage:"done"});await seedFiles("application_wrong_principal");const wrongResponse=await filesRoute.POST(signed("files_worker","files_wrong_command","files_wrong_nonce",{"x-velocity-test-lease-mode":"wrong_principal"})),wrongApp=(await db.doc("applications/application_wrong_principal").get()).data()!;assert(wrongResponse.status===500&&wrongApp.workerLease?.servicePrincipalId==="other_service","wrong principal completion was acknowledged");
  const audits=await db.collectionGroup("serviceExecutionAudits").get(),receipts=await db.collectionGroup("serviceExecutionReceipts").get();assert(!audits.empty&&!receipts.empty,"immutable audits or receipts missing");const persisted=JSON.stringify([...audits.docs,...receipts.docs].map(x=>x.data()));assert(!/synthetic_.*credential|borrower|income verified|storagePath/i.test(persisted),"credential or PII persisted");const main=(await db.doc("applications/application_main").get()).data()!;assert(main.ownershipState==="tenant_owned"&&main.decision!=="approved"&&main.decision!=="denied","ownership or human decision changed");
  console.log("WORKER_SERVICE_AUTH_EMULATOR_CHILD_COMPLETED");await deleteApp(app);
}
main().catch(e=>{console.error(e);process.exit(1)});
