import assert from "node:assert/strict";import {buildEvidencePackage,createEvidence,normalizeValue,resolutionKey,type EvidenceInput,type EvidenceObject} from "../lib/evidence";
const region=Object.freeze({unit:"normalized" as const,x:.1,y:.1,width:.4,height:.08,pageWidth:1,pageHeight:1});
function evidence(fieldName:EvidenceInput["fieldName"],rawValue:string,documentId:string,confidence:number,borrowerId:string|null="borrower-1"):EvidenceObject{const normalizedValue=normalizeValue(fieldName,rawValue);const result=createEvidence({fieldName,canonicalValue:normalizedValue,rawValue,normalizedValue,confidence,documentId,documentType:fieldName.startsWith("income")?"Paystub":"Unknown",borrowerId,pageNumber:1,boundingRegion:region,ocrText:`${fieldName}: ${rawValue}`,extractionMethod:"ocr",sourceComponent:"deterministic-extractor",timestamp:"2026-07-22T12:00:00.000Z",version:"1.0.0"});assert(result.ok);return result.value}
let passed=0;function test(name:string,fn:()=>void){fn();passed++;console.log(`PASS: ${name}`)}
test("canonical evidence carries complete immutable provenance",()=>{const e=evidence("borrower.name","Jane Q Borrower","doc-1",.96);assert.match(e.evidenceId,/^[a-f0-9]{64}$/);assert.equal(e.provenance.sourceDocumentId,e.documentId);assert.equal(e.provenance.sourcePageNumber,e.pageNumber);assert.equal(e.validationStatus,"valid");assert(Object.isFrozen(e)&&Object.isFrozen(e.provenance)&&Object.isFrozen(e.boundingRegion))});
test("normalization is deterministic for protected and financial fields",()=>{assert.equal(normalizeValue("borrower.ssn","123-45-6789"),"123456789");assert.equal(normalizeValue("income.amount","$5,000.25"),5000.25);assert.equal(normalizeValue("borrower.dob","7/2/1980"),"1980-07-02");assert.equal(normalizeValue("loan.interest_rate","6.875%"),6.875)});
test("multiple agreeing sources produce support and agreement scores",()=>{const a=evidence("income.amount","$5,000","paystub",.94),b=evidence("income.amount","5000.00","voe",.9);const result=buildEvidencePackage([b,a],"2026-07-22T13:00:00.000Z");assert(result.ok);const r=result.value.resolutions[0];assert.equal(r.reason,"unanimous_evidence");assert.equal(r.supportingEvidenceIds.length,1);assert(r.sourceAssessments.every(x=>x.agreementScore===1&&x.conflictScore===0));assert.equal(result.value.conflicts.length,0)});
test("conflicting sources retain winner support rejection and structured conflict",()=>{const paystub=evidence("income.amount","$5,000","paystub",.98),voe=evidence("income.amount","$5,500","voe",.7),w2=evidence("income.amount","$5,000","w2",.92);const result=buildEvidencePackage([voe,w2,paystub],"2026-07-22T13:00:00.000Z");assert(result.ok);const r=result.value.resolutions[0];assert.equal(r.canonicalValue,5000);assert.equal(r.winningEvidenceId,paystub.evidenceId);assert.deepEqual(r.supportingEvidenceIds,[w2.evidenceId]);assert.deepEqual(r.rejectedEvidenceIds,[voe.evidenceId]);assert.equal(result.value.conflicts.length,1);assert(result.value.conflicts[0].conflictScore>0);assert.equal(r.reason,"highest_adjusted_confidence")});
test("decision inputs reconstruct the complete DTI evidence chain",()=>{const income=evidence("income.amount","$10,000","paystub",.98),housing=evidence("custom.housing_payment","$2,000","closing",.95),debts=evidence("debts.monthly","$1,000","credit",.97);const result=buildEvidencePackage([income,housing,debts],"2026-07-22T13:00:00.000Z",[{fieldName:"custom.dti",borrowerId:"borrower-1",canonicalValue:.3,formula:"(housing_payment + monthly_debts) / monthly_income",inputResolutionKeys:[resolutionKey("income.amount","borrower-1"),resolutionKey("custom.housing_payment","borrower-1"),resolutionKey("debts.monthly","borrower-1")],timestamp:"2026-07-22T13:00:00.000Z",version:"1.0.0"}]);assert(result.ok);const d=result.value.derivedValues[0];assert.equal(d.inputEvidenceIds.length,3);assert.deepEqual(new Set(d.inputEvidenceIds),new Set([income.evidenceId,housing.evidenceId,debts.evidenceId]));assert.match(d.derivedValueId,/^[a-f0-9]{64}$/)});
test("malformed evidence and impossible provenance fail closed",()=>{const bad=createEvidence({fieldName:"income.amount",canonicalValue:1,rawValue:"$1",normalizedValue:1,confidence:2,documentId:"doc",documentType:"Paystub",borrowerId:null,pageNumber:0,boundingRegion:{...region,x:.9,width:.2},ocrText:"",extractionMethod:"ocr",sourceComponent:"extractor",timestamp:"invalid",version:"1"});assert(!bad.ok);assert(bad.errors.length>=4);const good=evidence("income.amount","$1","doc",.9);const tampered={...good,provenance:{...good.provenance,sourcePageNumber:2}};const packageResult=buildEvidencePackage([tampered],"2026-07-22T13:00:00.000Z");assert(!packageResult.ok);assert(packageResult.errors.some(x=>x.ruleId==="evidence.provenance"))});
test("missing derived lineage rejects the whole package",()=>{const income=evidence("income.amount","$1","doc",.9);const result=buildEvidencePackage([income],"2026-07-22T13:00:00.000Z",[{fieldName:"custom.dti",borrowerId:"borrower-1",canonicalValue:.3,formula:"x",inputResolutionKeys:["borrower-1::debts.monthly"],timestamp:"2026-07-22T13:00:00.000Z",version:"1"}]);assert(!result.ok);assert(result.errors.some(x=>x.ruleId==="derived.lineage"))});
console.log(`\nEvidence engine regression result: ${passed}/7 passed`);
