import assert from "node:assert/strict";
import {initializeApp,deleteApp} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
import {getStorage} from "firebase-admin/storage";
import {PDFDocument,StandardFonts} from "pdf-lib";
import {executeApplicationAnalyzeRoute} from "../lib/server/applications/applicationAnalyzeRouteCore";
import {listCanonicalApplicationDocuments,processCanonicalAuthorizedBytes,analyzeCanonicalEvidence,beginCanonicalAnalysis,completeCanonicalAnalysis} from "../lib/server/applications/applicationAnalyzeAdapters";
import {retrieveAuthorizedDocumentBytesCore,DOCUMENT_RETRIEVAL_POLICY} from "../lib/server/documents/authorizedDocumentBytes";
console.log("APPLICATION_ANALYZE_EMULATOR_CHILD_STARTED");
const projectId="demo-velocity-application-analyze",bucketName=`${projectId}.appspot.com`,tenantId="tenant_alpha",applicationId="application_alpha",documentId="document_alpha",path=`tenants/${tenantId}/applications/${applicationId}/documents/${documentId}/synthetic.pdf`,at="2026-07-15T00:00:00.000Z";
const auth:any={schemaVersion:"server-auth-context.v1",principal:{kind:"firebase_user",uid:"user_alpha",authenticationMethod:"session_cookie",tokenIssuedAt:at,authenticatedAt:at,emailVerified:true},verifiedAt:at,requestId:"request_emulator",correlationId:"correlation_emulator"};
const auditEvent=(eventId:string,permission:string,resourceType:string,resourceId:string)=>({schemaVersion:"authorization-audit-event.v1",eventId,requestId:auth.requestId,correlationId:auth.correlationId,evaluatedAt:at,principalKind:"firebase_user",principalReference:"user_alpha",tenantId,membershipVersion:"member_v1",tenantVersion:"tenant_v1",policyVersion:"authorization-policy.v1",permissionVersion:"authorization-permission-registry.v1",permission,resourceType,resourceId,resourceAuthorizationVersion:"auth_v1",decision:"allow",constraintsEvaluated:[],producer:"authorization-orchestrator.v1",classification:"access_allowed"});
async function pdf(){const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),page=doc.addPage();page.drawText("Income: $100",{x:50,y:700,size:24,font});return new Uint8Array(await doc.save())}
function request(key:string){return new Request(`https://velocity.test/api/applications/${applicationId}/analyze`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:key})})}
async function main(){const app=initializeApp({projectId,storageBucket:bucketName}),db=getFirestore(app),bucket=getStorage(app).bucket();const bytes=await pdf();await db.doc(`applications/${applicationId}`).set({ownershipState:"tenant_owned",tenantId,authorizationVersion:"app_auth_v1",status:"New"});await db.doc(`applicationDocuments/${documentId}`).set({applicationId,tenantId,ownershipState:"tenant_owned",storagePath:path,storageBucket:bucketName,authorizationVersion:"doc_auth_v1",status:"uploaded",mimeType:"application/pdf",sizeBytes:bytes.length});await bucket.file(path).save(Buffer.from(bytes),{contentType:"application/pdf",metadata:{metadata:{tenantId,applicationId,documentId}}});const originalApp=JSON.stringify((await db.doc(`applications/${applicationId}`).get()).data()),originalDoc=JSON.stringify((await db.doc(`applicationDocuments/${documentId}`).get()).data());let auditFailure=false,analysisCalls=0;
const appAllow:any={ok:true,context:{tenantId},applicationFacts:{applicationId,resourceAuthorizationVersion:"app_auth_v1"},auditPlan:auditEvent("application_analyze_allow","application.analyze","application",applicationId)};const docAllow:any={ok:true,context:{tenantId},decision:{decision:"allow",permission:"document.read",resourceType:"application_document",resourceId:documentId,tenantId},documentFacts:{applicationId,documentId,tenantId,ownershipState:"tenant_owned",storagePath:path,storageBucket:bucketName,documentAuthorizationVersion:"doc_auth_v1",documentStatus:"uploaded",mimeType:"application/pdf",sizeBytes:bytes.length},auditPlan:{event:auditEvent("document_read_allow","document.read","application_document",documentId),documentPermission:"document.read",documentAuthorizationVersion:"doc_auth_v1"}};
const base:any={now:()=>new Date(at),authenticate:async()=>({ok:true,state:"authenticated",context:auth,authorization:{status:"not_required"}}),authorizeApplication:async()=>appAllow,persistAuthorizationAudit:async(e:any)=>{if(auditFailure)return{ok:false};await db.doc(`tenants/${tenantId}/authorizationAuditEvents/${e.eventId}`).set(e);return{ok:true,receipt:{}}},listDocuments:listCanonicalApplicationDocuments,authorizeDocument:async()=>docAllow,retrieveBytes:async(input:any)=>retrieveAuthorizedDocumentBytesCore(input,{getMetadata:async(p,b)=>{const file=bucket.file(p);try{const[m]=await file.getMetadata();return{exists:true,sizeBytes:Number(m.size),contentType:m.contentType,generation:String(m.generation),metageneration:String(m.metageneration)}}catch{return{exists:false}}},readBytes:async(p)=>new Uint8Array((await bucket.file(p).download())[0])}),processBytes:processCanonicalAuthorizedBytes,analyzeEvidence:async(e:any,v:string)=>{analysisCalls++;return analyzeCanonicalEvidence(e,v)},begin:beginCanonicalAnalysis,complete:completeCanonicalAnalysis};
const execute=(key:string,d:any=base,id:string=applicationId)=>executeApplicationAnalyzeRoute(request(key),id,{idempotencyKey:key},d);
const success:any=await execute("key_success");assert(success.ok);assert.equal(success.documentCount,1);assert.equal(analysisCalls,1);assert((await db.doc(`tenants/${tenantId}/authorizationAuditEvents/application_analyze_allow`).get()).exists);assert((await db.doc(`tenants/${tenantId}/authorizationAuditEvents/document_read_allow`).get()).exists);assert((await db.doc(`tenants/${tenantId}/applications/${applicationId}/analysisAuditEvents/analysis_${(await import("node:crypto")).createHash("sha256").update(JSON.stringify([tenantId,applicationId,"key_success"])).digest("hex").slice(0,32)}`).get()).exists);
const retry:any=await execute("key_success");assert(retry.ok&&retry.writeResult==="already_exists_identical");assert.equal(analysisCalls,1);
const missing:any=await execute("key_missing",{...base,authorizeApplication:async()=>({ok:false,publicError:{code:"RESOURCE_NOT_AVAILABLE",status:404}})},"application_missing"),cross:any=await execute("key_cross",{...base,authorizeApplication:async()=>({ok:false,publicError:{code:"RESOURCE_NOT_AVAILABLE",status:404}})},"application_beta");assert.deepEqual({code:missing.error.code,status:missing.status},{code:cross.error.code,status:cross.status});
assert.equal((await execute("key_cross_doc",{...base,authorizeDocument:async()=>({ok:false})})).error.code,"DOCUMENT_NOT_AVAILABLE");assert.equal((await execute("key_legacy",{...base,authorizeApplication:async()=>({ok:false,publicError:{code:"RESOURCE_NOT_AVAILABLE",status:404}})})).error.code,"RESOURCE_NOT_AVAILABLE");
await bucket.file(path).delete();assert.equal((await execute("key_missing_object")).error.code,"DOCUMENT_NOT_AVAILABLE");await bucket.file(path).save(Buffer.from("malformed"),{contentType:"application/pdf"});await db.doc(`applicationDocuments/${documentId}`).update({sizeBytes:9});const malformed:any=await execute("key_malformed");assert(["DOCUMENT_PROCESSING_FAILED","DOCUMENT_NOT_AVAILABLE"].includes(malformed.error.code));await bucket.file(path).save(Buffer.from(bytes),{contentType:"application/pdf"});await db.doc(`applicationDocuments/${documentId}`).update({sizeBytes:bytes.length});
auditFailure=true;assert.equal((await execute("key_audit_fail")).error.code,"AUDIT_REQUIRED");auditFailure=false;assert.equal((await execute("key_stale",{...base,retrieveBytes:async()=>({ok:false as const,code:"DOCUMENT_AUTHORIZATION_STALE" as const})})).error.code,"DOCUMENT_NOT_AVAILABLE");
let release!:()=>void;const gate=new Promise<void>(r=>release=r),slow={...base,analyzeEvidence:async(e:any,v:string)=>{await gate;return analyzeCanonicalEvidence(e,v)}};const first=execute("key_race",slow);await new Promise(r=>setTimeout(r,300));const second:any=await execute("key_race",slow);assert.equal(second.error.code,"ANALYSIS_ALREADY_RUNNING");release();assert((await first).ok);
assert.equal(JSON.stringify((await db.doc(`applications/${applicationId}`).get()).data()),originalApp);const finalDoc:any=(await db.doc(`applicationDocuments/${documentId}`).get()).data();assert.equal(finalDoc.applicationId,(JSON.parse(originalDoc) as any).applicationId);assert.equal(finalDoc.tenantId,(JSON.parse(originalDoc) as any).tenantId);assert.equal(finalDoc.storagePath,(JSON.parse(originalDoc) as any).storagePath);assert.equal(finalDoc.authorizationVersion,(JSON.parse(originalDoc) as any).authorizationVersion);await deleteApp(app);console.log("APPLICATION_ANALYZE_EMULATOR_CHILD_COMPLETED");console.log("Application analyze route emulator regression: canonical authorization, Storage bytes, processing, evidence, audit, idempotency and concurrency passed")}
main().catch(e=>{console.error(e);process.exitCode=1});
