import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { applicationResourceFixtures as appFixtures } from "../lib/contracts/applicationResourceFixtures";
import { resolverAuth, resolverMembership, resolverTenant } from "../lib/server/authorization/tenantAuthorizationResolverFixtures";
import { resolveTenantAuthorizationContextCore } from "../lib/server/authorization/tenantAuthorizationResolverCore";
import { resolveApplicationResourceFactsCore } from "../lib/server/authorization/applicationResourceResolverCore";
import { evaluateAuthorizationDecisionCore } from "../lib/server/authorization/authorizationDecisionCore";
import { APPLICATION_ACTION_POLICIES } from "../lib/server/authorization/applicationActionPolicies";
import { authorizeApplicationActionCore, normalizeApplicationAuthorizationError } from "../lib/server/authorization/applicationAuthorizationOrchestratorCore";

const at = "2026-07-11T20:00:00.000Z", now = () => new Date(at), auth = resolverAuth("processor_user");
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v));
const makeDeps = (record: any, options: any = {}) => { const steps: string[] = []; let decisions = 0; const tenantId = options.tenantId ?? "tenant_alpha"; return { steps, get decisions() { return decisions; }, dependencies: { onStep: (s: string) => steps.push(s), resolveTenant: (input: any) => resolveTenantAuthorizationContextCore(input, { listDiscoveredTenantIds: async () => options.discovered ?? [tenantId], getTenant: async () => options.tenant ?? resolverTenant(tenantId, options.tenantStatus), getMembership: async () => options.membership ?? resolverMembership(tenantId, "processor_user", options.role ?? "processor", options.membershipStatus) }, now), resolveApplication: (input: any) => options.applicationFailure ? Promise.resolve(options.applicationFailure) : resolveApplicationResourceFactsCore(input, { getApplicationById: async () => record === undefined ? ({ exists: false }) : ({ exists: true, data: clone(record) }) }, now), evaluateDecision: (input: any) => { decisions++; return evaluateAuthorizationDecisionCore(input); } } }; };
const run = async (permission: any, policy: any, record: any, options: any = {}) => { const harness = makeDeps(record, options); const result = await authorizeApplicationActionCore({ authentication: options.authentication ?? clone(auth), ...(options.requestedTenantId !== undefined ? { requestedTenantId: options.requestedTenantId } : {}), applicationId: options.applicationId ?? record?.applicationId ?? "application_alpha", permission, policy, evaluatedAt: at }, harness.dependencies); return { result, harness }; };
let count = 0; const test = async (name: string, fn: () => unknown | Promise<unknown>) => { await fn(); console.log(`PASS ${++count}: ${name}`); };

async function main() {
await test("strict execution order and every layer required for same-tenant read/analyze", async () => { for (const [permission, policy] of [["application.read", APPLICATION_ACTION_POLICIES.read], ["application.analyze", APPLICATION_ACTION_POLICIES.analyze]] as const) { const { result, harness } = await run(permission, policy, { ...appFixtures.tenantOwned, createdBy: "processor_user", assignedProcessorId: "processor_user" }); assert(result.ok); assert.deepEqual(harness.steps, ["validate_authentication", "resolve_tenant", "resolve_application", "convert_resource_facts", "build_request", "evaluate_decision", "build_audit_plan"]); assert.equal(result.decision.decision, "allow"); assert.equal(result.auditPlan.decision, "allow"); assert(Object.isFrozen(result) && Object.isFrozen(result.auditPlan)); } });
await test("authentication, tenant selection, inactive tenant/membership, and unknown role fail closed", async () => { assert(!(await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned, { authentication: {} })).result.ok); assert(!(await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned, { discovered: [] })).result.ok); assert(!(await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned, { discovered: ["tenant_alpha", "tenant_beta"] })).result.ok); assert(!(await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned, { tenantStatus: "suspended" })).result.ok); assert(!(await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned, { membershipStatus: "suspended" })).result.ok); assert(!(await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned, { role: "unknown" })).result.ok); });
await test("application resolver failures stop decision evaluation", async () => { for (const record of [undefined, appFixtures.contradictory, appFixtures.unresolved, appFixtures.pending, appFixtures.rejected]) { const { result, harness } = await run("application.read", APPLICATION_ACTION_POLICIES.read, record, { applicationId: record?.applicationId ?? "application_missing" }); assert(!result.ok); if ([appFixtures.unresolved, appFixtures.pending].includes(record as any)) assert.equal(harness.decisions, 1); else assert.equal(harness.decisions, 0); } });
await test("cross-tenant, permission missing, and ABAC mismatches deny", async () => { const cross = await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.crossTenant); assert(!cross.result.ok && cross.result.publicError.code === "RESOURCE_NOT_AVAILABLE"); const viewerDelete = await run("application.delete", APPLICATION_ACTION_POLICIES.delete, appFixtures.tenantOwned, { role: "viewer" }); assert(!viewerDelete.result.ok && viewerDelete.result.internalReason === "permission_missing"); for (const constraint of ["branch_match", "team_match", "assigned_to_user", "creator_match"] as const) { const scoped = Object.freeze({ ...APPLICATION_ACTION_POLICIES.read, requiredConstraints: Object.freeze([...APPLICATION_ACTION_POLICIES.read.requiredConstraints, constraint]), auditAction: `application.read_${constraint}` }); const mismatch = await run("application.read", scoped, { ...appFixtures.tenantOwned, branchId: "branch_other", teamIds: ["team_other"], assignedProcessorId: "other_user", assignedUnderwriterId: "other_underwriter", createdBy: "other_user" }); assert(!mismatch.result.ok); } });
await test("assigned processor/underwriter and creator matches can pass explicit provisional constraints", async () => { for (const [constraint, record, user] of [["assigned_to_user", { ...appFixtures.tenantOwned, assignedProcessorId: "processor_user" }, "processor_user"], ["assigned_to_user", { ...appFixtures.tenantOwned, assignedUnderwriterId: "underwriter_user" }, "underwriter_user"], ["creator_match", { ...appFixtures.tenantOwned, createdBy: "processor_user" }, "processor_user"]] as const) { const base = constraint === "assigned_to_user" && user === "underwriter_user" ? APPLICATION_ACTION_POLICIES.analyze : APPLICATION_ACTION_POLICIES.read; const scoped = Object.freeze({ ...base, requiredConstraints: Object.freeze([...base.requiredConstraints, constraint]), auditAction: `${base.auditAction}_${constraint}` }); const customAuth = resolverAuth(user); const role = user === "underwriter_user" ? "underwriter" : "processor"; const membership = resolverMembership("tenant_alpha", user, role); const outcome = await run(base.permission, scoped, record, { authentication: customAuth, membership }); assert(outcome.result.ok); } });
await test("public normalization is indistinguishable and PII-safe; audit plans are PII-safe", async () => { const missing = await run("application.read", APPLICATION_ACTION_POLICIES.read, undefined, { applicationId: "application_missing" }), cross = await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.crossTenant); assert(!missing.result.ok && !cross.result.ok); assert.deepEqual(normalizeApplicationAuthorizationError(missing.result), normalizeApplicationAuthorizationError(cross.result)); const allowed = await run("application.read", APPLICATION_ACTION_POLICIES.read, appFixtures.tenantOwned); assert(allowed.result.ok); const text = JSON.stringify(allowed.result.auditPlan); for (const forbidden of ["borrower", "email", "loanAmount", "Synthetic Borrower", "synthetic@example.invalid"]) assert(!text.includes(forbidden)); });
await test("dependency failure maps safely, inputs remain unchanged, and output is deterministic", async () => { const input = clone(appFixtures.tenantOwned), before = JSON.stringify(input); const a = await run("application.read", APPLICATION_ACTION_POLICIES.read, input), b = await run("application.read", APPLICATION_ACTION_POLICIES.read, input); assert.deepEqual(a.result, b.result); assert.equal(JSON.stringify(input), before); const failed = await run("application.read", APPLICATION_ACTION_POLICIES.read, input, { applicationFailure: { ok: false, error: { code: "DEPENDENCY_FAILURE", message: "safe" } } }); assert(!failed.result.ok && failed.result.publicError.code === "INTERNAL_ERROR" && !JSON.stringify(failed.result).includes("Firestore")); });
await test("only dedicated authorized application read, analyze, and workspace routes import orchestration", () => { const files: string[] = []; const walk = (p: string) => fs.readdirSync(p, { withFileTypes: true }).forEach((e) => { const next = path.join(p, e.name); e.isDirectory() ? walk(next) : /\.(ts|tsx)$/.test(e.name) && files.push(next); }); walk(path.join(process.cwd(), "app")); const imports = files.filter((file) => fs.readFileSync(file, "utf8").includes("applicationAuthorizationOrchestrator")); assert.deepEqual(imports.map((file) => path.relative(process.cwd(), file).replace(/\\/g, "/")), ["app/api/applications/[id]/analyze/route.ts", "app/api/applications/[id]/route.ts", "app/api/applications/[id]/workspace/route.ts"]); });
console.log(`Application authorization orchestration regression: ${count}/${count} passed`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
