import assert from "node:assert/strict";
import { deleteApp, initializeApp } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { resolverAuth, resolverMembership, resolverTenant } from "../lib/server/authorization/tenantAuthorizationResolverFixtures";
import { resolveTenantAuthorizationContextCore } from "../lib/server/authorization/tenantAuthorizationResolverCore";
import { resolveApplicationResourceFactsCore } from "../lib/server/authorization/applicationResourceResolverCore";
import { evaluateAuthorizationDecisionCore } from "../lib/server/authorization/authorizationDecisionCore";
import { APPLICATION_ACTION_POLICIES } from "../lib/server/authorization/applicationActionPolicies";
import { authorizeApplicationActionCore } from "../lib/server/authorization/applicationAuthorizationOrchestratorCore";

console.log("EMULATOR_APPLICATION_AUTHORIZATION_EXECUTION_STARTED");
async function main() {
  const projectId = process.env.GCLOUD_PROJECT || "demo-velocity-application-authorization"; const app = initializeApp({ projectId }, `application-authorization-${Date.now()}`); const db = getFirestore(app); const nowText = "2026-07-11T20:00:00.000Z", now = () => new Date(nowText);
  const users = { processor: "processor_user", viewer: "viewer_user" }; for (const [user, role] of [[users.processor, "processor"], [users.viewer, "viewer"]] as const) { await db.doc(`userTenantMemberships/${user}/tenants/tenant_alpha`).set({ tenantId: "tenant_alpha" }); await db.doc(`tenants/tenant_alpha/members/${user}`).set(resolverMembership("tenant_alpha", user, role)); } await db.doc("tenants/tenant_alpha").set(resolverTenant("tenant_alpha")); await db.doc("tenants/tenant_beta").set(resolverTenant("tenant_beta"));
  const applications: Record<string, any> = { application_alpha: { ownershipState: "tenant_owned", tenantId: "tenant_alpha", authorizationVersion: "auth-v1", status: "New", assignedProcessorId: users.processor, borrowerName: "Synthetic Borrower", email: "synthetic@example.invalid", loanAmount: 100000 }, application_beta: { ownershipState: "tenant_owned", tenantId: "tenant_beta", authorizationVersion: "auth-v1", status: "New" }, application_legacy: { status: "New", companyProfileId: "tenant_alpha", createdBy: users.processor } }; for (const [id, data] of Object.entries(applications)) await db.doc(`applications/${id}`).set(data);
  const before = JSON.stringify((await db.collection("applications").orderBy("__name__").get()).docs.map((d) => [d.id, d.data()])); let lookupId = "";
  const dependencies = { resolveTenant: (input: any) => resolveTenantAuthorizationContextCore(input, { listDiscoveredTenantIds: async (uid) => (await db.collection(`userTenantMemberships/${uid}/tenants`).get()).docs.map((d) => d.id), getTenant: async (id) => (await db.doc(`tenants/${id}`).get()).data(), getMembership: async (id, uid) => (await db.doc(`tenants/${id}/members/${uid}`).get()).data() }, now), resolveApplication: (input: any) => resolveApplicationResourceFactsCore(input, { getApplicationById: async (id) => { lookupId = id; const snap = await db.doc(`applications/${id}`).get(); return snap.exists ? { exists: true, data: snap.data() } : { exists: false }; } }, now), evaluateDecision: evaluateAuthorizationDecisionCore };
  const authorize = (applicationId: string, user = users.processor, permission: any = "application.read", policy: any = APPLICATION_ACTION_POLICIES.read, requestedTenantId: any = "tenant_alpha") => authorizeApplicationActionCore({ authentication: resolverAuth(user), requestedTenantId, applicationId, permission, policy, evaluatedAt: nowText }, dependencies);
  const allowed = await authorize("application_alpha"); assert(allowed.ok && allowed.decision.decision === "allow" && lookupId === "application_alpha");
  const cross = await authorize("application_beta"), missing = await authorize("application_missing"), legacy = await authorize("application_legacy"); assert(!cross.ok && !missing.ok && !legacy.ok); assert.deepEqual(cross.publicError, missing.publicError); assert.equal(cross.publicError.code, "RESOURCE_NOT_AVAILABLE");
  const persistedAuthority = await authorize("application_alpha", users.processor, "application.read", APPLICATION_ACTION_POLICIES.read, "tenant_beta"); assert(!persistedAuthority.ok);
  const forgedRole = await authorize("application_alpha", users.viewer, "application.delete", APPLICATION_ACTION_POLICIES.delete); assert(!forgedRole.ok && forgedRole.internalReason === "permission_missing");
  const assignmentPolicy = Object.freeze({ ...APPLICATION_ACTION_POLICIES.read, requiredConstraints: Object.freeze([...APPLICATION_ACTION_POLICIES.read.requiredConstraints, "assigned_to_user"]), auditAction: "application.read_assigned" }); const forgedAssignment = await authorize("application_alpha", users.viewer, "application.read", assignmentPolicy); assert(!forgedAssignment.ok && forgedAssignment.internalReason === "assignment_scope_denied");
  const safe = JSON.stringify(allowed.ok ? allowed.auditPlan : allowed); for (const forbidden of ["borrower", "email", "loanAmount", "Synthetic Borrower", "synthetic@example.invalid"]) assert(!safe.includes(forbidden));
  const failed = await authorizeApplicationActionCore({ authentication: resolverAuth(users.processor), requestedTenantId: "tenant_alpha", applicationId: "application_alpha", permission: "application.read", policy: APPLICATION_ACTION_POLICIES.read, evaluatedAt: nowText }, { ...dependencies, resolveApplication: async () => ({ ok: false, error: { code: "DEPENDENCY_FAILURE", message: "safe" } }) }); assert(!failed.ok && failed.publicError.code === "INTERNAL_ERROR");
  const after = JSON.stringify((await db.collection("applications").orderBy("__name__").get()).docs.map((d) => [d.id, d.data()])); assert.equal(after, before);
  await deleteApp(app); console.log("EMULATOR_APPLICATION_AUTHORIZATION_EXECUTION_COMPLETED"); console.log("Application authorization orchestration emulator regression: 12/12 passed");
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
