import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { authorizationAuditFixtures as f } from "../lib/contracts/authorizationAuditFixtures";
import { canonicalSerializeAuthorizationAuditEvent, fingerprintAuthorizationAuditEvent, parseAuthorizationAuditPersistenceReceipt, persistAuthorizationAuditEventCore, type AuthorizationAuditPersistenceRepository } from "../lib/server/authorization/authorizationAuditPersistenceCore";

const at = "2026-07-12T04:00:00.000Z", clone = <T>(v: T): T => JSON.parse(JSON.stringify(v));
const memory = () => { const documents = new Map<string, any>(); const repository: AuthorizationAuditPersistenceRepository = { createOrRead: async (key, document) => documents.has(key) ? { result: "existing", document: clone(documents.get(key)) } : (documents.set(key, clone(document)), { result: "created" }) }; return { documents, repository }; };
let count = 0; const test = async (name: string, fn: () => unknown | Promise<unknown>) => { await fn(); console.log(`PASS ${++count}: ${name}`); };
async function main() {
await test("canonical serialization and SHA-256 fingerprint are stable and material", () => { const a = clone(f.events.allowed), reordered = Object.fromEntries(Object.entries(a).reverse()); assert.equal(canonicalSerializeAuthorizationAuditEvent(a as any), canonicalSerializeAuthorizationAuditEvent(reordered as any)); assert.equal(fingerprintAuthorizationAuditEvent(a as any), fingerprintAuthorizationAuditEvent(reordered as any)); assert.notEqual(fingerprintAuthorizationAuditEvent(a as any), fingerprintAuthorizationAuditEvent({ ...a, resourceAuthorizationVersion: "application.v2" } as any)); });
await test("tenant allow and deny create canonical immutable receipts without mutating inputs", async () => { for (const event of [f.events.allowed, f.events.denied]) { const db = memory(), input = clone(event), before = JSON.stringify(input); const result = await persistAuthorizationAuditEventCore(input, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: at }, db.repository); assert(result.ok && result.receipt.writeResult === "created" && result.receipt.canonicalPath === `tenants/tenant_alpha/authorizationAuditEvents/${event.eventId}`); assert(parseAuthorizationAuditPersistenceReceipt(result.receipt).ok); assert(Object.isFrozen(result.receipt)); assert.equal(JSON.stringify(input), before); assert.equal(db.documents.size, 1); } });
await test("identical retry is idempotent and conflicting retry fails closed", async () => { const db = memory(); const first = await persistAuthorizationAuditEventCore(f.events.allowed, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: at }, db.repository), retry = await persistAuthorizationAuditEventCore(f.events.allowed, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: "2026-07-12T05:00:00.000Z" }, db.repository), conflict = await persistAuthorizationAuditEventCore({ ...f.events.allowed, classification: "security_event" }, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: at }, db.repository); assert(first.ok && retry.ok && retry.receipt.writeResult === "already_exists_identical" && retry.receipt.persistedAt === at); assert(!conflict.ok && conflict.error.code === "AUDIT_EVENT_CONFLICT"); assert.equal(db.documents.size, 1); });
await test("tenant ownership and canonical paths cannot be overridden", async () => { const db = memory(); const missing = await persistAuthorizationAuditEventCore({ ...f.events.allowed, tenantId: undefined }, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: at }, db.repository), mismatch = await persistAuthorizationAuditEventCore(f.events.allowed, { scope: "tenant", tenantId: "tenant_beta", persistedAt: at }, db.repository); assert(!missing.ok && missing.error.code === "AUDIT_TENANT_REQUIRED"); assert(!mismatch.ok && mismatch.error.code === "AUDIT_TENANT_MISMATCH"); assert.equal(db.documents.size, 0); assert(!JSON.stringify(mismatch).includes("tenants/")); });
await test("platform-security path accepts only tenantless security events", async () => { const db = memory(), event = { ...f.events.unknownRole, tenantId: undefined, eventId: "event_platform_security", classification: "security_event" }; const result = await persistAuthorizationAuditEventCore(event, { scope: "platform_security", persistedAt: at }, db.repository); assert(result.ok && result.receipt.canonicalPath === "platformSecurity/authorizationAuditEvents/events/event_platform_security" && !result.receipt.tenantId); assert(!(await persistAuthorizationAuditEventCore(f.events.allowed, { scope: "platform_security", persistedAt: at }, db.repository)).ok); });
await test("malformed and PII-shaped events fail before writes", async () => { const db = memory(); for (const event of [{}, { ...f.events.allowed, borrowerName: "Synthetic Borrower" }, { ...f.events.allowed, evaluatedAt: "bad" }, { ...f.events.allowed, eventId: "bad/id" }, { ...f.events.allowed, permissionVersion: "bad version" }]) { const result = await persistAuthorizationAuditEventCore(event, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: at }, db.repository); assert(!result.ok && result.error.code === "AUDIT_EVENT_INVALID"); } assert.equal(db.documents.size, 0); });
await test("dependency failures map safely", async () => { const result = await persistAuthorizationAuditEventCore(f.events.allowed, { scope: "tenant", tenantId: "tenant_alpha", persistedAt: at }, { createOrRead: async () => { throw new Error("raw firestore borrower payload"); } }); assert(!result.ok && result.error.code === "AUDIT_DEPENDENCY_FAILURE" && !JSON.stringify(result).includes("firestore")); });
await test("repository is create/read only and only the dedicated application routes import the sink", () => { const db = memory(); assert.deepEqual(Object.keys(db.repository), ["createOrRead"]); const files: string[] = []; const walk = (p: string) => fs.readdirSync(p, { withFileTypes: true }).forEach((e) => { const next = path.join(p, e.name); e.isDirectory() ? walk(next) : /\.(ts|tsx)$/.test(e.name) && files.push(next); }); walk(path.join(process.cwd(), "app")); const imports = files.filter((file) => fs.readFileSync(file, "utf8").includes("authorizationAuditPersistence")); assert.deepEqual(imports.map((file) => path.relative(process.cwd(), file).replace(/\\/g, "/")), ["app/api/applications/[id]/analyze/route.ts", "app/api/applications/[id]/route.ts"]); });
console.log(`Authorization audit persistence regression: ${count}/${count} passed`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
