import {deleteApp,initializeApp} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
import {SCHEDULER_GRANT_V1,SCHEDULER_POLICY_VERSION} from "../lib/contracts/schedulerServiceAuth";
import {WORKER_SERVICE_GRANT_V1,WORKER_SERVICE_POLICY_VERSION} from "../lib/contracts/workerServiceAuth";
import {signSchedulerRequest} from "../lib/server/scheduler/schedulerServiceAuthCore";
const assert=(v:unknown,m:string)=>{if(!v)throw Error(m)};
async function main(){
 if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_STORAGE_EMULATOR_HOST||process.env.GCLOUD_PROJECT!=="demo-velocity-scheduler-service")throw Error("DEMO_EMULATORS_REQUIRED");
 console.log("SCHEDULER_SERVICE_AUTH_EMULATOR_CHILD_STARTED");
 Object.assign(process.env,{NODE_ENV:"test",SCHEDULER_SERVICE_ID:"velocity_scheduler",SCHEDULER_CREDENTIAL_VERSION:"credential-v1",SCHEDULER_CREDENTIAL:"synthetic_scheduler_credential_12345678901234567890",WORKER_FILES_SERVICE_ID:"velocity_files_worker",WORKER_FILES_CREDENTIAL_VERSION:"credential-v1",WORKER_FILES_CREDENTIAL:"synthetic_files_credential_12345678901234567890",WORKER_AI_SERVICE_ID:"velocity_ai_worker",WORKER_AI_CREDENTIAL_VERSION:"credential-v1",WORKER_AI_CREDENTIAL:"synthetic_ai_credential_1234567890123456789012"});
 const app=initializeApp({projectId:process.env.GCLOUD_PROJECT,storageBucket:`${process.env.GCLOUD_PROJECT}.appspot.com`}),db=getFirestore(app);
 await db.doc("serviceGrants/velocity_scheduler").set({schemaVersion:SCHEDULER_GRANT_V1,grantId:"scheduler_grant",servicePrincipalId:"velocity_scheduler",serviceKind:"scheduler",status:"active",credentialVersion:"credential-v1",grantVersion:"grant-v1",environment:"test",scopes:["scheduler.tick","scheduler.dispatch_files_worker","scheduler.dispatch_ai_worker"],workerTargets:["files_worker","ai_worker"],tenantIds:["tenant_alpha"],policyVersion:SCHEDULER_POLICY_VERSION});
 for(const kind of ["files_worker","ai_worker"] as const){const id=`velocity_${kind}`,p=kind==="files_worker"?"worker.files":"worker.ai";await db.doc(`serviceGrants/${id}`).set({schemaVersion:WORKER_SERVICE_GRANT_V1,grantId:`grant_${kind}`,servicePrincipalId:id,serviceKind:kind,status:"active",credentialVersion:"credential-v1",grantVersion:"grant-v1",environment:"test",scopes:kind==="files_worker"?[`${p}.claim`,`${p}.read_document`,`${p}.process`,`${p}.write_result`]:[`${p}.claim`,`${p}.read_application`,`${p}.execute`,`${p}.write_result`],tenantIds:["tenant_alpha"],policyVersion:WORKER_SERVICE_POLICY_VERSION})}
 const route=await import("../app/api/cron/tick/route");let n=0;
 const req=(key:string,mode:string,nonce=`scheduler_nonce_${++n}`,extra:Record<string,string>={})=>{const body=JSON.stringify({idempotencyKey:key,runMode:mode}),timestamp=new Date().toISOString(),signature=signSchedulerRequest({secret:process.env.SCHEDULER_CREDENTIAL!,method:"POST",path:"/api/cron/tick",timestamp,nonce,body});return new Request("http://localhost/api/cron/tick",{method:"POST",headers:{"content-type":"application/json","x-velocity-service-id":"velocity_scheduler","x-velocity-credential-version":"credential-v1","x-velocity-timestamp":timestamp,"x-velocity-nonce":nonce,"x-velocity-signature":signature,...extra},body})};
 for(const mode of ["files_only","ai_only","files_then_ai"]){const r=await route.POST(req(`mode_${mode}_command`,mode)),b=await r.json();assert(r.status===200&&b.ok&&b.workerResults.length===(mode==="files_then_ai"?2:1),`${mode} failed:${r.status}:${JSON.stringify(b)}`)}
 const replay=req("receipt_command","files_only","scheduler_receipt_nonce"),first=await route.POST(replay),firstBody=await first.json(),second=await route.POST(replay),secondBody=await second.json();assert(first.status===200&&second.status===200&&JSON.stringify(firstBody)===JSON.stringify(secondBody),"immutable receipt retry failed");
 const conflictA=await route.POST(req("conflict_command","files_only")),conflictB=await route.POST(req("conflict_command","ai_only"));assert(conflictA.status===200&&conflictB.status===409&&(await conflictB.json()).error.code==="SCHEDULER_COMMAND_CONFLICT","conflict not rejected");
 const concurrent=req("concurrent_command","files_then_ai","scheduler_concurrent_nonce"),pair=await Promise.all([route.POST(concurrent),route.POST(concurrent)]),pairBodies=await Promise.all(pair.map(x=>x.json()));assert((pair.filter(x=>x.status===200).length===1&&pair.filter(x=>x.status===409).length===1)||(pair.every(x=>x.status===200)&&JSON.stringify(pairBodies[0])===JSON.stringify(pairBodies[1])),"concurrent dispatch was not single-owner or immutable-receipt equivalent");
 const before=(await db.collection("serviceExecutionCommands").get()).size,auditFail=await route.POST(req("audit_failure_command","files_only",undefined,{"x-velocity-test-audit-failure":"start"})),after=(await db.collection("serviceExecutionCommands").get()).size;assert(auditFail.status===503&&(await auditFail.json()).error.code==="AUDIT_REQUIRED"&&before===after,"start audit failure dispatched");
 const partial=await route.POST(req("partial_command","files_then_ai",undefined,{"x-velocity-test-dispatch-failure":"ai_worker"})),partialCommands=await db.collection("schedulerExecutionCommands").where("idempotencyKey","==","partial_command").get();assert(partial.status===503&&!partialCommands.empty&&partialCommands.docs[0].data().workerResults.length===1,"partial state not recoverable");
 const audits=await db.collection("schedulerAuditEvents").get(),receipts=await db.collection("schedulerExecutionCommands").where("status","==","completed").get(),workerReceipts=await db.collection("serviceExecutionCommands").where("status","==","completed").get();assert(!audits.empty&&!receipts.empty&&!workerReceipts.empty,"audits/receipts missing");const persisted=JSON.stringify([...audits.docs,...receipts.docs,...workerReceipts.docs].map(d=>d.data()));assert(!/synthetic_.*credential|signature|borrower|document|storagePath|bucket/i.test(persisted),"secret or PII persisted");assert((await db.collection("applications").get()).empty,"human/business state created");
 console.log("SCHEDULER_SERVICE_AUTH_EMULATOR_CHILD_COMPLETED");await deleteApp(app);
}
main().catch(e=>{console.error(e);process.exit(1)});
