import "server-only";
import {createHash} from "node:crypto";
import {FieldPath,getFirestore} from "firebase-admin/firestore";
import {defaultAdminApp} from "../auth/firebaseAdminAuthAdapter";
import {resolveTenantAuthorizationContext} from "../authorization/tenantAuthorizationResolver";
import {permissionsForRole} from "../authorization/permissionPolicy";
import type {ServerAuthContextV1} from "../../contracts/serverAuth";
import type {AuthorizationPermission} from "../../contracts/authorization";
import {ENTERPRISE_FEATURES,FEATURE_FLAG_VERSION,GOVERNANCE_POLICY_VERSION,GOVERNANCE_ROLE_REGISTRY,PERMISSION_REGISTRY,TEAM_VERSION} from "../../governance/enterpriseGovernance";
import {AUTHORITY_REFRESH_MESSAGE,auditAuthorityRejection,enforceAuthorityInTransaction,readAuthoritySnapshot} from "../identity/identityAuthorityEnforcement";

const db=()=>getFirestore(defaultAdminApp()),ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,POLICY="enterprise-governance-admin.v1";
const failure=(auth:ServerAuthContextV1,code:string,status=403)=>Object.freeze({ok:false as const,status,error:{code,message:code.includes("AUTHORITY")||code.includes("MEMBERSHIP")?AUTHORITY_REFRESH_MESSAGE:"The governance operation is unavailable.",...(code.includes("AUTHORITY")||code.includes("MEMBERSHIP")?{refreshRequired:true,recoverable:true}:{})},requestId:auth.requestId,correlationId:auth.correlationId});
async function authorize(auth:ServerAuthContextV1,tenantId:string|undefined,permission:AuthorizationPermission){const result=await resolveTenantAuthorizationContext({authentication:auth,...(tenantId?{requestedTenantId:tenantId}:{})});if(!result.ok)return failure(auth,result.error.code,result.error.status);if(!permissionsForRole(result.context.role).includes(permission))return failure(auth,"FORBIDDEN",403);return{ok:true as const,context:result.context}}
const iso=(v:any)=>v?.toDate?.().toISOString?.()||String(v||"");
const principal=(auth:ServerAuthContextV1)=>auth.principal.kind==="firebase_user"?auth.principal.uid:"invalid";
const audit=(tx:any,tenantId:string,auth:ServerAuthContextV1,id:string,action:string,entityType:string,entityId:string)=>tx.create(db().doc(`tenants/${tenantId}/governanceAuditEvents/${id}`),{schemaVersion:"governance-audit-event.v1",action,outcome:"allowed",entityType,entityId,principalReference:principal(auth),requestId:auth.requestId,correlationId:auth.correlationId,policyVersion:POLICY,piiPresent:false,createdAt:new Date().toISOString()});

export async function readEnterpriseGovernance(auth:ServerAuthContextV1,tenantId?:string){
 const allowed=await authorize(auth,tenantId,"configuration.read");if(!allowed.ok)return allowed;const root=`tenants/${allowed.context.tenantId}`;
 const [tenant,members,teams,flags,policies,audits,authority]=await Promise.all([db().doc(root).get(),db().collection(`${root}/members`).orderBy(FieldPath.documentId()).limit(200).get(),db().collection(`${root}/teams`).orderBy(FieldPath.documentId()).limit(100).get(),db().doc(`${root}/configuration/featureFlags`).get(),db().collection(`${root}/governancePolicies`).orderBy("version","desc").limit(25).get(),db().collection(`${root}/governanceAuditEvents`).orderBy(FieldPath.documentId(),"desc").limit(50).get(),readAuthoritySnapshot(allowed.context.tenantId,allowed.context.authentication.principalId)]);if(!authority||authority.membershipStatus!=="active")return failure(auth,"MEMBERSHIP_INACTIVE",403);
 const canManage=permissionsForRole(allowed.context.role).includes("configuration.manage"),canManageMembers=permissionsForRole(allowed.context.role).includes("membership.manage");
 const projection=Object.freeze({schemaVersion:"enterprise-governance-projection.v1",organization:Object.freeze({tenantId:allowed.context.tenantId,name:String(tenant.data()?.name||"Organization"),status:String(tenant.data()?.status||"active"),version:iso(tenant.data()?.updatedAt)||allowed.context.tenantVersion}),currentActor:Object.freeze({userId:allowed.context.authentication.principalId,role:allowed.context.role,permissions:permissionsForRole(allowed.context.role),canManage,canManageMembers}),members:Object.freeze(members.docs.map(d=>{const x=d.data();return Object.freeze({userId:d.id,role:String(x.role||"unknown"),status:String(x.membershipStatus||"unknown"),teamIds:Object.freeze(Array.isArray(x.teamIds)?x.teamIds:[]),lastActivityAt:iso(x.lastActivityAt||x.updatedAt),version:String(x.membershipVersion||iso(x.updatedAt)||"legacy")})})),teams:Object.freeze(teams.docs.map(d=>{const x=d.data();return Object.freeze({teamId:d.id,name:String(x.name||d.id),status:String(x.status||"active"),managerIds:Object.freeze(x.managerIds||[]),memberIds:Object.freeze(x.memberIds||[]),underwriterIds:Object.freeze(x.underwriterIds||[]),processorIds:Object.freeze(x.processorIds||[]),version:Number(x.version||1)})})),roles:Object.freeze(Object.values(GOVERNANCE_ROLE_REGISTRY)),permissions:PERMISSION_REGISTRY,featureFlags:Object.freeze({schemaVersion:FEATURE_FLAG_VERSION,version:Number(flags.data()?.version||0),values:Object.freeze(Object.fromEntries(ENTERPRISE_FEATURES.map(feature=>[feature,flags.exists?flags.data()?.values?.[feature]!==false:true])))}),policies:Object.freeze(policies.docs.map(d=>Object.freeze({policyId:d.id,type:String(d.data().type||"unknown"),version:Number(d.data().version||0),status:String(d.data().status||"active"),createdAt:iso(d.data().createdAt)}))),audit:Object.freeze(audits.docs.map(d=>Object.freeze({eventId:d.id,action:String(d.data().action||"unknown"),outcome:String(d.data().outcome||d.data().decision||"unknown"),entityType:String(d.data().entityType||"governance"),entityId:String(d.data().entityId||""),actor:String(d.data().principalReference||"system"),createdAt:iso(d.data().createdAt)}))),safeDefaults:Object.freeze({legacyMemberships:"adapted_from_existing_role",missingFeatureFlags:"enabled_for_existing_features",unknownRole:"denied",policyFailure:"denied"})});
 return Object.freeze({ok:true as const,status:200,governance:Object.freeze({...projection,currentActor:Object.freeze({...projection.currentActor,membershipVersion:authority.membershipVersion,authorizationVersion:authority.authorizationVersion})}),requestId:auth.requestId,correlationId:auth.correlationId});
}

export async function executeGovernanceCommand(auth:ServerAuthContextV1,tenantId:string|undefined,raw:unknown){
 const x=raw as any,allowedKeys=["commandType","idempotencyKey","expectedVersion","expectedMembershipVersion","expectedAuthorizationVersion","teamId","name","managerIds","memberIds","underwriterIds","processorIds","feature","enabled","policyType","policy"];if(!x||typeof x!=="object"||Array.isArray(x)||Object.keys(x).some(k=>!allowedKeys.includes(k))||!ID.test(x.idempotencyKey||"")||!["create_team","rename_team","archive_team","set_feature","publish_policy"].includes(x.commandType))return failure(auth,"COMMAND_INVALID",400);
 const permission:AuthorizationPermission="configuration.manage",allowed=await authorize(auth,tenantId,permission);if(!allowed.ok)return allowed;const tenant=allowed.context.tenantId;if(!Number.isSafeInteger(x.expectedMembershipVersion)||typeof x.expectedAuthorizationVersion!=="string"){await auditAuthorityRejection({auth,tenantId:tenant,commandType:String(x.commandType),code:"AUTHORITY_VERSION_REQUIRED"});return failure(auth,"AUTHORITY_VERSION_REQUIRED",409)}const commandId=createHash("sha256").update(`${tenant}:${principal(auth)}:${x.idempotencyKey}`).digest("hex"),commandRef=db().doc(`tenants/${tenant}/governanceCommands/${commandId}`),fingerprint=createHash("sha256").update(JSON.stringify([x,POLICY])).digest("hex");
 try{return await db().runTransaction(async tx=>{const [existing,actorAuthority]=await Promise.all([tx.get(commandRef),enforceAuthorityInTransaction(tx,{tenantId:tenant,userId:allowed.context.authentication.principalId,expected:{expectedMembershipVersion:x.expectedMembershipVersion,expectedAuthorizationVersion:x.expectedAuthorizationVersion}})]);if(!actorAuthority.ok){tx.create(db().doc(`tenants/${tenant}/authorityDenialAuditEvents/${commandId}:authority`),{schemaVersion:"identity-authority-denial-audit.v1",classification:"authority_stale_or_inactive",reasonCode:actorAuthority.code,commandType:x.commandType,principalReference:principal(auth),requestId:auth.requestId,correlationId:auth.correlationId,piiPresent:false,createdAt:new Date().toISOString()});return failure(auth,actorAuthority.code,409)}if(existing.exists){if(existing.data()?.fingerprint!==fingerprint)return failure(auth,"COMMAND_CONFLICT",409);return Object.freeze({ok:true as const,status:200,receipt:existing.data()?.receipt,requestId:auth.requestId,correlationId:auth.correlationId})}
  let receipt:any;
  if(x.commandType==="create_team"){if(!ID.test(x.teamId||"")||typeof x.name!=="string"||!x.name.trim()||x.name.length>120)return failure(auth,"COMMAND_INVALID",400);const ref=db().doc(`tenants/${tenant}/teams/${x.teamId}`),current=await tx.get(ref);if(current.exists)return failure(auth,"TEAM_EXISTS",409);const data={schemaVersion:TEAM_VERSION,teamId:x.teamId,name:x.name.trim(),status:"active",managerIds:Object.freeze(x.managerIds||[]),memberIds:Object.freeze(x.memberIds||[]),underwriterIds:Object.freeze(x.underwriterIds||[]),processorIds:Object.freeze(x.processorIds||[]),version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};tx.create(ref,data);receipt={teamId:x.teamId,version:1}}
  else if(x.commandType==="rename_team"||x.commandType==="archive_team"){if(!ID.test(x.teamId||"")||!Number.isInteger(x.expectedVersion))return failure(auth,"COMMAND_INVALID",400);const ref=db().doc(`tenants/${tenant}/teams/${x.teamId}`),current=await tx.get(ref);if(!current.exists)return failure(auth,"TEAM_NOT_FOUND",404);if(Number(current.data()?.version)!==x.expectedVersion)return failure(auth,"GOVERNANCE_STALE",409);if(x.commandType==="rename_team"&&(typeof x.name!=="string"||!x.name.trim()||x.name.length>120))return failure(auth,"COMMAND_INVALID",400);if(x.commandType==="archive_team"&&["memberIds","managerIds","underwriterIds","processorIds"].some(key=>Array.isArray(current.data()?.[key])&&current.data()![key].length))return failure(auth,"TEAM_NOT_EMPTY",409);const version=x.expectedVersion+1;tx.update(ref,x.commandType==="rename_team"?{name:x.name.trim(),version,updatedAt:new Date().toISOString()}:{status:"archived",version,updatedAt:new Date().toISOString()});receipt={teamId:x.teamId,version}}
  else if(x.commandType==="set_feature"){if(!ENTERPRISE_FEATURES.includes(x.feature)||typeof x.enabled!=="boolean"||!Number.isInteger(x.expectedVersion))return failure(auth,"COMMAND_INVALID",400);const ref=db().doc(`tenants/${tenant}/configuration/featureFlags`),current=await tx.get(ref),version=Number(current.data()?.version||0);if(version!==x.expectedVersion)return failure(auth,"GOVERNANCE_STALE",409);tx.set(ref,{schemaVersion:FEATURE_FLAG_VERSION,version:version+1,values:{...(current.data()?.values||{}),[x.feature]:x.enabled},updatedAt:new Date().toISOString()},{merge:false});receipt={feature:x.feature,enabled:x.enabled,version:version+1}}
  else{if(!ID.test(x.policyType||"")||!x.policy||typeof x.policy!=="object"||Array.isArray(x.policy)||!Number.isInteger(x.expectedVersion))return failure(auth,"COMMAND_INVALID",400);const policyId=`${x.policyType}:v${x.expectedVersion+1}`,ref=db().doc(`tenants/${tenant}/governancePolicies/${policyId}`);tx.create(ref,{schemaVersion:GOVERNANCE_POLICY_VERSION,policyId,type:x.policyType,version:x.expectedVersion+1,status:"active",configuration:x.policy,createdBy:principal(auth),createdAt:new Date().toISOString(),piiPresent:false});receipt={policyId,version:x.expectedVersion+1}}
  audit(tx,tenant,auth,`${commandId}:audit`,x.commandType,x.commandType.includes("team")?"team":x.commandType==="set_feature"?"feature":"policy",String(x.teamId||x.feature||x.policyType));tx.create(commandRef,{schemaVersion:"governance-command.v1",fingerprint,status:"completed",receipt,createdAt:new Date().toISOString()});return Object.freeze({ok:true as const,status:200,receipt,requestId:auth.requestId,correlationId:auth.correlationId})})}catch{return failure(auth,"OPERATION_FAILED",500)}
}
