import "server-only";
import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { FieldPath, getFirestore } from "firebase-admin/firestore";
import { defaultAdminApp } from "../auth/firebaseAdminAuthAdapter";
import { resolveTenantAuthorizationContext } from "../authorization/tenantAuthorizationResolver";
import { permissionsForRole } from "../authorization/permissionPolicy";
import type { ServerAuthContextV1 } from "../../contracts/serverAuth";
import type { AuthorizationPermission } from "../../contracts/authorization";

const db=()=>getFirestore(defaultAdminApp()),ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,MAX_PAGE=50,MAX_EXPORT=500,POLICY="governance-admin-audit-policy.v1";
const principal=(auth:ServerAuthContextV1)=>auth.principal.kind==="firebase_user"?auth.principal.uid:"invalid";
const safe=(code:string,status:number,a:ServerAuthContextV1)=>Object.freeze({ok:false as const,status,error:{code,message:"The requested governance operation is unavailable."},requestId:a.requestId,correlationId:a.correlationId});
const cursorSecret=()=>{const value=process.env.GOVERNANCE_CURSOR_SECRET||(process.env.GCLOUD_PROJECT?.startsWith("demo-")?"demo-governance-cursor-secret-000001":"");if(value.length<32)throw Error("CURSOR_SECRET_REQUIRED");return value};
const encode=(payload:object)=>{const body=Buffer.from(JSON.stringify(payload)).toString("base64url"),mac=createHmac("sha256",cursorSecret()).update(body).digest("base64url");return`${body}.${mac}`};
const decode=(value:string|undefined,tenantId:string)=>{if(!value)return;try{const[body,sig,...extra]=value.split(".");if(!body||!sig||extra.length)throw 0;const expected=createHmac("sha256",cursorSecret()).update(body).digest(),actual=Buffer.from(sig,"base64url");if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw 0;const parsed=JSON.parse(Buffer.from(body,"base64url").toString());if(parsed.v!==1||parsed.tenantId!==tenantId||!ID.test(parsed.id)||parsed.policy!==POLICY)throw 0;return parsed.id as string}catch{throw Error("AUDIT_QUERY_INVALID")}};
async function context(auth:ServerAuthContextV1,tenantId:string|undefined,permission:AuthorizationPermission){const resolved=await resolveTenantAuthorizationContext({authentication:auth,...(tenantId?{requestedTenantId:tenantId}:{})});if(!resolved.ok)return safe(["TENANT_REQUIRED","TENANT_SELECTION_REQUIRED"].includes(resolved.error.code)?"TENANT_SELECTION_REQUIRED":"RESOURCE_NOT_AVAILABLE",["TENANT_REQUIRED","TENANT_SELECTION_REQUIRED"].includes(resolved.error.code)?400:404,auth);if(!permissionsForRole(resolved.context.role).includes(permission))return safe("FORBIDDEN",403,auth);return{ok:true as const,value:resolved.context}}
async function audit(tenantId:string,auth:ServerAuthContextV1,action:string,outcome:string,details:object={}){await db().doc(`tenants/${tenantId}/governanceAuditEvents/${auth.requestId}:${action}`).create({schemaVersion:"governance-audit-event.v1",action,outcome,principalReference:principal(auth),requestId:auth.requestId,correlationId:auth.correlationId,policyVersion:POLICY,piiPresent:false,createdAt:new Date().toISOString(),...details})}

export async function createSafeUserProfile(auth:ServerAuthContextV1,raw:unknown){if(auth.principal.kind!=="firebase_user")return safe("AUTH_INVALID",403,auth);const userId=principal(auth),x=raw as any;if(!x||typeof x!=="object"||Array.isArray(x)||Object.keys(x).some(k=>k!=="displayName")||typeof x.displayName!=="string"||x.displayName.trim().length>120)return safe("OPERATION_FAILED",400,auth);const ref=db().doc(`users/${userId}`),now=new Date().toISOString();await db().runTransaction(async tx=>{const current=await tx.get(ref);if(current.exists)return;tx.create(ref,{schemaVersion:"user-profile.v1",userId,displayName:x.displayName.trim(),profileVersion:"profile-v1",authorityPresent:false,createdAt:now,updatedAt:now})});return Object.freeze({ok:true as const,status:200,profile:{userId,displayName:x.displayName.trim(),authorityPresent:false},requestId:auth.requestId,correlationId:auth.correlationId})}

export async function listAvailableTenants(auth:ServerAuthContextV1){if(auth.principal.kind!=="firebase_user")return safe("AUTH_INVALID",403,auth);const refs=await db().collection(`userTenantMemberships/${auth.principal.uid}/tenants`).orderBy(FieldPath.documentId()).limit(50).get(),items=[];for(const ref of refs.docs){const resolved=await resolveTenantAuthorizationContext({authentication:auth,requestedTenantId:ref.id});if(resolved.ok)items.push(Object.freeze({tenantId:resolved.context.tenantId,role:resolved.context.role,membershipVersion:resolved.context.membershipVersion,tenantVersion:resolved.context.tenantVersion,status:"active"}))}return Object.freeze({ok:true as const,status:200,tenants:Object.freeze(items),requestId:auth.requestId,correlationId:auth.correlationId})}

export async function selectActiveTenant(auth:ServerAuthContextV1,raw:unknown,failAudit=false){if(auth.principal.kind!=="firebase_user")return safe("AUTH_INVALID",403,auth);const userId=principal(auth),x=raw as any;if(!x||Object.keys(x).some(k=>k!=="tenantId")||!ID.test(x.tenantId||""))return safe("ACTIVE_TENANT_INVALID",400,auth);const resolved=await resolveTenantAuthorizationContext({authentication:auth,requestedTenantId:x.tenantId});if(!resolved.ok)return safe("ACTIVE_TENANT_INVALID",403,auth);try{await db().runTransaction(async tx=>{if(failAudit)throw Error("audit");tx.set(db().doc(`userActiveTenantSelections/${userId}`),{schemaVersion:"active-tenant-selection.v1",userId,tenantId:resolved.context.tenantId,membershipVersion:resolved.context.membershipVersion,tenantVersion:resolved.context.tenantVersion,selectionVersion:createHash("sha256").update(`${userId}:${resolved.context.tenantId}:${resolved.context.membershipVersion}:${resolved.context.tenantVersion}`).digest("hex").slice(0,24),updatedAt:new Date().toISOString()});tx.create(db().doc(`tenants/${resolved.context.tenantId}/governanceAuditEvents/${auth.requestId}:tenant.select`),{schemaVersion:"governance-audit-event.v1",action:"tenant.select",outcome:"allowed",principalReference:userId,requestId:auth.requestId,correlationId:auth.correlationId,policyVersion:POLICY,piiPresent:false,createdAt:new Date().toISOString()})})}catch{return safe("AUDIT_REQUIRED",500,auth)}return Object.freeze({ok:true as const,status:200,tenant:{tenantId:resolved.context.tenantId,membershipVersion:resolved.context.membershipVersion,tenantVersion:resolved.context.tenantVersion},requestId:auth.requestId,correlationId:auth.correlationId})}

export async function listTenantMembers(auth:ServerAuthContextV1,tenantId:string|undefined){const c=await context(auth,tenantId,"membership.read");if(!c.ok)return c;const snap=await db().collection(`tenants/${c.value.tenantId}/members`).orderBy(FieldPath.documentId()).limit(101).get();if(snap.size>100)return safe("OPERATION_FAILED",413,auth);await audit(c.value.tenantId,auth,"membership.list","allowed",{resultCount:snap.size});return Object.freeze({ok:true as const,status:200,members:Object.freeze(snap.docs.map(d=>{const x=d.data();return Object.freeze({userId:d.id,role:x.role,membershipStatus:x.membershipStatus,membershipVersion:x.membershipVersion||x.updatedAt?.toDate?.().toISOString?.()||"legacy"})})),requestId:auth.requestId,correlationId:auth.correlationId})}

export async function listUnderwriterDirectory(auth:ServerAuthContextV1,tenantId:string|undefined){const c=await context(auth,tenantId,"assignment.read");if(!c.ok)return c;const snap=await db().collection(`tenants/${c.value.tenantId}/members`).where("membershipStatus","==","active").where("role","==","underwriter").limit(100).get();await audit(c.value.tenantId,auth,"underwriter.directory.read","allowed",{resultCount:snap.size});return Object.freeze({ok:true as const,status:200,underwriters:Object.freeze(snap.docs.map(d=>Object.freeze({userId:d.id,eligible:true,membershipVersion:d.data().membershipVersion||"legacy"}))),requestId:auth.requestId,correlationId:auth.correlationId})}

const AUDIT_SOURCES=Object.freeze(["governanceAuditEvents","authorizationAuditEvents","applicationCreateAuditEvents","billingOperationAudit"]);
export async function readTenantAudit(auth:ServerAuthContextV1,input:{tenantId?:string;pageSize?:string|null;cursor?:string|null;eventType?:string|null}){const c=await context(auth,input.tenantId,"audit.read");if(!c.ok)return c;const size=input.pageSize?Number(input.pageSize):25;if(!Number.isInteger(size)||size<1||size>MAX_PAGE||(input.eventType&&!AUDIT_SOURCES.includes(input.eventType)))return safe("AUDIT_QUERY_INVALID",400,auth);let after:string|undefined;try{after=decode(input.cursor||undefined,c.value.tenantId)}catch{return safe("AUDIT_QUERY_INVALID",400,auth)}const sources=input.eventType?[input.eventType]:AUDIT_SOURCES,rows:any[]=[];for(const source of sources){let q:any=db().collection(`tenants/${c.value.tenantId}/${source}`).orderBy(FieldPath.documentId());if(after)q=q.startAfter(after);const snap=await q.limit(size+1).get();for(const d of snap.docs){const x=d.data();rows.push({id:d.id,eventType:source,action:String(x.action||"unknown").slice(0,128),outcome:String(x.outcome||x.decision||"unknown").slice(0,64),occurredAt:String(x.createdAt||x.persistedAt||x.occurredAt||""),principalReference:String(x.principalReference||"unknown").slice(0,128),policyVersion:String(x.policyVersion||"unknown").slice(0,128)})}}rows.sort((a,b)=>a.id.localeCompare(b.id));const page=rows.slice(0,size),last=page.at(-1);await audit(c.value.tenantId,auth,"audit.search","allowed",{resultCount:page.length});return Object.freeze({ok:true as const,status:200,events:Object.freeze(page),nextCursor:rows.length>size&&last?encode({v:1,tenantId:c.value.tenantId,id:last.id,policy:POLICY}):null,requestId:auth.requestId,correlationId:auth.correlationId})}

export async function exportTenantAudit(auth:ServerAuthContextV1,raw:unknown,failAudit=false){const x=raw as any;if(!x||typeof x!=="object"||Array.isArray(x)||Object.keys(x).some(k=>!["tenantId","idempotencyKey","eventType","limit"].includes(k))||!ID.test(x.idempotencyKey||"")||!Number.isInteger(x.limit)||x.limit<1||x.limit>MAX_EXPORT)return safe("AUDIT_QUERY_INVALID",400,auth);const c=await context(auth,x.tenantId,"audit.export");if(!c.ok)return c;const commandId=createHash("sha256").update(`${c.value.tenantId}:${auth.principal.kind==="firebase_user"?auth.principal.uid:"invalid"}:${x.idempotencyKey}`).digest("hex"),ref=db().doc(`tenants/${c.value.tenantId}/auditExportCommands/${commandId}`),fingerprint=createHash("sha256").update(JSON.stringify([c.value.tenantId,x.eventType||null,x.limit,POLICY])).digest("hex"),existing=await ref.get();if(existing.exists){if(existing.data()?.fingerprint!==fingerprint)return safe("COMMAND_CONFLICT",409,auth);return Object.freeze({ok:true as const,status:200,export:existing.data()?.receipt,requestId:auth.requestId,correlationId:auth.correlationId})}const read=await readTenantAudit(auth,{tenantId:c.value.tenantId,pageSize:String(Math.min(x.limit,MAX_PAGE)),eventType:x.eventType||null});if(!read.ok)return read;const rows=read.events.slice(0,x.limit),csv=["eventType,action,outcome,occurredAt,principalReference,policyVersion",...rows.map((r:any)=>[r.eventType,r.action,r.outcome,r.occurredAt,r.principalReference,r.policyVersion].map((v:any)=>`"${String(v).replace(/"/g,'""')}"`).join(","))].join("\r\n"),receipt=Object.freeze({schemaVersion:"tenant-audit-export.v1",format:"csv",rowCount:rows.length,content:csv,retentionDays:30,policyVersion:POLICY});try{await db().runTransaction(async tx=>{if(failAudit)throw Error("audit");tx.create(ref,{schemaVersion:"audit-export-command.v1",fingerprint,status:"completed",receipt,createdAt:new Date().toISOString()});tx.create(db().doc(`tenants/${c.value.tenantId}/governanceAuditEvents/${auth.requestId}:audit.export`),{schemaVersion:"governance-audit-event.v1",action:"audit.export",outcome:"allowed",principalReference:auth.principal.kind==="firebase_user"?auth.principal.uid:"invalid",rowCount:rows.length,requestId:auth.requestId,correlationId:auth.correlationId,policyVersion:POLICY,piiPresent:false,createdAt:new Date().toISOString()})})}catch{return safe("AUDIT_REQUIRED",500,auth)}return Object.freeze({ok:true as const,status:200,export:receipt,requestId:auth.requestId,correlationId:auth.correlationId})}
