"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
const label=(v:string)=>String(v||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function IdentityLifecyclePage(){
 const[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[email,setEmail]=useState(""),[role,setRole]=useState("underwriter"),[lastToken,setLastToken]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/governance/identity",{cache:"no-store"}),body=await response.json().catch(()=>null);if(!response.ok||!body?.ok)throw Error(body?.error?.message||"Identity administration is unavailable.");setData(body.identity);setError("")},[]);
 useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
 const command=async(body:any)=>{setBusy(true);try{const response=await fetch("/api/governance/identity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})}),result=await response.json().catch(()=>null);if(!response.ok||!result?.ok)throw Error(result?.error?.message||result?.error?.code||"Identity command failed.");if(result.receipt?.token)setLastToken(result.receipt.token);await load();return result}catch(e:any){setError(e.message);await load().catch(()=>{})}finally{setBusy(false)}};
 if(!data)return <div className="v-card p-8">{error||"Loading identity lifecycle…"}</div>;
 return <div className="space-y-4"><header className="rounded-2xl bg-slate-950 text-white p-6"><Link href="/admin/governance" className="text-xs text-slate-300">← Enterprise Governance</Link><h1 className="text-2xl font-semibold mt-2">Identity Lifecycle & Provisioning</h1><p className="text-sm text-slate-300 mt-2">Authentication proves identity. Versioned membership determines authority.</p></header>{error?<div className="rounded-xl bg-red-50 text-red-800 p-3 text-sm">{error}</div>:null}
 <section className="v-card p-5"><h2 className="font-semibold">Invite identity</h2><div className="grid md:grid-cols-[2fr_1fr_auto] gap-2 mt-3"><input className="border rounded-lg p-2 text-sm" type="email" placeholder="user@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select className="border rounded-lg p-2 text-sm" value={role} onChange={e=>setRole(e.target.value)}>{["admin","underwriter","processor","loan_officer","viewer"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><button className="v-btn-primary" disabled={busy||!email} onClick={()=>void command({commandType:"invite",email,role,teamIds:[],expiresInDays:7}).then(()=>setEmail(""))}>Create invitation</button></div>{lastToken?<div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs"><b>One-time acceptance token:</b> <code className="break-all">{lastToken}</code><div className="mt-1">Copy it now. Only its hash is persisted.</div></div>:null}</section>
 <section className="v-card p-5"><h2 className="font-semibold">Pending invitations</h2><div className="space-y-2 mt-3">{data.invitations.map((invite:any)=><div className="border rounded-xl p-3 flex justify-between gap-3" key={invite.invitationId}><div><div className="text-sm font-medium">{invite.emailMasked} · {label(invite.role)}</div><div className="text-xs v-muted">{label(invite.status)} · Expires {new Date(invite.expiresAt).toLocaleString()}</div></div>{invite.status==="pending"?<button className="v-btn-danger text-xs" disabled={busy} onClick={()=>void command({commandType:"cancel_invitation",invitationId:invite.invitationId})}>Cancel</button>:null}</div>)}</div></section>
 <section className="v-card p-5"><h2 className="font-semibold">Memberships and authorization status</h2><div className="overflow-x-auto mt-3"><table className="w-full text-sm"><thead><tr className="border-b text-left">{["Identity","State","Role","Teams","Authority","Actions"].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.members.map((member:any)=><tr className="border-b align-top" key={member.userId}><td className="p-2 font-medium">{member.userId}<div className="text-xs v-muted">Membership v{member.membershipVersion}</div></td><td className="p-2">{label(member.status)}</td><td className="p-2"><select className="border rounded p-1" disabled={busy} value={member.role} onChange={e=>void command({commandType:"change_role",userId:member.userId,role:e.target.value,expectedMembershipVersion:member.membershipVersion,expectedAuthorizationVersion:member.authorizationVersion,reason:"role_reassignment"})}>{["owner","admin","underwriter","processor","loan_officer","viewer"].map(x=><option key={x}>{x}</option>)}</select></td><td className="p-2">{member.teamIds.join(", ")||"Tenant-wide"}</td><td className="p-2 text-xs max-w-40 break-all">{member.authorizationVersion}</td><td className="p-2"><div className="flex gap-1 flex-wrap">{member.status==="pending"?<button className="v-btn text-xs" disabled={busy} onClick={()=>void command({commandType:"activate",userId:member.userId,expectedMembershipVersion:member.membershipVersion,expectedAuthorizationVersion:member.authorizationVersion,reason:"onboarding_complete"})}>Activate</button>:null}{member.status==="active"?<button className="v-btn text-xs" disabled={busy} onClick={()=>void command({commandType:"suspend",userId:member.userId,expectedMembershipVersion:member.membershipVersion,expectedAuthorizationVersion:member.authorizationVersion,reason:"administrative_suspension"})}>Suspend</button>:null}{member.status==="suspended"?<button className="v-btn text-xs" disabled={busy} onClick={()=>void command({commandType:"reactivate",userId:member.userId,expectedMembershipVersion:member.membershipVersion,expectedAuthorizationVersion:member.authorizationVersion,reason:"access_restored"})}>Reactivate</button>:null}{member.status!=="archived"?<button className="v-btn-danger text-xs" disabled={busy} onClick={()=>window.confirm("Archive this membership and revoke access?")&&void command({commandType:"archive",userId:member.userId,expectedMembershipVersion:member.membershipVersion,expectedAuthorizationVersion:member.authorizationVersion,reason:"membership_archived"})}>Archive</button>:null}</div></td></tr>)}</tbody></table></div></section>
 <section className="v-card p-5"><h2 className="font-semibold">Immutable membership history</h2><div className="space-y-2 mt-3">{data.history.map((event:any)=><div className="border rounded-xl p-3" key={event.eventId}><div className="flex justify-between"><span className="font-medium text-sm">{label(event.eventType)}</span><span className="text-xs">Membership v{event.membershipVersion}</span></div><div className="text-xs v-muted mt-1">Target {event.targetUserId} · Actor {event.actorId} · {event.createdAt?new Date(event.createdAt).toLocaleString():"Time unavailable"}</div><div className="text-xs mt-1">{event.reason}</div></div>)}</div></section></div>
}
